-- brighter-super: Brighter Super -- PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (as of 2026-06-30, AUD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Brighter Super', 'Superannuation Fund', 'Australia', 'https://www.brightersuper.com.au');
  select * into f from ingest.fund_for('Private equity mandate (Harbourvest Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:5291cf7b5f181e85c8f04e27b54a58a9', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Harbourvest Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Harbourvest Partners)', null, 'AUD', null, 'private_equity', null, null, 50064404, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (LGT Fund Managers)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:d0a891a3b0f7ca8081aeb2294b86a1d4', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('LGT Fund Managers', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (LGT Fund Managers)', null, 'AUD', null, 'private_equity', null, null, 48029647, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (ROC Capital Pty Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:489f1a5e344fa7b757f890095949b390', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('ROC Capital Pty Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (ROC Capital Pty Limited)', null, 'AUD', null, 'private_equity', null, null, 33085676, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Plato Investment Management Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:33ad0dcbabbe377cfb143c024c5f6989', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Plato Investment Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Plato Investment Management Limited)', null, 'AUD', null, 'private_equity', null, null, 24261098, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Industry Super Holdings PTY. Ltd.)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:6061305e647c93936f1f94a06cd13820', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Industry Super Holdings PTY. Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Industry Super Holdings PTY. Ltd.)', null, 'AUD', null, 'private_equity', null, null, 3444122, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (QIC Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:8d41187fb7f1622cda26c7c8fb2360b8', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('QIC Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (QIC Limited)', null, 'AUD', null, 'private_equity', null, null, 2267092, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Hamilton Lane)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:a47bafee8a2b108be3e5af4343b66283', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Hamilton Lane', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Hamilton Lane)', null, 'AUD', null, 'private_equity', null, null, 1224502, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Stafford Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:0c4018f5209253e1bea379b5d3415548', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Stafford Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Stafford Capital)', null, 'AUD', null, 'private_equity', null, null, 330569, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Russell Investments)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:c4699f89d9d39aa75ff60e8632875052', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Russell Investments', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Russell Investments)', null, 'AUD', null, 'private_equity', null, null, 134520, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (IFM Investors Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:8a6bb0f7b35d752aa56f05b09d8664a2', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 71579, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Lexington Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:54802498045e5a6b510602f0bd8d28d7', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Lexington Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Lexington Capital)', null, 'AUD', null, 'private_equity', null, null, 15659, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (QIC Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:a276a3d8593e2e748240f4aedfd93fb8', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('QIC Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (QIC Limited)', null, 'AUD', null, 'real_estate', null, null, 35593091, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Charter Hall Investment Management Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:f790982482f7d3fd5e60a5e8511db93c', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Charter Hall Investment Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Charter Hall Investment Management Limited)', null, 'AUD', null, 'real_estate', null, null, 26759163, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (CIM Group)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:79142c7ef6b08c596ed0f5c7f320e1d8', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('CIM Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (CIM Group)', null, 'AUD', null, 'real_estate', null, null, 22746520, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Mirvac Funds Management Australia Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:58a63833eb79c3aaab689989c0efa051', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Mirvac Funds Management Australia Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Mirvac Funds Management Australia Limited)', null, 'AUD', null, 'real_estate', null, null, 22469749, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Dexus Capital Funds Management Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:b026b5a70a8631be0b79c889b4cfa6fc', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Dexus Capital Funds Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Dexus Capital Funds Management Limited)', null, 'AUD', null, 'real_estate', null, null, 22218973, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (GPT)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:fe69171ddd32e0bbcd4a82fa3e21a6b2', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('GPT', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (GPT)', null, 'AUD', null, 'real_estate', null, null, 12369654, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Barwon Investment Partners)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:494cdad79c5ee83a1e2627a9614be91c', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Barwon Investment Partners', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Barwon Investment Partners)', null, 'AUD', null, 'real_estate', null, null, 11788957, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Barings Australia Property Pty Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:cfb8b821776df4e89c4f609f932875de', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Barings Australia Property Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Barings Australia Property Pty Ltd)', null, 'AUD', null, 'real_estate', null, null, 10461740, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Lendlease Corp. Ltd.)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:a537c31f59da9686d91b2d583c87efd0', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Lendlease Corp. Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Lendlease Corp. Ltd.)', null, 'AUD', null, 'real_estate', null, null, 409645, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (AMP Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:22d341c41c14bee5662b4b7b7af01fef', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('AMP Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (AMP Limited)', null, 'AUD', null, 'real_estate', null, null, 85233, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Palisade Investment Partners Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:02c234a231056ff3b03bbd858f49902c', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Palisade Investment Partners Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Palisade Investment Partners Limited)', null, 'AUD', null, 'infrastructure', null, null, 73814629, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Macquarie Infrastructure Partners Inc)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:f49698e0e6a8bcf81058359bc1e8a55f', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Macquarie Infrastructure Partners Inc', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Macquarie Infrastructure Partners Inc)', null, 'AUD', null, 'infrastructure', null, null, 40015914, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (I Squared Capital)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:1f3349f6d27b6a245053823d85d79aad', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('I Squared Capital', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (I Squared Capital)', null, 'AUD', null, 'infrastructure', null, null, 31669874, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (QIC Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:a66f2103d281879d5685b9b43e54f6c6', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('QIC Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (QIC Limited)', null, 'AUD', null, 'infrastructure', null, null, 24418207, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (EQT Fund Management)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:982ef9726a14e83935091f84f04c0af7', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('EQT Fund Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (EQT Fund Management)', null, 'AUD', null, 'infrastructure', null, null, 22780872, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Macquarie Asset Management)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:ba99b6dc2870ae39a9d871f7629f4466', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Macquarie Asset Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Macquarie Asset Management)', null, 'AUD', null, 'infrastructure', null, null, 20976505, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Ardian)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:7421b0ebd3eca177253d9b5d6207ef2c', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Ardian', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Ardian)', null, 'AUD', null, 'infrastructure', null, null, 18377442, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (First Sentier Investors)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:318124400ecfb7e84b1635b7f585a316', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('First Sentier Investors', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (First Sentier Investors)', null, 'AUD', null, 'infrastructure', null, null, 14100409, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Administrator Macquarie)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:cc699629e89bde102981d38838e76d28', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Administrator Macquarie', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Administrator Macquarie)', null, 'AUD', null, 'infrastructure', null, null, 3113637, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Morgan Stanley)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:4121f4cc37d459af6189d830c548ebd5', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Morgan Stanley', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Morgan Stanley)', null, 'AUD', null, 'infrastructure', null, null, 594375, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Riparian Capital Partners)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:859ab192624389072781b87de60554f6', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('Riparian Capital Partners', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Riparian Capital Partners)', null, 'AUD', null, null, null, null, 394372, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (K2 Asset Management Ltd)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:brighter-super:brighter-super:70ba111d9b6cf78c1bf0876be7300de5', v_lp, f.gp_company_id, f.fund_id, 'Brighter Super', coalesce('K2 Asset Management Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (K2 Asset Management Ltd)', null, 'AUD', null, null, null, null, 31239, null, null, '2026-06-30', 'PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30 (p. 1)', 'lp_disclosure', 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - PHD SCHEDULE 8D TABLE 1 - PORTFOLIO HOLDINGS INFORMATION FOR INVESTMENT OPTION - Balanced Accumulation - ASSETS - 2026-06-30'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.brightersuper.com.au/-/media/public/files/portfolio-holdings-disclosure-june-2026/balanced_accumulation_30june2026_table1.csv?la=en') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Brighter Super', 'doc', 'brighter-super', 'rows', 33));
end $$;
