-- caresuper: CareSuper -- CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (as of 2026-06-30, AUD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('CareSuper', 'Superannuation Fund', 'Australia', 'https://www.caresuper.com.au');
  select * into f from ingest.fund_for('Private equity mandate (Adams Street Partners LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:d7d85ea6697591a76fd20bbcbc1af1ba', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Adams Street Partners LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Adams Street Partners LLC)', null, 'AUD', null, 'private_equity', null, null, 488065820, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Athora Holdings Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:d71b42d999b7c1b4c3e88e8372e0f143', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Athora Holdings Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Athora Holdings Ltd)', null, 'AUD', null, 'private_equity', null, null, 323727098, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Ausbil Investment Management Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:2fbb680d852702b6930e45133de42b6f', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Ausbil Investment Management Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Ausbil Investment Management Ltd)', null, 'AUD', null, 'private_equity', null, null, 7588401, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Avenue Capital Group LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:ee4da16512628830fcf326efaad02311', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Avenue Capital Group LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Avenue Capital Group LLC)', null, 'AUD', null, 'private_equity', null, null, 3671702, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (BioScience Managers Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:b4ecba14d8febb402e9577eb551cd31c', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('BioScience Managers Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (BioScience Managers Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 0, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Blackbird Ventures Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:d0bf8b07bd051569551a75356b462776', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Blackbird Ventures Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Blackbird Ventures Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 103163436, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Carnegie Venture Capital Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:6ea1a818ae54afd0100473a464d1b7e6', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Carnegie Venture Capital Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Carnegie Venture Capital Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 254286, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (GBS Venture Partners Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:7df0f07d97d96e20cc1d89ac3d467300', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('GBS Venture Partners Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (GBS Venture Partners Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 3127388, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (HarbourVest Partners LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:3b4d6ef90d8e0da8277d18b89f54c2f5', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('HarbourVest Partners LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (HarbourVest Partners LLC)', null, 'AUD', null, 'private_equity', null, null, 210864740, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (IFM Investors Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:8a6bb0f7b35d752aa56f05b09d8664a2', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 3943833, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Intermediate Capital Group PLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:98555e6de4a83b3bd9867416d42f73ca', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Intermediate Capital Group PLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Intermediate Capital Group PLC)', null, 'AUD', null, 'private_equity', null, null, 1399533, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Lennox Capital Partners Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:f44bbd9f444f70c8850864f07d6a38b3', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Lennox Capital Partners Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Lennox Capital Partners Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 23017800, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Lexington Partners LP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:856691b8540eeed85b882147073cf6c0', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Lexington Partners LP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Lexington Partners LP)', null, 'AUD', null, 'private_equity', null, null, 11349832, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (LGT Capital Partners Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:3da636b2c0b09762cfe8d75ff6cd9741', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('LGT Capital Partners Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (LGT Capital Partners Ltd)', null, 'AUD', null, 'private_equity', null, null, 226249466, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Partners Group Holding AG)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:149283cc1f517642d2b6caa96d0932d6', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Partners Group Holding AG', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Partners Group Holding AG)', null, 'AUD', null, 'private_equity', null, null, 251467233, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Roc Capital Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:1dc4285335e90c0f1ac81d26d7ac62fc', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Roc Capital Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Roc Capital Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 432568928, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Siguler Guff Advisers LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:16ddc76a5670e42578d2527a188a7b7e', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Siguler Guff Advisers LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Siguler Guff Advisers LLC)', null, 'AUD', null, 'private_equity', null, null, 254133744, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Square Peg Capital Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:9e470eaa25a4cb95205ae3f87b8dae6c', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Square Peg Capital Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Square Peg Capital Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 136709434, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (StepStone Group Holdings LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:677b592fd3820575ec479520449e5cd3', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('StepStone Group Holdings LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (StepStone Group Holdings LLC)', null, 'AUD', null, 'private_equity', null, null, 236739158, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (TCW Asset Management Company LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:a1c9a274a8374cb8f52912a237e2cf62', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('TCW Asset Management Company LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (TCW Asset Management Company LLC)', null, 'AUD', null, 'private_equity', null, null, 65482, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (UBS Securities Australia Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:4f708aae5fcaa1f95456e9fcd0f2c639', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('UBS Securities Australia Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (UBS Securities Australia Ltd)', null, 'AUD', null, 'private_equity', null, null, 324211, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Wilshire Associates Inc)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:76e01e12d283a2df45cb89e34e50123c', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Wilshire Associates Inc', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Wilshire Associates Inc)', null, 'AUD', null, 'private_equity', null, null, 1275856, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Charter Hall Group)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:7f1e91e251d47e3a08789e9077785d86', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Charter Hall Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Charter Hall Group)', null, 'AUD', null, 'real_estate', null, null, 1182075750, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Dexus)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:7e7f7d8c3f83786633de55493295bdb7', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Dexus', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Dexus)', null, 'AUD', null, 'real_estate', null, null, 428318456, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (GPT Funds Management Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:32a7f335e84bad01e7c357c69e9893db', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('GPT Funds Management Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (GPT Funds Management Ltd)', null, 'AUD', null, 'real_estate', null, null, 8424519, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Gresham Partners Group Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:d2812f6900f210517210e30714e76de4', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Gresham Partners Group Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Gresham Partners Group Ltd)', null, 'AUD', null, 'real_estate', null, null, 511011, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (HMC Capital Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:6b94ed0dc1e68080f70915edca87fb69', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('HMC Capital Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (HMC Capital Ltd)', null, 'AUD', null, 'real_estate', null, null, 62146619, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (IFM Investors Pty Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:1c0704f63b92fff38dae044e5ca12899', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'real_estate', null, null, 424681357, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Investa Property Group)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:4d3097502e708383e548956e52d436e5', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Investa Property Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Investa Property Group)', null, 'AUD', null, 'real_estate', null, null, 83379061, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Lendlease Real Estate Investments Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:8359f9b162a708a83860e3c2d4ab26ee', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Lendlease Real Estate Investments Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Lendlease Real Estate Investments Ltd)', null, 'AUD', null, 'real_estate', null, null, 198456526, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Nuveen LLC)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:0b78f97d286fcfed324f933891cbfb29', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Nuveen LLC', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Nuveen LLC)', null, 'AUD', null, 'real_estate', null, null, 289031248, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Antin Infrastructure Partners SAS)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:787968fcf685677772ad8770155ca218', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Antin Infrastructure Partners SAS', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Antin Infrastructure Partners SAS)', null, 'AUD', null, 'infrastructure', null, null, 352384305, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Dexus)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:770b1f1c6f9be08a3054c0b66dd4d4e6', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Dexus', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Dexus)', null, 'AUD', null, 'infrastructure', null, null, 303920236, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Digital Bridge Investments LLC)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:1cd5b705f6b0d53020a2943513b21686', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Digital Bridge Investments LLC', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Digital Bridge Investments LLC)', null, 'AUD', null, 'infrastructure', null, null, 369580186, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (IFM Investors Pty Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:f78811fa203c37a6bf56212d1863956d', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'infrastructure', null, null, 913987852, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Macquarie Group Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:607c78f12d13beda7b3ba90724cdc72c', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Macquarie Group Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Macquarie Group Ltd)', null, 'AUD', null, 'infrastructure', null, null, 575834437, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Morrison Private Markets Pty Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:7452730fe7b4caba6288c752fc87cbb9', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Morrison Private Markets Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Morrison Private Markets Pty Ltd)', null, 'AUD', null, 'infrastructure', null, null, 864211266, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Partners Group Holding AG)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:9040eba541e143963c93f8a850246ee9', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Partners Group Holding AG', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Partners Group Holding AG)', null, 'AUD', null, 'infrastructure', null, null, 34525812, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Patrizia Pty Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:adb248578c0ba1a5afdc109c725334c5', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Patrizia Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Patrizia Pty Ltd)', null, 'AUD', null, 'infrastructure', null, null, 355799415, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Bridgewater Associates LP)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:628004962d1781035b534e59c3fb79b6', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Bridgewater Associates LP', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Bridgewater Associates LP)', null, 'AUD', null, null, null, null, 128661157, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Fulcrum Asset Management LLP)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:95308b91cb5cf01edadecce8827032bd', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Fulcrum Asset Management LLP', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Fulcrum Asset Management LLP)', null, 'AUD', null, null, null, null, 166264423, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (PIMCO Australia Pty Ltd)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:9bea449169d3222a3e9c55269659e437', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('PIMCO Australia Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (PIMCO Australia Pty Ltd)', null, 'AUD', null, null, null, null, 242691596, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Winton Group Ltd)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:caresuper:caresuper:d5b44d57977eaf3435b3ac283b60eba5', v_lp, f.gp_company_id, f.fund_id, 'CareSuper', coalesce('Winton Group Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Winton Group Ltd)', null, 'AUD', null, null, null, null, 189777828, null, null, '2026-06-30', 'CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - CareSuper Portfolio Holdings Information for Investment Option [Accumulation - Balanced] - Table 1 Assets'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.caresuper.com.au/-/media/project/CareSuper/Files/portfolio-holdings/balanced-phd-a-cs.csv') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'CareSuper', 'doc', 'caresuper', 'rows', 43));
end $$;
