-- cbus: Cbus Super -- Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (as of 2026-06-30, AUD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Cbus Super', 'Superannuation Fund', 'Australia', 'https://www.cbussuper.com.au');
  select * into f from ingest.fund_for('Private equity mandate (Advent GP Management Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:0ee6027b08a832aac4db747c1a6dd947', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Advent GP Management Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Advent GP Management Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 5516664.78, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Archer Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:5f88965507a2b5335d3d1f171d278c81', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Archer Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Archer Capital)', null, 'AUD', null, 'private_equity', null, null, 522701.77, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Archimed)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:a3b8691ea44f38bcd099850d53662923', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Archimed', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Archimed)', null, 'AUD', null, 'private_equity', null, null, 52618771.97, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Bain Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:b59788fa3fccad371c839fd951d0b6cf', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Bain Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Bain Capital)', null, 'AUD', null, 'private_equity', null, null, 901148.01, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Barings)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:896a2cc76fa6a3fefceeb1333d0a39fe', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Barings', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Barings)', null, 'AUD', null, 'private_equity', null, null, 5900076.67, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Brookfield Asset Management)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:ab8ecf017934489f9097cca3f001cceb', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Brookfield Asset Management', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Brookfield Asset Management)', null, 'AUD', null, 'private_equity', null, null, 375941532.51, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Consolidation et Developpement Gestion)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:0c5c3fd07bac0954c45c8c5be6a9f163', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Consolidation et Developpement Gestion', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Consolidation et Developpement Gestion)', null, 'AUD', null, 'private_equity', null, null, 14956456.76, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Continuity Capital (previously Wilshire Private Markets Group))', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:5d4d917f6757d609b25707064115e78a', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Continuity Capital (previously Wilshire Private Markets Group)', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Continuity Capital (previously Wilshire Private Markets Group))', null, 'AUD', null, 'private_equity', null, null, 683770.11, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (EQT)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:2315ed9c554b553a305e4100156c1957', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('EQT', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (EQT)', null, 'AUD', null, 'private_equity', null, null, 58787737.49, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Eterna Growth Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:34410a2222e49fc8abfb8de1544707c0', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Eterna Growth Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Eterna Growth Partners)', null, 'AUD', null, 'private_equity', null, null, 52500092.66, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Harbourvest)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:250f2d99bc09f0cff8ad70d446c0ea1d', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Harbourvest', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Harbourvest)', null, 'AUD', null, 'private_equity', null, null, 301641185.98, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (IFM Investors)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:f80fbb1dab03fe7bb2685fc8afcbc308', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('IFM Investors', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (IFM Investors)', null, 'AUD', null, 'private_equity', null, null, 10181093.37, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Integrum)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:3aa5a10f22376fb5e46e2712b9f0663e', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Integrum', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Integrum)', null, 'AUD', null, 'private_equity', null, null, 53697316.13, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (LGT Capital Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:6eb3bf90827ed6f8b07932e0eb2611d1', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('LGT Capital Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (LGT Capital Partners)', null, 'AUD', null, 'private_equity', null, null, 45956034.66, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Mill Point Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:dd035bdeda1409d4a8fec3b2da114b0b', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Mill Point Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Mill Point Capital)', null, 'AUD', null, 'private_equity', null, null, 5986427.58, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Nautic Partners, LLC)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:aba3adacf4f9165db32ee99182db237d', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Nautic Partners, LLC', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Nautic Partners, LLC)', null, 'AUD', null, 'private_equity', null, null, 26767392.24, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Neuberger Berman)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:2d57623b1baac869dd02a86415ddcd9c', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Neuberger Berman', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Neuberger Berman)', null, 'AUD', null, 'private_equity', null, null, 240478283.5, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Next Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:993ae542ab0c8dba32b3c27895214b75', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Next Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Next Capital)', null, 'AUD', null, 'private_equity', null, null, 35040502.14, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Potentia Capital)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:fa5ab47f1ca9054d7fbab76f698c4fac', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Potentia Capital', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Potentia Capital)', null, 'AUD', null, 'private_equity', null, null, 64543157.12, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Roc Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:8a686b1adaaf7e02deb3236d2a55de17', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Roc Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Roc Partners)', null, 'AUD', null, 'private_equity', null, null, 468518313.15, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Stafford Capital Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:19624b045e3cf904a73d80635d415a19', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Stafford Capital Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Stafford Capital Partners)', null, 'AUD', null, 'private_equity', null, null, 9912089.63, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (The Growth Fund)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:9210f11ed4a573b9a8162a2d48453232', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('The Growth Fund', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (The Growth Fund)', null, 'AUD', null, 'private_equity', null, null, 2573823.59, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Top Tier Capital Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:7a39e075d3eb2a917cb77c25378cb0f8', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Top Tier Capital Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Top Tier Capital Partners)', null, 'AUD', null, 'private_equity', null, null, 4098082.43, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (VenCap International Plc)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:b39fdce170f1b1d30ec24601b99205f4', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('VenCap International Plc', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (VenCap International Plc)', null, 'AUD', null, 'private_equity', null, null, 28498419.22, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Wilshire)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:229539b49b5ea9509d1a9250df4de892', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Wilshire', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Wilshire)', null, 'AUD', null, 'private_equity', null, null, 509426.51, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Charter Hall)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:06db5359022c160c758b6dbf39fa626e', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Charter Hall', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Charter Hall)', null, 'AUD', null, 'real_estate', null, null, 105109635.42, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Dexus)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:7e7f7d8c3f83786633de55493295bdb7', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Dexus', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Dexus)', null, 'AUD', null, 'real_estate', null, null, 403472597.15, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (EG Funds Management)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:a454d5c3c6c6e7dfc6272fcf4be28d90', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('EG Funds Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (EG Funds Management)', null, 'AUD', null, 'real_estate', null, null, 44830529.54, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Fife Capital)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:e89905fdd83b463d1f8816cc62fc5e3f', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Fife Capital', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Fife Capital)', null, 'AUD', null, 'real_estate', null, null, 300164.84, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (GPT Group)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:74da51a29c2ba3627c58e27af5beffcd', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('GPT Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (GPT Group)', null, 'AUD', null, 'real_estate', null, null, 99733187.04, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Heitman)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:3aad60e21cd028b239632bd928f52431', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Heitman', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Heitman)', null, 'AUD', null, 'real_estate', null, null, 412480431.01, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (IFM Investors)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:83b0d9c2ebb7d5428a8f659a5905860a', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('IFM Investors', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (IFM Investors)', null, 'AUD', null, 'real_estate', null, null, 1598847131.3, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Nuveen)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:acd9b118d4c509273bd1bc1b3daaa6f8', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Nuveen', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Nuveen)', null, 'AUD', null, 'real_estate', null, null, 91213733.33, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (QIC)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:21596276b21eabd3887e5c55446874d7', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('QIC', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (QIC)', null, 'AUD', null, 'real_estate', null, null, 26811610.59, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Antin Infrastructure Partners)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:d747bcc4f8b4f1440690728fcf625188', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Antin Infrastructure Partners', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Antin Infrastructure Partners)', null, 'AUD', null, 'infrastructure', null, null, 301951763.44, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Capital Dynamics)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:ab317517c1cd0a5ca03ad154dff179e5', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Capital Dynamics', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Capital Dynamics)', null, 'AUD', null, 'infrastructure', null, null, 219246700.31, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Columbia Capital)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:a62caf7efedc87d025760b8e63cf04a1', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Columbia Capital', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Columbia Capital)', null, 'AUD', null, 'infrastructure', null, null, 462578110.23, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Copenhagen Infrastructure Partners)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:7ed9f736c380a056d1a82b010a639c49', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Copenhagen Infrastructure Partners', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Copenhagen Infrastructure Partners)', null, 'AUD', null, 'infrastructure', null, null, 107061714.92, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Foresight Group Holding Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:807a8628fc515347637477069feb8272', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Foresight Group Holding Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Foresight Group Holding Ltd)', null, 'AUD', null, 'infrastructure', null, null, 139937114.69, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (IFM Investors)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:0442787fdd393b1e0be065075af49381', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('IFM Investors', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (IFM Investors)', null, 'AUD', null, 'infrastructure', null, null, 5780656581.5, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Igneo Infrastructure Partners)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:95b42cd6a404831cfcdbe459584f6304', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Igneo Infrastructure Partners', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Igneo Infrastructure Partners)', null, 'AUD', null, 'infrastructure', null, null, 358576080.17, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (KKR)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:907c4c5007c3f0071750201659053097', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('KKR', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (KKR)', null, 'AUD', null, 'infrastructure', null, null, 1340913558.8, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Morrison)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:511447ff15b9dba6632698bf0af6eb67', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Morrison', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Morrison)', null, 'AUD', null, 'infrastructure', null, null, 1381392291.3, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Stepstone Group)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:a7528c66c8b441441c542150b67ac936', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Stepstone Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Stepstone Group)', null, 'AUD', null, 'infrastructure', null, null, 448368758.21, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Stonepeak)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:6c25a3837b701e4e2d66bc4418c9b459', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Stonepeak', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Stonepeak)', null, 'AUD', null, 'infrastructure', null, null, 320291008.41, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (UBS)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:9b42bb7a0d37a249b94c4948c546d878', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('UBS', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (UBS)', null, 'AUD', null, 'infrastructure', null, null, 6957102.7, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Australian Chamber Orchestra)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:f7c528f794d29326411340754be7df59', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Australian Chamber Orchestra', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Australian Chamber Orchestra)', null, 'AUD', null, null, null, null, 1616805.04, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Barings)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:11d2c3ec00928bcd9a574d2f46b8972c', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Barings', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Barings)', null, 'AUD', null, null, null, null, 342379147.15, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Cerberus Capital Management)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:fb95261589adc5a842317833e3db1fe4', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Cerberus Capital Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Cerberus Capital Management)', null, 'AUD', null, null, null, null, 1152183.97, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Sculptor Capital Management)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:7866fbbb2c22f5ffae520a5ab6963e02', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Sculptor Capital Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Sculptor Capital Management)', null, 'AUD', null, null, null, null, 995153.37, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Siguler Guff & Company)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:92703da2399bf0cce56264736733f789', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('Siguler Guff & Company', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Siguler Guff & Company)', null, 'AUD', null, null, null, null, 102166638.58, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (TPG Opportunities Partners II)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cbus-super:cbus:3289eaecf068859578bbe7ac5dfc9f0e', v_lp, f.gp_company_id, f.fund_id, 'Cbus Super', coalesce('TPG Opportunities Partners II', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (TPG Opportunities Partners II)', null, 'AUD', null, null, null, null, 381753.85, null, null, '2026-06-30', 'Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026 (p. 1)', 'lp_disclosure', 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Portfolio Holdings Information for Investment Option: Growth Accumulation Option - Assets - 30 June 2026'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.cbussuper.com.au/content/dam/cbus/files/governance/investment-holdings/super-growth.csv') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Cbus Super', 'doc', 'cbus', 'rows', 52));
end $$;
