-- colorado-pera-private-equity-01: Colorado PERA -- Private Equity Holdings as of December 31, 2025 (CoPERA) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := 'f1fcf63c-8869-4b6a-b8c6-c2804a17db0d'::uuid;
  select * into f from ingest.fund_for('Centennial Fund Ltd', 1982, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:3972e8643f1d1347a7504f3f75f62f12', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centennial Fund Ltd', 5000000, 'USD', 1982, 'private_equity', 5000000, 9565819, null, 9.27, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centennial Fund II', 1984, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:c7458a4ba677b70227bf5793b206332f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centennial Fund II', 5000000, 'USD', 1984, 'private_equity', 5000000, 6801204, null, 6.43, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centennial Business Development Fund', 1985, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:7b6bd53449f1667ba40fafcdc86719f3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centennial Business Development Fund', 2000000, 'USD', 1985, 'private_equity', 2000000, 3347063, null, 8.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centennial Fund III', 1987, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:b67dfc77817b73cc875ff62afa3d6c6b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centennial Fund III', 25000000, 'USD', 1987, 'private_equity', 25000000, 72147814, null, 22.04, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Columbine Venture Fund II', 1988, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:8a08769f0c93a6e0423bf8a6d61ab436', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Columbine Venture Fund II', 5000000, 'USD', 1988, 'private_equity', 5000000, 2050862, null, -9.28, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Equitable Deal Flow Fund', 1988, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:15828ad470b255099f3c35ece078f212', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Equitable Deal Flow Fund', 50000000, 'USD', 1988, 'private_equity', 72181515, 82843187, null, 4.09, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest III', 1988, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:0ae4d96a052d998734ec730fb2fe29b7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest III', 50000000, 'USD', 1988, 'private_equity', 50000000, 107995102, null, 13.76, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Accel Partners III', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:6e7f89b282fdee87cb3d7d98ae436c87', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Accel Partners III', 2000000, 'USD', 1989, 'private_equity', 2000000, 4358716, null, 14.66, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Colorado Venture Management III', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:81b6fc56ff1218387a3e8843bd2c7919', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Colorado Venture Management III', 1500000, 'USD', 1989, 'private_equity', 1500000, 3938250, null, 14.63, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Grotech Partners III', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:8a4c58013d3cbc912f9d99341ae0eef5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Grotech Partners III', 2000000, 'USD', 1989, 'private_equity', 2000000, 2039447, null, 0.28, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lehman Brothers Merchant Banking Ptnrshp', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:ee4d177ddcc873844818090cb666ab66', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lehman Brothers Merchant Banking Ptnrshp', 50000000, 'USD', 1989, 'private_equity', 42256540, 145058417, null, 30.5, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Morgan Holland Fund II', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:3223102312ba48a8823630e948215651', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Morgan Holland Fund II', 2000000, 'USD', 1989, 'private_equity', 2000000, 4196309, null, 17.45, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Nazem & Company III', 1989, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:e587ce8d473db8fb965b2a4705e0bc3c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Nazem & Company III', 3000000, 'USD', 1989, 'private_equity', 3000000, 3240890, null, 1.96, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Brantley Venture Partners II', 1990, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:f974a29e84623ecb5054b4ca723812f7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Brantley Venture Partners II', 2000000, 'USD', 1990, 'private_equity', 2000000, 2337232, null, 2.56, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Equitable Capital Private Inc & Equity Fund II', 1990, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:7565a33779e9be5816271cdcef293e06', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Equitable Capital Private Inc & Equity Fund II', 50000000, 'USD', 1990, 'private_equity', 72059423, 107372058, null, 13.6, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Gateway Venture Partners III', 1990, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:cfd90a4b0589e663591152a71c731520', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Gateway Venture Partners III', 2000000, 'USD', 1990, 'private_equity', 2000000, 4007174, null, 16.85, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest International Private Equity Partners', 1990, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:052666707006ea6fdad2beb60523e59e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest International Private Equity Partners', 30000000, 'USD', 1990, 'private_equity', 30000000, 53079245, null, 11.14, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Joseph Littlejohn & Levy Fund', 1991, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:4da38c5c9584628a746ba5d76df87d3c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Joseph Littlejohn & Levy Fund', 30000000, 'USD', 1991, 'private_equity', 33138213, 87095301, null, 33.85, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Forstmann Little Sub Debt & Equity V', 1992, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:4aa0dfa5bfe571688f323b924189f5c1', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Forstmann Little Sub Debt & Equity V', 100000000, 'USD', 1992, 'private_equity', 95785413, 113598501, null, 36.86, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Media/Communications Partners II', 1992, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:2f9067a9afa8a9b582ce92d878bf838f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Media/Communications Partners II', 3000000, 'USD', 1992, 'private_equity', 3000000, 12955329, null, 38.9, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Mohr Davidow Ventures III', 1992, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:04ebea81332af9b7dade5ccf82e82d5d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Mohr Davidow Ventures III', 3000000, 'USD', 1992, 'private_equity', 3000000, 4863980, null, 11.41, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Accel Partners IV', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:0acbfc3934ce4ac330c41a051dfcad1e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Accel Partners IV', 2000000, 'USD', 1993, 'private_equity', 2000000, 13929817, null, 77.9, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centennial Fund IV', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:b56fc77b6548970d888b61fa9c317217', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centennial Fund IV', 45000000, 'USD', 1993, 'private_equity', 45000000, 147744721, null, 38.06, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Colorado Venture Management IV', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:14c0aee1f4dbe93ee3df0d7f5d985a4c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Colorado Venture Management IV', 1700000, 'USD', 1993, 'private_equity', 1696000, 1921392, null, 2.6, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Geocapital III', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:8706ed40ed3a7d5d46f4f32bc6cd222a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Geocapital III', 1000000, 'USD', 1993, 'private_equity', 1000000, 2980458, null, 79.84, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Grotech Partners IV', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:9368c91b1774cbe2847d7d8a9482bec6', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Grotech Partners IV', 2500000, 'USD', 1993, 'private_equity', 2500000, 4272522, null, 15.19, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest IV-Direct', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:1bda0041a6c6406ddb8fd3c3c66700af', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest IV-Direct', 20000000, 'USD', 1993, 'private_equity', 20000000, 24566820, null, 5.57, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest IV-Partnership', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:96303e0608288e0e2942dafd1c792124', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest IV-Partnership', 30000000, 'USD', 1993, 'private_equity', 28500000, 110987822, null, 41.78, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Phillips-Smith Specialty Retail Group III', 1993, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:979bd2b9c84afb53852d90770e65f6e2', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Phillips-Smith Specialty Retail Group III', 2000000, 'USD', 1993, 'private_equity', 2000000, 4123186, null, 22.77, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Capital Partners II', 1994, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:6d0c02672855110d7aea2a6c9fc5cc10', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Capital Partners II', 100000000, 'USD', 1994, 'private_equity', 109106993, 238417493, null, 38.4, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Brantley Venture Partners III', 1994, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:b93934014516d8d040ecf5090e6f80ff', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Brantley Venture Partners III', 2000000, 'USD', 1994, 'private_equity', 2000000, 1871633, null, -0.88, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Joseph Littlejohn & Levy Fund II', 1994, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:f976c9ce49c08a55328f33e5f82fd190', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Joseph Littlejohn & Levy Fund II', 50000000, 'USD', 1994, 'private_equity', 56009870, 84462793, null, 7.13, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund III', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:3b61763383b54cc6dc9e1bdbcc78618b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund III', 100000000, 'USD', 1995, 'private_equity', 111972394, 160902280, null, 10.45, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Cypress Merchant Banking Partners', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:c2b359a6bb121b7b9e7bbf5d9fd9dbfe', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Cypress Merchant Banking Partners', 100000000, 'USD', 1995, 'private_equity', 103808696, 126333190, null, 2.66, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Forstmann Little Sub Debt & Equity VI', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:913707c4835ee5f78b8aa3d53c138e7a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Forstmann Little Sub Debt & Equity VI', 130000000, 'USD', 1995, 'private_equity', 139410810, 171713229, null, 8.93, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Franklin Capital Associates III', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:eb19c8406f30ec4ff736fed3c49e9f71', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Franklin Capital Associates III', 3000000, 'USD', 1995, 'private_equity', 3000000, 1970477, null, -6.64, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Intl Pvt Equity Ptnrs II-Direct', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:91be181dcf84493c02257af70ef9105a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Intl Pvt Equity Ptnrs II-Direct', 20000000, 'USD', 1995, 'private_equity', 20000000, 38019916, null, 19.57, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Intl Pvt Equity Ptnrs II-Partnership', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:29557dd6fbc4ef43d1db98853034b050', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Intl Pvt Equity Ptnrs II-Partnership', 80000000, 'USD', 1995, 'private_equity', 78400000, 110588259, null, 8.81, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Mohr Davidow Ventures IV', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:67c4bece3a01a92777f521deb38b2111', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Mohr Davidow Ventures IV', 3000000, 'USD', 1995, 'private_equity', 3000000, 41070513, null, 108.43, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Morgan Holland One Liberty III', 1995, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-01:09b1f960e867300efe64414d27f737de', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Morgan Holland One Liberty III', 2000000, 'USD', 1995, 'private_equity', 2000000, 7488386, null, 28.26, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Private Equity Holdings as of December 31, 2025 (CoPERA)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Colorado PERA', 'doc', 'colorado-pera-private-equity-01', 'rows', 40));
end $$;
