-- colorado-pera-private-equity-04: Colorado PERA -- Private Equity Holdings as of December 31, 2025 (CoPERA) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := 'f1fcf63c-8869-4b6a-b8c6-c2804a17db0d'::uuid;
  select * into f from ingest.fund_for('Blackstone Capital Partners IV', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:ae80fc2cadc4474c85f6c4df23d0abb3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Capital Partners IV', 150000000, 'USD', 2002, 'private_equity', 163652003, 319000990, null, 37.78, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners IV', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:f28f934ce5a3d86481b3f65e503e610d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners IV', 40000000, 'USD', 2002, 'private_equity', 34400000, 46938031, null, 11.51, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Francisco Partners SP', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:a95bc28c0ef02ca8dc9d04e0987b8150', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Francisco Partners SP', 15000000, 'USD', 2002, 'private_equity', 13603861, 21436267, null, 8.47, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ITU Ventures Colorado I', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:3501631516bceb134c8c17095af6b2a5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ITU Ventures Colorado I', 10000000, 'USD', 2002, 'private_equity', 9542795, 6496078, null, -14.83, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ITU Ventures West I', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:9ba0b67c7ba14c9d81840748ae459ce9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ITU Ventures West I', 10000000, 'USD', 2002, 'private_equity', 9475287, 2275219, null, -31.31, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JLL Partners IV', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:dd42145d9dc9972db98e9356f9df67fd', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JLL Partners IV', 50000000, 'USD', 2002, 'private_equity', 56397075, 80683877, null, 6.23, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock II', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:fc7522ef03bbe9092ecdde0b4dc96618', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock II', 35000000, 'USD', 2002, 'private_equity', 34144462, 101574021, null, 54.95, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TSG 4', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:d2745f41f954d8e64d7ecba17e690ea4', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TSG 4', 40000000, 'USD', 2002, 'private_equity', 39592351, 110326345, null, 36.35, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg - Bill Barrett Corporation', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:8082f6b167ffeb62b9cf92c73ed61778', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg - Bill Barrett Corporation', 8000000, 'USD', 2002, 'private_equity', 8000004, 22725345, null, 52.62, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wellspring Capital Partners III', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:9f9b27325a35097be8e501a021e9e89c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Wellspring Capital Partners III', 50000000, 'USD', 2002, 'private_equity', 49208273, 107775072, null, 26.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Galen Partners IV', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:e5014e0a35d6dace1b45ff5e5f4e3b9a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Galen Partners IV', 30000000, 'USD', 2003, 'private_equity', 31024486, 46206440, null, 8.31, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest VII-Venture Partnership Fund', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:147e6b8106a0b063e7b8f3077ecd3c37', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest VII-Venture Partnership Fund', 100000000, 'USD', 2003, 'private_equity', 59000000, 64341517, null, 4.87, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Headland Private Equity Fund 3', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:e223d758f92625c3521b1d71032d2850', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Headland Private Equity Fund 3', 30000000, 'USD', 2003, 'private_equity', 35082429, 56228037, null, 11.73, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Jefferson Partners Fund IV', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:91891c222f4b07640f720b7b14975bd0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Jefferson Partners Fund IV', 9730000, 'USD', 2003, 'private_equity', 12498881, 142, null, -69.2, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners II', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:b59ad111aadd9f3697cd112e69a6a14a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners II', 50000000, 'USD', 2003, 'private_equity', 49853714, 82146777, null, 33.78, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('SunTX Fulcrum Fund', 2003, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:f79913e4149d1f48ca6f82e7ef1cc0ef', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'SunTX Fulcrum Fund', 15000000, 'USD', 2003, 'private_equity', 17800058, 31683360, null, 5.14, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('AIG Global Emerging Markets Fund II', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:18b5c932ba05ce1d5c4712ee2bebd6b5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'AIG Global Emerging Markets Fund II', 75000000, 'USD', 2004, 'private_equity', 2594821, 2594821, null, 0.0, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Distressed Investment Fund (DIF)', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:0e9e7a3a7b5d0d9eb079e14bd14bf3be', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Distressed Investment Fund (DIF)', 35000000, 'USD', 2004, 'private_equity', 35000000, 50632043, null, 8.05, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:eedfc4a7f1b46c8ef607bc1b35d9173c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund', 45000000, 'USD', 2004, 'private_equity', 54666540, 83838016, null, 13.32, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Asia Special Situations Fund III', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:9313f078c6c6b74eb37f01da85f8c88e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Asia Special Situations Fund III', 75000000, 'USD', 2004, 'private_equity', 56736944, 83120869, null, 8.06, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CMEA VI', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:f2735ee3a9f8a1977377328d881026dc', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CMEA VI', 30000000, 'USD', 2004, 'private_equity', 28110000, 11747846, null, -12.65, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Founders Equity SBIC I', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:468d677416c6c9d92e08ce58f59ad2a7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Founders Equity SBIC I', 7500000, 'USD', 2004, 'private_equity', 7500000, 2042891, null, -27.61, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock III', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:262cd8af03d2029840335becf3f9b702', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock III', 42000000, 'USD', 2004, 'private_equity', 45130187, 23338294, null, -12.56, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LLR Equity Partners II', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:0c0f6d2740b41e2a03fcd16538338c25', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LLR Equity Partners II', 40000000, 'USD', 2004, 'private_equity', 40000000, 72561389, null, 12.25, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira Europe III', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:9046b15cfb0e7d8493422fe074fc3ccf', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira Europe III', 35394000, 'USD', 2004, 'private_equity', 31129743, 52644108, null, 40.13, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Shepherd Ventures II', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:bb96575d6824826308c92e1c53665aea', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Shepherd Ventures II', 5000000, 'USD', 2004, 'private_equity', 4350000, 2639205, null, -6.35, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology Crossover Ventures V', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:bd7aaff31a7aaa7423dc70d8952e2073', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology Crossover Ventures V', 50000000, 'USD', 2004, 'private_equity', 49575000, 91752423, null, 10.58, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TVV Equity Investors II', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:d4e79e00a5cd023b1beb6bcfdf87659f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TVV Equity Investors II', 7500000, 'USD', 2004, 'private_equity', 7500000, 11959433, null, 8.33, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Columbia Capital Equity Partners IV', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:17518d22d33759d7e2b5bacd22e04f57', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Columbia Capital Equity Partners IV', 25000000, 'USD', 2005, 'private_equity', 24602044, 53044642, null, 11.54, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners IV (D)', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:6a3371608108c01d2545bd300bac0946', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners IV (D)', 96984000, 'USD', 2005, 'private_equity', 106219322, 199440613, null, 16.74, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Elevation Partners LP', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:8372c3a7547c8c24802433777895e276', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Elevation Partners LP', 30000000, 'USD', 2005, 'private_equity', 28556534, 44725738, null, 11.82, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ITU Ventures III', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:f65b0b4dcecdcbf5fc16ad927b41288f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ITU Ventures III', 2256338, 'USD', 2005, 'private_equity', 2287588, 19210, null, -92.31, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JLL Partners V', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:b63f3ad44b462c0ab1accf0325b73b8b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JLL Partners V', 100000000, 'USD', 2005, 'private_equity', 119206129, 179292156, null, 9.61, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Kirtland Capital Partners IV', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:b0e4a95857eb12c861dc504976677a79', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Kirtland Capital Partners IV', 10000000, 'USD', 2005, 'private_equity', 9241290, 7318603, null, -2.53, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Leapfrog Ventures II', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:d36a32306636a4bc592af57ea51196f3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Leapfrog Ventures II', 15000000, 'USD', 2005, 'private_equity', 14598619, 14443622, null, -0.18, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pegasus Partners III', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:f9c772138aa3d197ce8dffcdabddb56d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pegasus Partners III', 50000000, 'USD', 2005, 'private_equity', 66538033, 52544655, null, -4.51, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Rho Ventures V', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:256a6ab7edec2226be08c5f67ff3ed30', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Rho Ventures V', 25000000, 'USD', 2005, 'private_equity', 25028947, 10042935, null, -9.61, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners III', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:0ee28b3d1b2d0784e762e0b3234d44b4', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners III', 50000000, 'USD', 2005, 'private_equity', 57450334, 73515090, null, 5.16, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity IX', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:c7cdde8baaea53996407eb7e243a0a97', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity IX', 225000000, 'USD', 2005, 'private_equity', 225000000, 387133105, null, 9.6, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund VI', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-04:7ea05536669c3d53761143e1c7cec46e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund VI', 150000000, 'USD', 2006, 'private_equity', 198934197, 296697035, null, 8.62, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Private Equity Holdings as of December 31, 2025 (CoPERA)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Colorado PERA', 'doc', 'colorado-pera-private-equity-04', 'rows', 40));
end $$;
