-- colorado-pera-private-equity-05: Colorado PERA -- Private Equity Holdings as of December 31, 2025 (CoPERA) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := 'f1fcf63c-8869-4b6a-b8c6-c2804a17db0d'::uuid;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund II', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:297cdfb59ff9a57423e6f7208ad9ce96', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund II', 60000000, 'USD', 2006, 'private_equity', 67494686, 111630228, null, 13.1, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Asia Special Situations Fund IV', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:961f36f308b61f3471a225bc102941bd', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Asia Special Situations Fund IV', 60000000, 'USD', 2006, 'private_equity', 47342520, 50422075, null, 1.45, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Special Situations Fund IV', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:af65d433ceb6437e54a4e847d7c275db', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Special Situations Fund IV', 65000000, 'USD', 2006, 'private_equity', 81833682, 106929805, null, 8.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Capital Partners V', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:a99d271e371886310d1a5a25da6d0812', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Capital Partners V', 150000000, 'USD', 2006, 'private_equity', 154648708, 252735045, null, 7.52, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Brentwood Associates Private Equity IV', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:5c67b9599b576aa10dcc2395afb518cd', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Brentwood Associates Private Equity IV', 40000000, 'USD', 2006, 'private_equity', 50311439, 91965106, null, 11.73, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Edison Venture Fund VI', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:dae617793bbda2d563069176df96e58f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Edison Venture Fund VI', 15000000, 'USD', 2006, 'private_equity', 15000000, 16612803, null, 3.35, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Euroknights V', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:f6f0fb3623529f027f4a34a6c00c90b5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Euroknights V', 30000000, 'USD', 2006, 'private_equity', 31596401, 38324444, null, 8.89, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Francisco Partners II', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:656bbebc404bb2cb4bc402dae37d394c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Francisco Partners II', 50000000, 'USD', 2006, 'private_equity', 46550000, 79014979, null, 10.37, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Highland Capital Partners VII', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:5ba9ca0604cf7c3fd7ae1908afcbb40e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Highland Capital Partners VII', 25000000, 'USD', 2006, 'private_equity', 25038297, 36105965, null, 5.57, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock IV AF', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:641b407674df2cd9c64c9f0f94d483b3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock IV AF', 40000000, 'USD', 2006, 'private_equity', 44106247, 273682072, null, 16.91, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pacven Walden Ventures VI', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:e7a3624994d71c082ad710f395e29f4b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pacven Walden Ventures VI', 15000000, 'USD', 2006, 'private_equity', 15001765, 40641245, null, 14.05, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Phoenix Equity Partners V (Phoenix Equity 2006)', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:7b5b20dcc66af9fe7d84b4f6521ab2a0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Phoenix Equity Partners V (Phoenix Equity 2006)', 28027200, 'USD', 2006, 'private_equity', 29324025, 20652239, null, -9.2, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology Crossover Ventures VI', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:6a83f7ee6bf8696ae23c72e3d75b3ba7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology Crossover Ventures VI', 50000000, 'USD', 2006, 'private_equity', 49765000, 77625648, null, 12.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Versa Capital Fund I', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:c240aa1dd00f4061754905b0ed36b3f6', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Versa Capital Fund I', 15000000, 'USD', 2006, 'private_equity', 17700000, 17760619, null, 0.07, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wellspring Capital Partners IV', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:2e9dfd46ada5d0925eccd526322efa22', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Wellspring Capital Partners IV', 50000000, 'USD', 2006, 'private_equity', 51958244, 79572039, null, 7.93, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Special Situations Fund V', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:4f5e3f346908002da7826acf20f768d1', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Special Situations Fund V', 65000000, 'USD', 2007, 'private_equity', 65680310, 86621970, null, 11.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avista Capital Partners', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:c52846ca719440337df64cc680222121', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avista Capital Partners', 35000000, 'USD', 2007, 'private_equity', 40050155, 48617837, null, 6.07, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CMEA VII', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:50a46f4beed9c2a8b77be63634524d7a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CMEA VII', 20000000, 'USD', 2007, 'private_equity', 20067332, 27311289, null, 6.68, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners V, L.P', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:468cee72184531f26eb38fac5d837a84', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners V, L.P', 40000000, 'USD', 2007, 'private_equity', 30630000, 43271809, null, 7.92, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Galen Partners V', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:aa7f065b8adfa5f770f92e3a450c163e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Galen Partners V', 30000000, 'USD', 2007, 'private_equity', 34330872, 42624503, null, 3.41, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JC Flowers II', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:71246ea196109fdd1ccd8e2c406cbf03', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JC Flowers II', 50000000, 'USD', 2007, 'private_equity', 60602574, 30526551, null, -10.29, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lighthouse Capital Partners VI', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:d0e41c6946482468dbbaa890ead0c3df', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lighthouse Capital Partners VI', 25000000, 'USD', 2007, 'private_equity', 23750000, 33937939, null, 6.84, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Noson Lawen Partners', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:1d3228350583c420fb087ff1fda9cfa0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Noson Lawen Partners', 15000000, 'USD', 2007, 'private_equity', 12863239, 12674888, null, -0.19, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pegasus Partners IV', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:de9d46a82f3c8e8e73edc6d327617a2b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pegasus Partners IV', 70000000, 'USD', 2007, 'private_equity', 82542554, 63042569, null, -5.33, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Terra Firma Capital Partners III', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:ea508581eb7471d8a6f47581bc0ddd70', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Terra Firma Capital Partners III', 65835000, 'USD', 2007, 'private_equity', 68390026, 30655409, null, -9.21, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TSG 5', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:cb51ae2aeee5cdbe2d2350b55e93bbc4', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TSG 5', 40000000, 'USD', 2007, 'private_equity', 39648413, 81513508, null, 16.83, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity X', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:70bab3181e57a7cf316f5327f197f6f8', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity X', 200000000, 'USD', 2007, 'private_equity', 200000000, 356461426, null, 9.44, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund VII', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:a6905706879e7410ee690402cf180d3d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund VII', 100000000, 'USD', 2008, 'private_equity', 128434336, 209101551, null, 22.09, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund III', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:17211c7ee7a777d723d4787f13c189c3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund III', 75000000, 'USD', 2008, 'private_equity', 91793781, 194316018, null, 20.95, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Europe Special Situations Fund', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:92f2ea3a1dd443ce51a426154d920e93', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Europe Special Situations Fund', 50000000, 'USD', 2008, 'private_equity', 41976224, 57738258, null, 11.74, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners V', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:db4f0120465d808f34bd07b4a1540a1f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners V', 98820000, 'USD', 2008, 'private_equity', 74926934, 152718293, null, 15.8, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Fortress Credit Opportunities Fund', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:3d238b90ac5d9cdd934fefa9aa6a4b86', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Fortress Credit Opportunities Fund', 75000000, 'USD', 2008, 'private_equity', 185775501, 254245248, null, 23.28, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Headland Private Equity Fund 6', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:cea83cd85f9e527569cb5848dc6a9b67', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Headland Private Equity Fund 6', 63750000, 'USD', 2008, 'private_equity', 74929685, 62671078, null, -3.95, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JLL Partners VI', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:5bd419bbdd6faf5c5d6d1599e285900b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JLL Partners VI', 100000000, 'USD', 2008, 'private_equity', 131877223, 245435596, null, 22.61, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock V', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:bf0588c299c0bbc9d4dcb52c23563a7b', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock V', 50000000, 'USD', 2008, 'private_equity', 55441882, 46611953, null, -2.46, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LLR Equity Partners III', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:5997148a22ff6c742bfdc2283e986136', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LLR Equity Partners III', 50000000, 'USD', 2008, 'private_equity', 48565437, 87432967, null, 14.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Longitude Venture Partners', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:f85918c8289b2d40d0e5a9d47500cded', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Longitude Venture Partners', 15000000, 'USD', 2008, 'private_equity', 14450461, 37600951, null, 25.21, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners IV', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:18a25020ace235b8c8229eafb28a7d25', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners IV', 50000000, 'USD', 2008, 'private_equity', 49050867, 77365425, null, 12.73, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('SunTX Capital Partners II GP', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:2d872f41fced6d1def43b84daed244d7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'SunTX Capital Partners II GP', 35000000, 'USD', 2008, 'private_equity', 52145889, 26648397, null, -21.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology Crossover Ventures VII', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-05:eeb2d2642fb1be1c9a7e2ebb20d0d022', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology Crossover Ventures VII', 75000000, 'USD', 2008, 'private_equity', 73800000, 232946546, null, 23.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Private Equity Holdings as of December 31, 2025 (CoPERA)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Colorado PERA', 'doc', 'colorado-pera-private-equity-05', 'rows', 40));
end $$;
