-- colorado-pera-private-equity-08: Colorado PERA -- Private Equity Holdings as of December 31, 2025 (CoPERA) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := 'f1fcf63c-8869-4b6a-b8c6-c2804a17db0d'::uuid;
  select * into f from ingest.fund_for('Brentwood Associates Private Equity V, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:3462e739f55d07e4c4359b3527f246fe', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Brentwood Associates Private Equity V, L.P.', 40000000, 'USD', 2014, 'private_equity', 69342365, 76674425, null, 2.72, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners VI', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:9a98833ac0268579db66cecf7ac05fb6', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners VI', 99741000, 'USD', 2014, 'private_equity', 95263357, 164532269, null, 14.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Glendon Opportunities Fund, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:d28d685d25ae62a80a465de75ff43b3d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Glendon Opportunities Fund, L.P.', 50000000, 'USD', 2014, 'private_equity', 47500000, 69674352, null, 8.48, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('GSO Capital Solutions Fund II', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:287062ebd21419f5bda04708131a791a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'GSO Capital Solutions Fund II', 50000000, 'USD', 2014, 'private_equity', 29878946, 29074288, null, -1.06, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LADEN Co-Investment Fund, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:ea6dbe9a28cf071db1aeb8e6c28dfa7a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LADEN Co-Investment Fund, L.P.', 22000000, 'USD', 2014, 'private_equity', 24057675, 20251043, null, 6.46, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LLR Equity Partners IV', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:c3b58aa17e72884f8b983630cda63ad0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LLR Equity Partners IV', 50000000, 'USD', 2014, 'private_equity', 46000000, 111736108, null, 26.77, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Marlin Heritage, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:d7b351d9c13f5d9c5ceb7e90b98e53b0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Marlin Heritage, L.P.', 25000000, 'USD', 2014, 'private_equity', 28350450, 50737481, null, 28.37, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Montauk TriGuard VI', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:5034467c17647bf4efff52481b21a253', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Montauk TriGuard VI', 30000000, 'USD', 2014, 'private_equity', 27138732, 30914340, null, 9.75, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('New Mountain Partners IV', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:43d9d2f9a8701b466bfb7f99fae0b7bf', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'New Mountain Partners IV', 75000000, 'USD', 2014, 'private_equity', 69775150, 140833174, null, 20.15, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NMP IV Rollover Fund', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:8bb54652c1c110cbbe8d5da896832452', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NMP IV Rollover Fund', 2000000, 'USD', 2014, 'private_equity', 1952003, 1754846, null, null, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira V L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:c60db33dbfef59a39c867b0339b4d937', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira V L.P.', 75000000, 'USD', 2014, 'private_equity', 64533704, 167485052, null, 20.72, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Raine Partners II LP', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:6e9e9e68d596ffea8930bb85de4f5e9e', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Raine Partners II LP', 50000000, 'USD', 2014, 'private_equity', 54147917, 137163597, null, 23.48, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners VI', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:97abcd7b1e958134eee748d8188e86d0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners VI', 50000000, 'USD', 2014, 'private_equity', 38165268, 50995923, null, 12.93, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology Crossover Ventures VIII', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:326aee6da03e23e079354ade5f9fbf75', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology Crossover Ventures VIII', 50000000, 'USD', 2014, 'private_equity', 43587508, 79794900, null, 12.17, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Energy, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:e9c978485384b0207b7c97ab66c17b47', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Energy, L.P.', 50000000, 'USD', 2014, 'private_equity', 48000000, 50359253, null, 4.79, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity XI, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:857d58fb7cd7f368b4224549d7366955', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity XI, L.P.', 20000000, 'USD', 2014, 'private_equity', 19972647, 30562397, null, 12.69, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Z Capital Special Situations Fund II', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:7a3ef9445c4c92033a939529052b9f0d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Z Capital Special Situations Fund II', 50000000, 'USD', 2014, 'private_equity', 87211406, 41156757, null, -0.26, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Arclight Energy Partners Fund VI', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:a508482a962bd4ad976229b36126ba81', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Arclight Energy Partners Fund VI', 50000000, 'USD', 2015, 'private_equity', 53331547, 49814048, null, 3.77, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Energy Partners II L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:031c4e242060e4256eed5786cf7b17fa', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Energy Partners II L.P.', 25000000, 'USD', 2015, 'private_equity', 26896346, 34613698, null, 5.35, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Comvest Investment Partners V', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:198c29e4439ab2d904d1a5a54431f908', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Comvest Investment Partners V', 50000000, 'USD', 2015, 'private_equity', 51820323, 62668344, null, 5.34, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Fortress Credit Opportunities Fund IV', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:f8e65d9055ccf3f7d265e8ae3b6e6fae', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Fortress Credit Opportunities Fund IV', 100000000, 'USD', 2015, 'private_equity', 118410979, 130633642, null, 8.25, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Francisco Partners IV', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:72f52d1beb8165ddb50b5cb777300e8a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Francisco Partners IV', 50000000, 'USD', 2015, 'private_equity', 48936383, 142060505, null, 26.37, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Genstar Capital Partners VII', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:8a96f8517a951d2c6f4c63fc376393e8', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Genstar Capital Partners VII', 75000000, 'USD', 2015, 'private_equity', 100538811, 231037338, null, 32.57, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Insight Venture Partners IX', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:bc9db6e502a5aeb58653ec0ea51d4a3a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Insight Venture Partners IX', 50000000, 'USD', 2015, 'private_equity', 52784788, 145676497, null, 23.0, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JLL Partners VII', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:1a40ab203ba188bf9c950e7a17c1b3bd', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JLL Partners VII', 100000000, 'USD', 2015, 'private_equity', 125844446, 212632184, null, 15.12, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners VIII, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:d7e68ba4e9f5797e44b17dd3bdd3e3ae', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners VIII, L.P.', 75000000, 'USD', 2015, 'private_equity', 70765166, 89727262, null, 13.66, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock VII', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:af5752c8d99db1d1509c9aa799bf091a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock VII', 50000000, 'USD', 2015, 'private_equity', 61433206, 91002074, null, 17.87, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('GCM Grosvenor Peloton II', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:65aa8c95b70c45a035b2bb883fd6f362', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'GCM Grosvenor Peloton II', 55000000, 'USD', 2015, 'private_equity', 55543206, 73102571, null, 9.12, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity XII, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:bcad415df21b2dd6fbe7e87926039de2', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity XII, L.P.', 110000000, 'USD', 2015, 'private_equity', 110312331, 202670612, null, 14.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Capital Partners VII', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:4ae77599863afca208d0f67e14708cba', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Capital Partners VII', 112500000, 'USD', 2016, 'private_equity', 119111983, 164710546, null, 10.18, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners VII, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:5814d7387c84d0300c3c2165f89a7487', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners VII, L.P.', 125000000, 'USD', 2016, 'private_equity', 93266958, 121228388, null, 12.54, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Foundry Group Next, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:91f42cba43fb1ed564c6172a9beebd72', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Foundry Group Next, L.P.', 50000000, 'USD', 2016, 'private_equity', 47062500, 16274895, null, 5.17, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Kelso Investment Associates IX, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:789f04ea37f66b8dd04466034e831dc8', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Kelso Investment Associates IX, L.P.', 50000000, 'USD', 2016, 'private_equity', 48696521, 81761173, null, 18.83, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Longitude Venture Partners III', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:5a9c0b50026506e2febbcfbb0843d670', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Longitude Venture Partners III', 36000000, 'USD', 2016, 'private_equity', 39404238, 41210298, null, 16.53, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Montauk TriGuard VII', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:310c4be8dc3c3ca0e31c8dc9508935a9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Montauk TriGuard VII', 50000000, 'USD', 2016, 'private_equity', 45099468, 37167771, null, 10.61, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners VII', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:1fa132857a4b7f206f4d672ef357858d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners VII', 150000000, 'USD', 2016, 'private_equity', 119969840, 160739699, null, 15.53, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology Crossover Ventures IX', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:ae18ccc5c222b394c63f2edd99952b96', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology Crossover Ventures IX', 75000000, 'USD', 2016, 'private_equity', 59535000, 92233704, null, 19.04, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TSG 7A', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:eeff6fc91662fdd25f80dc2085045ee9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TSG 7A', 48000000, 'USD', 2016, 'private_equity', 41895051, 78322802, null, 15.09, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TSG 7B', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:a01125e6e0ee666c2009230213fc83d9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TSG 7B', 12000000, 'USD', 2016, 'private_equity', 12487501, 8362463, null, 16.0, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Access Venture Partners IV, L.P.', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-08:5f81dc48a8d80793d573d5a5f08acbb0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Access Venture Partners IV, L.P.', 15000000, 'USD', 2017, 'private_equity', 14716822, 2168682, null, 3.92, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Private Equity Holdings as of December 31, 2025 (CoPERA)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Colorado PERA', 'doc', 'colorado-pera-private-equity-08', 'rows', 40));
end $$;
