-- colorado-pera-private-equity-07: Colorado PERA -- Private Equity Holdings as of December 31, 2025 (CoPERA) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := 'f1fcf63c-8869-4b6a-b8c6-c2804a17db0d'::uuid;
  select * into f from ingest.fund_for('PMI Mezzanine Fund', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:d3ae64b8c87bf0a66f2f87c85c06734d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'PMI Mezzanine Fund', 10000000, 'USD', 2010, 'private_equity', 2383, 1373, null, -24.39, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Portfolio Advisors Private Equity Fund IV', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:a245522a5be8e056d2bb3b87d964b10a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Portfolio Advisors Private Equity Fund IV', 15000000, 'USD', 2010, 'private_equity', 9444661, 18296192, null, 11.97, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Portfolio Advisors Private Equity Fund V', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:c68a74acb865b55e7b60cd1f33803b31', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Portfolio Advisors Private Equity Fund V', 15000000, 'USD', 2010, 'private_equity', 9926180, 18428715, null, 11.08, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Siguler Guff Fund II', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:4950ded70a7554b5152e664abc99590a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Siguler Guff Fund II', 10000000, 'USD', 2010, 'private_equity', 9670965, 10938653, null, 4.5, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Siguler Guff Fund III', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:f5bbadb41a8591b81fdb927886228e8d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Siguler Guff Fund III', 20000000, 'USD', 2010, 'private_equity', 22068207, 31572303, null, 8.41, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Technology for Information and Entertainment III', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:185fdfb4a0c7d71534e4363b21e3c14a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Technology for Information and Entertainment III', 5598000, 'USD', 2010, 'private_equity', 830900, 824928, null, -0.79, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Tenaska Power Fund II', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:800c3d90e62ea47da5a70f0333d98163', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Tenaska Power Fund II', 10000000, 'USD', 2010, 'private_equity', 8730099, 8554582, null, -0.55, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Windjammer Mezzanine and Equity Fund II', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:03afb7f4e5172493f930d8cab48e5b08', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Windjammer Mezzanine and Equity Fund II', 10000000, 'USD', 2010, 'private_equity', 4748969, 4766392, null, 0.29, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Windjammer Senior Equity Fund III', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:73bc71f991091d346e2f13092795d7ce', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Windjammer Senior Equity Fund III', 10000000, 'USD', 2010, 'private_equity', 9880802, 12333806, null, 17.67, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Arclight Energy Partners Fund V', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:2d9dd29b6e24d7d4944fb6876edcd0bb', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Arclight Energy Partners Fund V', 50000000, 'USD', 2011, 'private_equity', 50687062, 69083464, null, 8.01, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Audax Mezzanine Fund III', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:577bcb0a06f7c745758352fa2928d26c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Audax Mezzanine Fund III', 40000000, 'USD', 2011, 'private_equity', 39965646, 52668395, null, 9.55, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Special Situations Fund VI', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:5a5e6e2067c708a0074baa3c77af9ca9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Special Situations Fund VI', 50000000, 'USD', 2011, 'private_equity', 50000000, 51447519, null, 1.5, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('BC European Capital IX', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:188723467e7a7c2a4f31dd09f6a12ae7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'BC European Capital IX', 50000000, 'USD', 2011, 'private_equity', 51019335, 85906719, null, 13.22, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Capital Partners VI', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:bed7d38a93908761ed2b0c6d3acc4649', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Capital Partners VI', 75000000, 'USD', 2011, 'private_equity', 80471934, 120261587, null, 10.09, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Comvest Investment Partners IV', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:ccbab02aba602799127e20754a47db7a', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Comvest Investment Partners IV', 30000000, 'USD', 2011, 'private_equity', 30975004, 54406460, null, 28.3, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Euroknights VI', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:2a600c2ca29f33d78e5c44a869a057ae', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Euroknights VI', 36025000, 'USD', 2011, 'private_equity', 38236586, 50459307, null, 8.66, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Francisco Partners III', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:d52f936495021d46bdc0379e16bb3d6c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Francisco Partners III', 50000000, 'USD', 2011, 'private_equity', 45798451, 118194459, null, 20.12, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Strategic Partners V', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:9ceeaca44b4fba11e1019c54e2fe49c9', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Strategic Partners V', 50000000, 'USD', 2011, 'private_equity', 43257198, 69762822, null, 17.86, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wellspring Capital Partners V', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:95810c9aae65265df08ce48df5b79e70', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Wellspring Capital Partners V', 50000000, 'USD', 2011, 'private_equity', 53008261, 82862891, null, 14.82, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund IV, L.P.', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:2f57df018829df7a33047934f04954d5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund IV, L.P.', 75000000, 'USD', 2012, 'private_equity', 85063444, 142862849, null, 13.88, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avenue Europe Special Situations Fund II', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:ad18e7ba1f92daa051108ba01bc905d4', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avenue Europe Special Situations Fund II', 50000000, 'USD', 2012, 'private_equity', 50000000, 63989448, null, 7.71, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners VI, L.P.', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:783c08420c5d0e3fc5c159822116d469', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners VI, L.P.', 50000000, 'USD', 2012, 'private_equity', 35138367, 58516248, null, 14.55, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Colorado Mile High Fund', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:1606a1ffd260f4fc5ca18329009f98e0', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Colorado Mile High Fund', 50000000, 'USD', 2012, 'private_equity', 30378079, 37003034, null, 8.09, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Court Square Capital Partners III', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:1b9d61688c8aefe962aee4d039cedc17', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Court Square Capital Partners III', 50000000, 'USD', 2012, 'private_equity', 51345527, 76815633, null, 17.84, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Fortress Credit Opportunities Fund III', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:e0d8bd15c229a412c3bd099ebd389750', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Fortress Credit Opportunities Fund III', 50000000, 'USD', 2012, 'private_equity', 64761517, 84090888, null, 9.57, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Genstar Capital Partners VI', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:386add8303072430a1d55b1b04989266', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Genstar Capital Partners VI', 50000000, 'USD', 2012, 'private_equity', 75320230, 159658220, null, 36.48, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lime Rock VI', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:8ee02cc48a2ed25514a2b1085aa57d5c', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lime Rock VI', 50000000, 'USD', 2012, 'private_equity', 57976135, 52937979, null, -3.65, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pegasus Partners V', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:0e8ae2a3804a32749f7eabb8e1b5405d', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pegasus Partners V', 50000000, 'USD', 2012, 'private_equity', 66918155, 60567242, null, -2.68, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Summit Partners Growth Equity VIII', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:68d36f636e94ed2cee2d7c9a9e9c4d6f', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Summit Partners Growth Equity VIII', 75000000, 'USD', 2012, 'private_equity', 84168996, 192838975, null, 25.33, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TSG 6', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:021d8d0530002b9e33ddce3dab3e90ef', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TSG 6', 50000000, 'USD', 2012, 'private_equity', 45303753, 100662553, null, 27.5, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity XI', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:7f058dbcf3e6a838de1f6a45f52392fa', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity XI', 100000000, 'USD', 2012, 'private_equity', 107051448, 161821682, null, 11.87, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Windjammer Senior Equity Fund IV', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:549ee8768e575ac81b52ccbc5aedb6c7', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Windjammer Senior Equity Fund IV', 25000000, 'USD', 2012, 'private_equity', 23879628, 39191990, null, 11.72, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund VIII', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:ffaedf0c288dd0e796e9f4fb6ee71494', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund VIII', 80000000, 'USD', 2013, 'private_equity', 83517827, 109444847, null, 8.04, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avista Capital Partners III', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:82ea2686bdd961dfd35a06815aae04dc', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Avista Capital Partners III', 50000000, 'USD', 2013, 'private_equity', 54122327, 59862662, null, 3.21, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Grey Mountain Partners III', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:77ae687590337a5ff80c3b7f0d054366', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Grey Mountain Partners III', 25000000, 'USD', 2013, 'private_equity', 21318252, 29036574, null, 11.36, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HgCapital 7', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:1984c30d2b6a6f99a095796145100802', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HgCapital 7', 50000000, 'USD', 2013, 'private_equity', 40995319, 85578059, null, 17.0, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Co-Investment Partners III', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:674a0b6c048355b337beadd35046c700', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Co-Investment Partners III', 50000000, 'USD', 2013, 'private_equity', 59161488, 98534260, null, 16.27, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Longitude Venture Partners II', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:0d55f2d4530f94ddbdc63156c24014b3', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Longitude Venture Partners II', 25000000, 'USD', 2013, 'private_equity', 26731541, 33736684, null, 7.05, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Marlin Equity IV', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:75f6d71f0212b68592d35c2ef9f349d5', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Marlin Equity IV', 40000000, 'USD', 2013, 'private_equity', 42483686, 38307940, null, 3.5, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('W Capital Partners III, L.P.', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:colorado-pera:colorado-pera-private-equity-07:58cacbbfcfceb192e88e6adfe2af5815', v_lp, f.gp_company_id, f.fund_id, 'Colorado PERA', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'W Capital Partners III, L.P.', 50000000, 'USD', 2013, 'private_equity', 45179485, 53918391, null, 5.44, null, '2025-12-31', 'Private Equity Holdings as of December 31, 2025 (CoPERA)', 'lp_disclosure', 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Private Equity Holdings as of December 31, 2025 (CoPERA)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://content.copera.org/wp-content/uploads/2026/06/Private-Equity-Holdings-5-181C-12-25.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Colorado PERA', 'doc', 'colorado-pera-private-equity-07', 'rows', 40));
end $$;
