-- cpp-investments-jpy: CPP Investments -- <strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (as of 2026-03-31, JPY). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('CPP Investments', 'Public Pension Fund', 'Canada', 'https://www.cppinvestments.com');
  select * into f from ingest.fund_for('Bain Capital Japan Middle Market Fund', 2022, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-jpy:59be5c2a84b67d89cff2d4e0a685b351', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bain Capital Japan Middle Market Fund', 6000000000, 'JPY', 2022, 'private_equity', 7417000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bain Capital Japan Middle Market Fund II', 2026, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-jpy:a37f664485bfb8a768ebef392382b1d3', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bain Capital Japan Middle Market Fund II', 11750000000, 'JPY', 2026, 'private_equity', null, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NSSK Global 2025', 2026, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-jpy:838fb184718636519b50398c2632754f', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NSSK Global 2025', 11000000000, 'JPY', 2026, 'private_equity', null, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Tiara CG Private Equity Fund', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-jpy:c17a071a77251cc6c2866689a491d5f1', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Tiara CG Private Equity Fund', 13800000000, 'JPY', 2020, 'private_equity', 14573000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Tiara CG Private Equity Fund 2024', 2026, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-jpy:bf3b0a0e612b71db916659b13073079e', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Tiara CG Private Equity Fund 2024', 15000000000, 'JPY', 2026, 'private_equity', 2595000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - <strong>Private Equity Relationships Established as at March 31, 2026</strong> (JPY commitments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'CPP Investments', 'doc', 'cpp-investments-jpy', 'rows', 5));
end $$;
