-- cpp-investments-eur: CPP Investments -- <strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (as of 2026-03-31, EUR). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('CPP Investments', 'Public Pension Fund', 'Canada', 'https://www.cppinvestments.com');
  select * into f from ingest.fund_for('Advent International GPE IX-H', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:cbca5484af1188c0426cea4c57228993', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Advent International GPE IX-H', 669000000, 'EUR', 2019, 'private_equity', 735000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Advent International GPE X-A', 2022, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:90decc3e79c3b81026de63345c1ffb07', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Advent International GPE X-A', 662000000, 'EUR', 2022, 'private_equity', 448000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('AlpInvest Co-Inv II', 2002, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:6630d95702f5912265b5fb82577bad45', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'AlpInvest Co-Inv II', 100000000, 'EUR', 2002, 'private_equity', 95000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ardian Expansion Syclef Continuation Fund', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:16f3a56e2c0902a779142af9810fd448', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ardian Expansion Syclef Continuation Fund', 50000000, 'EUR', 2024, 'private_equity', 26000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('AXA IM Prime Genesis PE Secondaries Fund', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:df5001fd90d2c1063d8047812b645e28', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'AXA IM Prime Genesis PE Secondaries Fund', 167000000, 'EUR', 2024, 'private_equity', 130000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bain Capital Europe Fund VI', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:24d6dacc380eeba0d1160be20d0227f4', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bain Capital Europe Fund VI', 100000000, 'EUR', 2023, 'private_equity', 44000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Carlyle Europe Partners V', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:81dcb57ec518791f63f8faef304c7cd5', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Carlyle Europe Partners V', 300000000, 'EUR', 2018, 'private_equity', 349000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners IX', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:b8e29de3b1d00ab95a6ab56416486988', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners IX', 500000000, 'EUR', 2024, 'private_equity', 157000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners Strategic Opp II', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:ad1e2ead77ca1643692f46bae370aa44', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners Strategic Opp II', 250000000, 'EUR', 2020, 'private_equity', 234000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners VII', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:f1e738349a3753e6f88498d6196494fd', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners VII', 650000000, 'EUR', 2018, 'private_equity', 635000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners VIII (A)', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:fd20e3964e1d46ba6f0d693534ac5ec5', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners VIII (A)', 500000000, 'EUR', 2021, 'private_equity', 488000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners IV', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:c99cfc54dc5cc352eef7cbd9ddd0ad23', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners IV', 200000000, 'EUR', 2005, 'private_equity', 191000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners V', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:db4f0120465d808f34bd07b4a1540a1f', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners V', 350000000, 'EUR', 2008, 'private_equity', 384000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC European Equity Partners VI', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:9a98833ac0268579db66cecf7ac05fb6', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC European Equity Partners VI', 650000000, 'EUR', 2014, 'private_equity', 780000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Eighth Cinven Fund (No.1)', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:c04c4ac5613a9c7efb639943c6c45bdd', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Eighth Cinven Fund (No.1)', 300000000, 'EUR', 2024, 'private_equity', 94000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT Growth (No.1)', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:06b955f58c298be7d1e98e7a792921b4', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT Growth (No.1)', 100000000, 'EUR', 2021, 'private_equity', 97000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT IX', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:28a130497f82bd8549ba0d039a9bd3e0', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT IX', 250000000, 'EUR', 2020, 'private_equity', 283000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT VIII', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:082a48bc139a0eee2fc01a5312a84f7d', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT VIII', 200000000, 'EUR', 2018, 'private_equity', 231000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT X', 2022, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:406195ace2ccda108a05263e880ca7a8', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT X', 400000000, 'EUR', 2022, 'private_equity', 204000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HG Genesis 11 B', 2026, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:16a7f56e8678dd6aa1bc4f16dd96619e', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HG Genesis 11 B', 115000000, 'EUR', 2026, 'private_equity', null, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lion Capital Fund III', 2010, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:f9618429bcd09a01666b68ad800638dc', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lion Capital Fund III', 200000000, 'EUR', 2010, 'private_equity', 258000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Montagu VII (A)', 2025, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:23843ee9e53e55831af1c1a51311d102', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Montagu VII (A)', 100000000, 'EUR', 2025, 'private_equity', 1000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Nordic Capital Fund IX', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:94143c48d58b7ac61d25841c4228284f', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Nordic Capital Fund IX', 150000000, 'EUR', 2018, 'private_equity', 174000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Nordic Capital Fund XII', 2026, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:3e8b4f694062882cedc8f1beb811f24d', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Nordic Capital Fund XII', 200000000, 'EUR', 2026, 'private_equity', null, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira IV', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:2fceab8e794a783d9a8009ec78915978', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira IV', 150000000, 'EUR', 2006, 'private_equity', 163000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira V', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:b82242b70de65beb0b2455e25137d98a', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira V', 350000000, 'EUR', 2014, 'private_equity', 373000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira VI', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:11842f6ce7ff9c58166d7d3ff529cf3d', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira VI', 400000000, 'EUR', 2017, 'private_equity', 396000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira VII', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:bb261cb62714a5dee39366ecd4050aa2', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira VII', 375000000, 'EUR', 2019, 'private_equity', 378000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Permira VIII - 1', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:a6d6837af6dd797750ba8cb0f0d1c50e', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Permira VIII - 1', 325000000, 'EUR', 2023, 'private_equity', 217000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Summa Equity Fund III (No.2)', 2022, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:6f538cefc27d2aab590de726426812c2', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Summa Equity Fund III (No.2)', 50000000, 'EUR', 2022, 'private_equity', 36000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TDR Capital Fund IV', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:7aa823fe3426d028710a8c9f5abb5150', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TDR Capital Fund IV', 125000000, 'EUR', 2018, 'private_equity', 121000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TDR Capital V', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:42951e0531c09d419ff108e43dd31cca', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TDR Capital V', 200000000, 'EUR', 2024, 'private_equity', 106000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Fifth Cinven Fund', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:efb87a8d4488beddacbdb2899689795f', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Fifth Cinven Fund', 350000000, 'EUR', 2012, 'private_equity', 458000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Fourth Cinven Fund', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:9aaebfbb35b912d3efea205cf5e77dc4', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Fourth Cinven Fund', 250000000, 'EUR', 2006, 'private_equity', 256000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Seventh Cinven Fund', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:d225a62abb5a86a877e219289bc9425d', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Seventh Cinven Fund', 320000000, 'EUR', 2020, 'private_equity', 358000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Sixth Cinven Fund', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-eur:2dcf2e8e1797886969ea279490a56ff7', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Sixth Cinven Fund', 250000000, 'EUR', 2017, 'private_equity', 239000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - <strong>Private Equity Relationships Established as at March 31, 2026</strong> (EUR commitments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'CPP Investments', 'doc', 'cpp-investments-eur', 'rows', 36));
end $$;
