-- cpp-investments-cny: CPP Investments -- <strong>Private Equity Relationships Established as at March 31, 2026</strong> (CNY commitments) (as of 2026-03-31, CNY). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('CPP Investments', 'Public Pension Fund', 'Canada', 'https://www.cppinvestments.com');
  select * into f from ingest.fund_for('FountainVest China Growth Fund', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-cny:9045081180a0ddfd07b05918f3b999d7', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FountainVest China Growth Fund', 1500000000, 'CNY', 2008, 'private_equity', 1659000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (CNY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FountainVest II', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-cny:a4b671a40349025ac9b13cb8f2f03624', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FountainVest II', 1800000000, 'CNY', 2013, 'private_equity', 2209000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (CNY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FountainVest III', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:cpp-investments:cpp-investments-cny:9704516712812fc3fe9a6fa2e41b1734', v_lp, f.gp_company_id, f.fund_id, 'CPP Investments', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FountainVest III', 2300000000, 'CNY', 2017, 'private_equity', 2861000000, null, null, null, null, '2026-03-31', '<strong>Private Equity Relationships Established as at March 31, 2026</strong> (CNY commitments) (p. 1)', 'lp_disclosure', 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html', '2026-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - <strong>Private Equity Relationships Established as at March 31, 2026</strong> (CNY commitments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.cppinvestments.com/wp-content/uploads/2026/08/PI_Holdings_EN_Q1F27.html') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'CPP Investments', 'doc', 'cpp-investments-cny', 'rows', 3));
end $$;
