-- deg-usd: DEG - Deutsche Investitions- und Entwicklungsgesellschaft -- DEG investment list (deginvest.csv) - equity fund commitments (USD) (as of None, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('DEG - Deutsche Investitions- und Entwicklungsgesellschaft', 'Development Finance Institution', 'Germany', 'https://www.deginvest.de');
  select * into f from ingest.fund_for('Navegar III L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:da0698dd37565bc5ee6a309f6f346fe4', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Navegar III GP Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Navegar III L.P.', 40000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('SPE PEF III, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:af18478a8264bcde50ea677347f869f2', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('SPE PEF III (GP) Limited', (select name from public.companies where id = f.gp_company_id)), 'SPE PEF III, L.P.', 10000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vinci Lacan Fund IV LP, Canada', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:5fdf641e3afb43b3c469bde07cfcf577', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Vinci Lacan IV GP LLC', (select name from public.companies where id = f.gp_company_id)), 'Vinci Lacan Fund IV LP, Canada', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lendable MSME FinTech Credit Fund II SCSp, SICAV-RAIF', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:4f8bf47fe9297e08c62f74176d651ade', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Lendable MSME Fintech Credit Fund II General Partner S.a.r.l (Luxembourg corporate GP) /Luxembourg', (select name from public.companies where id = f.gp_company_id)), 'Lendable MSME FinTech Credit Fund II SCSp, SICAV-RAIF', 25000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Reforestation Fund I LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:6cc0cb37dd14eb6c966900d8e905f2ea', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('TRF General Partner I', (select name from public.companies where id = f.gp_company_id)), 'The Reforestation Fund I LP', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('African Development Partners IV, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:1cf56ce3cffa4bd23958ac9134ba97bb', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('ADP IV GP Ltd.', (select name from public.companies where id = f.gp_company_id)), 'African Development Partners IV, L.P.', 50000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Canary IV, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:ce258ecce9712076382124c2fb96e581', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Canary IV GP, LLC, United States', (select name from public.companies where id = f.gp_company_id)), 'Canary IV, L.P.', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('PI Fund V (Ontario), L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:9a91f7fbed4295c0c34d84c9535c00bc', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('PI General Partner V Ltd., Cayman Islands/Ontario', (select name from public.companies where id = f.gp_company_id)), 'PI Fund V (Ontario), L.P.', 50000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Revo Capital Fund III C.V.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:77240db610ed06e3de66bcef0ec7d816', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Revo Capital Management GP III B.V.', (select name from public.companies where id = f.gp_company_id)), 'Revo Capital Fund III C.V.', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Jungle Ventures V L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:de09b68dbc690c9849d9564637e1e1ed', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Jungle Partners V L.P.', (select name from public.companies where id = f.gp_company_id)), 'Jungle Ventures V L.P.', 40000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Creador VI L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:753cbc6bdfd231bbe37812c2bbca736e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Creador Management VI Ltd  (Mauritius)/Mauritius', (select name from public.companies where id = f.gp_company_id)), 'Creador VI L.P.', 50000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Nature Based Carbon Fund', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:2dedc0158eac9e24747a5de4fb4e5f7a', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('NBCF General Partner S.à.r.l', (select name from public.companies where id = f.gp_company_id)), 'Nature Based Carbon Fund', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Rymel Ingenieria Electrica S.A.S', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:509a693d9e443d0bfafa5a44ffc8c08a', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('ACON Sunrise Investors I', (select name from public.companies where id = f.gp_company_id)), 'Rymel Ingenieria Electrica S.A.S', 12400000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Actis Asia Climate Transition SCSp', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:314e036aba07882e187d6b0be9dfaa11', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Actis EU GP S.à r.l.', (select name from public.companies where id = f.gp_company_id)), 'Actis Asia Climate Transition SCSp', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('DIC Latin American Fund IV, L.P./Canada', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:7963e795e488bde0957f14dd088e91f6', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('DIC Latin American Fund IV GP, LLC., Delaware', (select name from public.companies where id = f.gp_company_id)), 'DIC Latin American Fund IV, L.P./Canada', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wavemaker Pacific 5, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:8e2f56f0bebfc19b2867ae5ea9851acd', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Wavemaker Global Partners 5 Ltd / Cayman Islands', (select name from public.companies where id = f.gp_company_id)), 'Wavemaker Pacific 5, L.P.', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Latin American Green Bond Fund S.A. SICAV-SIF', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:6467bd0f0279f5b07a841bc7d4551e02', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Finance in Motion GmbH', (select name from public.companies where id = f.gp_company_id)), 'Latin American Green Bond Fund S.A. SICAV-SIF', 25000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('SPE PEF III, L.P. (2)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:321ed1bb0ff98a514596cc330fba751c', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('SPE PEF III GP Ltd / Mauritius', (select name from public.companies where id = f.gp_company_id)), 'SPE PEF III, L.P. (2)', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('African Infrastructure Investment Fund 4', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:e393bfea34e47b0a5cd8f19246175a3e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('African Infrastructure Investment Managers', (select name from public.companies where id = f.gp_company_id)), 'African Infrastructure Investment Fund 4', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('QUADRIA Capital Fund III L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:e3ecd02d78ff2ea2c81849c3c03e0da6', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Quadria Capital Fund III GP', (select name from public.companies where id = f.gp_company_id)), 'QUADRIA Capital Fund III L.P.', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Adenia Capital (V) LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:0f48b2e97013a837d6e33571c3af3d46', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Afindo GP V Ltd', (select name from public.companies where id = f.gp_company_id)), 'Adenia Capital (V) LP', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ashmore Andean Fund III, L.P. / Canada', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:2ddf096cb984a32b5c9ef57c9035f2be', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Ashmore Management Company Colombia S.A.S. / Colombia', (select name from public.companies where id = f.gp_company_id)), 'Ashmore Andean Fund III, L.P. / Canada', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Digital East Fund III, SCSp', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:683de6f1ca7a8ed547d5122ad90b8c9a', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('DEF Digital East Management Sarl', (select name from public.companies where id = f.gp_company_id)), 'Digital East Fund III, SCSp', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vinci Capital Partners IV A, LP / Canada', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:2d6b0906dbe585941d5fdfcc35d06e21', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Vinci Capital Partners IV GP LLC / Delaware', (select name from public.companies where id = f.gp_company_id)), 'Vinci Capital Partners IV A, LP / Canada', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apis Growth Fund III SCSp', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:b3a200870a79e22d499c36ba4bce2a45', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('APIS GP III S.À.R.L', (select name from public.companies where id = f.gp_company_id)), 'Apis Growth Fund III SCSp', 40000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('A.P. Møller Capital – Emerging Markets Infrastructure Fund II', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:829beb8030fe862bf5e9a0962c15d51e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('A.P. Møller Capital  - Emerging Markets Infrastructure Fund II GP ApS / Denmark', (select name from public.companies where id = f.gp_company_id)), 'A.P. Møller Capital – Emerging Markets Infrastructure Fund II', 50000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('L Catterton Latin America IV-B, L.P', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:45cd89b55216ebe5d200070af0680857', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('LCLA Managing Partner IV, L.P.', (select name from public.companies where id = f.gp_company_id)), 'L Catterton Latin America IV-B, L.P', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Openspace Ventures IV, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:e752fe165ea16d9cc8be78361bb6a459', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('OSV IV GP Limited / Cayman Islands', (select name from public.companies where id = f.gp_company_id)), 'Openspace Ventures IV, L.P.', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Metier Capital Growth Fund III', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:5657fd961f3913d2b13c828b0e7d0f42', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Metier Capital Growth International Fund GP / Mauritius', (select name from public.companies where id = f.gp_company_id)), 'Metier Capital Growth Fund III', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LC Healthcare SEA Fund I, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:1bcec4e9b7c46a04c4da64c5b8f51da1', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('LC Healthcare SEA Fund I GP Limited / Cayman Islands', (select name from public.companies where id = f.gp_company_id)), 'LC Healthcare SEA Fund I, L.P.', 5000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TIDE Africa II LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:42f0d5dc22feea8c7af45164a9a60d63', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('TIDE Africa II GP LP', (select name from public.companies where id = f.gp_company_id)), 'TIDE Africa II LP', 5000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Growtheum Capital Partners SEA Fund 1 LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:bac89b5fcf2fba7a7c614469ecb0dfcc', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Growtheum Capital Partners SEA Fund 1 GP Pte. Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Growtheum Capital Partners SEA Fund 1 LP', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('QUADRIA Capital Fund III L.P. (2)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:aafcff7e0b89cbba17f9e230134bb5a1', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Quadria Capital Fund III GP', (select name from public.companies where id = f.gp_company_id)), 'QUADRIA Capital Fund III L.P. (2)', 35000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Avataar Venture Partners II', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:f6e4378f98acb41ddc707fba67e62544', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Avataar Venture Capital Management Ltd / Mauritius', (select name from public.companies where id = f.gp_company_id)), 'Avataar Venture Partners II', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NXTP III, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:6e071086e09c9c254e297b5f95ebdd18', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('NXTP Fund III GP', (select name from public.companies where id = f.gp_company_id)), 'NXTP III, L.P.', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Alterrra Africa Accelerator Fund LP, Mauritus', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:40d4a735979ace7ab1d156ca08c35c92', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Alterra Africa Accelerator G.P.', (select name from public.companies where id = f.gp_company_id)), 'Alterrra Africa Accelerator Fund LP, Mauritus', 17000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vertex Ventures (SG) SEA V LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:53022b789f7580e2b8754140bed0d1c2', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Vertex Ventures (SG) SEA GP III Pte Ltd', (select name from public.companies where id = f.gp_company_id)), 'Vertex Ventures (SG) SEA V LP', 18000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Exacta Asia Investment III LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:917b3e8580f871f7473709014b19ba28', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Exacta Capital Partners III', (select name from public.companies where id = f.gp_company_id)), 'Exacta Asia Investment III LP', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Alcazar Energy Partners II', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:35253f697779ecce5fe30cc3cfb831dc', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Alcazar Energy Partners II GP Sa.r.l.', (select name from public.companies where id = f.gp_company_id)), 'Alcazar Energy Partners II', 29500000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Horizon Capital Growth Fund IV (HCGF IV)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:64d010befc8fc875dde59b74ddf4f67e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Horizon Capital', (select name from public.companies where id = f.gp_company_id)), 'Horizon Capital Growth Fund IV (HCGF IV)', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Adenia Capital V', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:3af0595f2fcaf055c3f884437631d5ee', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Adenia Capital', (select name from public.companies where id = f.gp_company_id)), 'Adenia Capital V', 20000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Riverwood Capital Partners Latam II L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:f2fe86f0400d15ec32f08381acbb2442', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Double GP Structure: Riverwood Capital Latam II L.P. and their GP Riverwood Capital Latam GP II Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Riverwood Capital Partners Latam II L.P.', 25000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('OrbiMed Asia Partners V, L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:3cff19f282a44c4b2a6aa790db85b47a', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Orbimed Asia GP V, L.P.', (select name from public.companies where id = f.gp_company_id)), 'OrbiMed Asia Partners V, L.P.', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Asia Partners II L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:6e6aed3752bb5aa5b2623a44335f793a', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Asia Partners II Ltd.', (select name from public.companies where id = f.gp_company_id)), 'Asia Partners II L.P.', 30000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('VI (Vietnam Investments) Fund IV L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:a40612891ce70095070430c06d522341', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('VI / Vietnam Investments Management LLC', (select name from public.companies where id = f.gp_company_id)), 'VI (Vietnam Investments) Fund IV L.P.', 15000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASEAN Frontier Markets Fund, L.P. (“AFMF”),', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-usd:b3b692de7806465e7a8fbfc52f2d4ebb', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('AFMF GP Pte.Ltd.', (select name from public.companies where id = f.gp_company_id)), 'ASEAN Frontier Markets Fund, L.P. (“AFMF”),', 10000000, 'USD', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (USD) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - DEG investment list (deginvest.csv) - equity fund commitments (USD)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://deginvest-investments.de/deginvest.csv') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', 'doc', 'deg-usd', 'rows', 46));
end $$;
