-- deg-eur: DEG - Deutsche Investitions- und Entwicklungsgesellschaft -- DEG investment list (deginvest.csv) - equity fund commitments (EUR) (as of None, EUR). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('DEG - Deutsche Investitions- und Entwicklungsgesellschaft', 'Development Finance Institution', 'Germany', 'https://www.deginvest.de');
  select * into f from ingest.fund_for('Adenia Entrepreneurial Fund (I) LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:99b05cfb025cc42e5fafc81aa99d0fc6', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('AEF GP (I) Ltd', (select name from public.companies where id = f.gp_company_id)), 'Adenia Entrepreneurial Fund (I) LP', 15000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('E2VC Fund III C.V.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:3a8cf45a77359cf508388d3cfa506ed3', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('E2VC III GP B. V.', (select name from public.companies where id = f.gp_company_id)), 'E2VC Fund III C.V.', 10000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Endiya Partners Fund III', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:dd01a03b87c61fd26544ecc0ff25c06f', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Endiya Alamban Advisory Services LLP', (select name from public.companies where id = f.gp_company_id)), 'Endiya Partners Fund III', 10800000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Somerset Indus Healthcare India Fund III', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:df88a965304cf4da631d96aed5d9522e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Somerset Healthcare Investment Advisors III Pvt Ltd', (select name from public.companies where id = f.gp_company_id)), 'Somerset Indus Healthcare India Fund III', 15000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Mediterra Capital Partners III, LP', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:abcfc8bfb619c09fa797e390a4f3b87f', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Mediterra Capital Partners GP III, LP', (select name from public.companies where id = f.gp_company_id)), 'Mediterra Capital Partners III, LP', 20000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Amethis Fund III S.C.A., SICAV-RAIF', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:7f23427f6c7791eb9d1c60b478be5fe3', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Amethis Fund III Management S.à.r.l.', (select name from public.companies where id = f.gp_company_id)), 'Amethis Fund III S.C.A., SICAV-RAIF', 13000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Mediterrania Capital IV Mid-Cap', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:f097c4f80e2e9cbb872fc483b088d23b', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Mediterrania Capital Partners Ltd', (select name from public.companies where id = f.gp_company_id)), 'Mediterrania Capital IV Mid-Cap', 15000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Amicus Capital Partners India Fund II', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:12b1b7786a15f87189045ef99bf90cf0', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Amicus India Capital Partners LLP', (select name from public.companies where id = f.gp_company_id)), 'Amicus Capital Partners India Fund II', 14686205, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ascent Growth Trust V', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:036d3ebb2acc8e2a08e6bcfc29f08e4e', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Ascent Capital Advisors India Private Limited', (select name from public.companies where id = f.gp_company_id)), 'Ascent Growth Trust V', 18000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Phi Capital Growth Fund 1.6', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:06ee7a110626ee4b392fed0657045fb8', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Phi Capital Management LLP (India)', (select name from public.companies where id = f.gp_company_id)), 'Phi Capital Growth Fund 1.6', 17000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Mediterrania Capital IV Mid-Cap (2)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:082281f2c3cb89ec6fac0dd567ceb85c', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('MCP (Mauritius) GP IV Ltd', (select name from public.companies where id = f.gp_company_id)), 'Mediterrania Capital IV Mid-Cap (2)', 10000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partech Africa II S.L.P.', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:deg-deutsche-investitions-und-entwicklungsgesellschaft:deg-eur:f58a31e39b6d7059d1b80260c31f5922', v_lp, f.gp_company_id, f.fund_id, 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', coalesce('Partech Partners SAS GP: Partech Africa GP', (select name from public.companies where id = f.gp_company_id)), 'Partech Africa II S.L.P.', 15000000, 'EUR', null, null, null, null, null, null, null, null, 'DEG investment list (deginvest.csv) - equity fund commitments (EUR) (p. 1)', 'lp_disclosure', 'https://deginvest-investments.de/deginvest.csv', null)
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - DEG investment list (deginvest.csv) - equity fund commitments (EUR)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://deginvest-investments.de/deginvest.csv') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'DEG - Deutsche Investitions- und Entwicklungsgesellschaft', 'doc', 'deg-eur', 'rows', 12));
end $$;
