-- lacers-real-estate: Los Angeles City Employees' Retirement System -- Real Estate Portfolio Performance Review — Fourth Quarter 2025 (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Los Angeles City Employees'' Retirement System', 'Public Pension Fund', 'United States', 'https://www.lacers.org');
  select * into f from ingest.fund_for('Berkshire Multifamily Income Realty Fund', 2015, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:79f18926e319765f86cb2615bc6d9e41', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Berkshire Multifamily Income Realty Fund', 20000000, 'USD', 2015, 'real_estate', 20000000, 18719963, 11917913, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Carlyle Property Investors', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:b013b067949c51d85520d4c0ddb9576e', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Carlyle Property Investors', 85000000, 'USD', 2025, 'real_estate', null, null, 0, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CIM VI (Urban REIT), LLC', 2012, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:7308c59681727c58ee154ce4ea07363a', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CIM VI (Urban REIT), LLC', 25000000, 'USD', 2012, 'real_estate', 25000000, 22206796, 4339668, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Cortland Partners Growth and Income Fund', 2022, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:620e40f407818c7a32b38c3ea72f3c0f', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Cortland Partners Growth and Income Fund', 100000000, 'USD', 2022, 'real_estate', 107591222, 7932643, 67614208, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('INVESCO Core Real Estate', 2004, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:5f72448eabf3e0fefcb16d14fa9ad66a', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'INVESCO Core Real Estate', 63867553, 'USD', 2004, 'real_estate', 141442166, 100500254, 165237155, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Jamestown Premier Property Fund', 2015, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:01bd098597446a0bdf5b5afd72b8cbeb', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Jamestown Premier Property Fund', 50000000, 'USD', 2015, 'real_estate', 51992904, 28157825, 13640639, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('JP Morgan Strategic Property Fund', 2005, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:0c56f47b7f8b89c71902ea61babcafad', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'JP Morgan Strategic Property Fund', 30000000, 'USD', 2005, 'real_estate', 30421882, 3397077, 75774579, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Kayne Anderson Core Real Estate Fund', 2019, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:042a8f3f3a2b18ee02689947d5367a32', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Kayne Anderson Core Real Estate Fund', 85000000, 'USD', 2019, 'real_estate', 97453108, 17022240, 100297479, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lion Industrial Trust - 2007', 2016, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:ab44986abed8009ba57f40ca5941d3ab', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lion Industrial Trust - 2007', 75000000, 'USD', 2016, 'real_estate', 94567369, 28862190, 169999533, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Prime Property Fund', 2015, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:db4accd84e316a2da82e3be81e463750', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Prime Property Fund', 50000000, 'USD', 2015, 'real_estate', 59144287, 23244948, 65741092, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Principal U.S. Property Account', 2015, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:4fdb59b4fc2358a77a60eb62d850b0ba', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Principal U.S. Property Account', 50000000, 'USD', 2015, 'real_estate', 50000000, null, 79618344, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Realty Income U.S. Core Plus Fund', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:b5dd2c4b76965981c2eb9b3d9b08ca7a', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Realty Income U.S. Core Plus Fund', 65000000, 'USD', 2025, 'real_estate', 50038381, 810847, 59299721, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Hancock Timberland XI', 2012, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:dd5bd3f2adc2730f9da51d3a76ec9ce7', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Hancock Timberland XI', 20000000, 'USD', 2012, 'real_estate', 18601851, 8496476, 18988448, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Almanac Realty Securities VI', 2012, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:caa226cbd96914e644970a60593b3c7b', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Almanac Realty Securities VI', 25000000, 'USD', 2012, 'real_estate', 15475571, 17184560, 1995471, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Asana Partners Fund I', 2017, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:f8bb03fc22ed23a94a3194f974573f1b', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Asana Partners Fund I', 20000000, 'USD', 2017, 'real_estate', 18301629, 16101663, 16726467, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Asana Partners Fund II', 2019, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:76d976b41388bdba029a392f0268f610', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Asana Partners Fund II', 35000000, 'USD', 2019, 'real_estate', 32340950, null, 27296705, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('DRA Growth and Income Fund VIII', 2014, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:e40970ed2672acbb7ec45be933da5837', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'DRA Growth and Income Fund VIII', 25000000, 'USD', 2014, 'real_estate', 29576071, 32683275, 1444175, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT Exeter European Logistics Value Fund V', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:dc5d0ffe60abcfaf8707fe590b59cd4d', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT Exeter European Logistics Value Fund V', 50974865, 'USD', 2025, 'real_estate', null, null, null, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT Exeter Industrial Value Fund VI', 2023, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:3ae63ee9c651ca1a2a274dd54644640d', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT Exeter Industrial Value Fund VI', 75000000, 'USD', 2023, 'real_estate', 45000000, null, 47811591, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Gerrity Retail Fund 2', 2015, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:94c7087026e7cb8227373443f85ec356', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Gerrity Retail Fund 2', 20000000, 'USD', 2015, 'real_estate', 20077854, 11392168, 11855059, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('GLP Capital Partners IV', 2021, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:218a44cc0fd884ddbd4e3804b6e0cd67', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'GLP Capital Partners IV', 40000000, 'USD', 2021, 'real_estate', 35999258, 17372083, 27071277, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Heitman Asia-Pacific Property Investors', 2018, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:36ff4d315bfe4b34203734224a128445', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Heitman Asia-Pacific Property Investors', 25000000, 'USD', 2018, 'real_estate', 24444543, 10703778, 9789127, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LBA Logistics Value Fund IX', 2022, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:f9e6778a23ef394b9117738d991fb91e', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LBA Logistics Value Fund IX', 50000000, 'USD', 2022, 'real_estate', 43333333, 1641026, 40779861, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LBA Logistics Value Fund VII', 2020, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:c000321902c8255d14010c7c1bae6396', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LBA Logistics Value Fund VII', 35000000, 'USD', 2020, 'real_estate', 31668237, 10011781, 37143735, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LBA Logistics Value Fund X', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:3cd7d8b726c7cfb237784b334efe8a56', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LBA Logistics Value Fund X', 50000000, 'USD', 2025, 'real_estate', 4529873, null, 4036694, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NB Partners Fund IV LP', 2023, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:f5febd7b77571fa473dab874c27d8231', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NB Partners Fund IV LP', 40000000, 'USD', 2023, 'real_estate', 22839950, 589849, 22901687, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NREP Nordic Strategies Fund IV', 2019, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:7bf4e6188a2735548989ef25ddcfee23', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NREP Nordic Strategies Fund IV', 35437928, 'USD', 2019, 'real_estate', 26941472, -2130639, 28267958, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Waterton Residential Property Venture XIV, L.P.', 2020, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:3c0801b4574f4470aaa3a4c70ae5a385', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Waterton Residential Property Venture XIV, L.P.', 50000000, 'USD', 2020, 'real_estate', 50000000, 32432, 43092147, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Waterton Residential Property Venture XV', 2023, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:337ce4a6534409b0c2597cbaddbcf294', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Waterton Residential Property Venture XV', 50000000, 'USD', 2023, 'real_estate', 21916713, 357524, 23698572, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 18)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo CPI Europe I', 2006, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:95cab131b46af6297f9701d9c2ae06c5', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo CPI Europe I', 25533001, 'USD', 2006, 'real_estate', 22385238, 11762746, 232587, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bristol Value II, L.P.', 2012, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:83ff2494fb5ed0163fd5d85db09988f3', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bristol Value II, L.P.', 20000000, 'USD', 2012, 'real_estate', 25491739, 33464707, 730192, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Broadview Real Estate Partners Fund, L.P.', 2019, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:3366735066940ff8651cc583ff7f5996', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Broadview Real Estate Partners Fund, L.P.', 20000000, 'USD', 2019, 'real_estate', 16178066, 6708639, 15870551, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Brookfield Strategic Real Estate Partners IV', 2022, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:b38ed67dd3a0bd87e283ede81e13b420', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Brookfield Strategic Real Estate Partners IV', 50000000, 'USD', 2022, 'real_estate', 44148050, 6793480, 40515635, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('California Smart Growth Fund IV', 2006, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:cfcc2dac5de18cdf93167520e63d8617', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'California Smart Growth Fund IV', 30000000, 'USD', 2006, 'real_estate', 31522663, 38422919, null, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Cerberus Institutional Real Estate Partners V', 2020, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:74a5d129198eeae72ed4315e70a2ff91', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Cerberus Institutional Real Estate Partners V', 40000000, 'USD', 2020, 'real_estate', 32090605, 1781922, 44720048, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CIM Real Estate Fund III', 2007, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:ade9d9fa7daf92150cf27232536dcd51', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CIM Real Estate Fund III', 15000000, 'USD', 2007, 'real_estate', 16674075, 21753159, 1210322, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Latin America Investors III', 2008, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:edf01dc6552dbd57862e871b9c238caa', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Latin America Investors III', 20000000, 'USD', 2008, 'real_estate', 20686689, 3886924, -3584713, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lone Star Real Estate Fund II', 2011, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:66cad7c927110e6fa39305131ea29f77', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lone Star Real Estate Fund II', 15000000, 'USD', 2011, 'real_estate', 13291475, 20603988, null, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Oaktree Real Estate Opportunities Fund IX L.P.', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:2cb43fae0462f3d3daf31ea9cc589022', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Oaktree Real Estate Opportunities Fund IX L.P.', 50000000, 'USD', 2025, 'real_estate', 10000000, 2000000, 8699551, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Oaktree Real Estate Opportunities Fund VIII L.P.', 2021, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:5f4858a0c938a9b6b8a8845d514f7558', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Oaktree Real Estate Opportunities Fund VIII L.P.', 50000000, 'USD', 2021, 'real_estate', 40174118, 8301039, 31407091, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Principal Data Center Growth & Income Fund, LP', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:b846b39f43d26fb8c2f406b5b2d85263', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Principal Data Center Growth & Income Fund, LP', 35000000, 'USD', 2025, 'real_estate', 20738054, 323925, 22159394, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('RECP Fund IV, L.P.', 2008, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:7c208c7c803276c2c41c91c2c7613da6', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'RECP Fund IV, L.P.', 40000000, 'USD', 2008, 'real_estate', 53279662, 41256108, 13134205, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Stockbridge Real Estate Fund II', 2006, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:fb87fc51e5e632be7586ba457d6cc848', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Stockbridge Real Estate Fund II', 30000000, 'USD', 2006, 'real_estate', 30000000, 14865602, null, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TPG Real Estate Partners IV', 2022, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:e20bf6b7300939de131b9efb2033b3dc', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TPG Real Estate Partners IV', 50000000, 'USD', 2022, 'real_estate', 25527907, 266119, 27456802, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Walton Street Real Estate Fund V', 2006, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:5afa1405437aba4fe107e201afdb2322', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Walton Street Real Estate Fund V', 25000000, 'USD', 2006, 'real_estate', 25000001, 17350398, 298743, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Walton Street Real Estate Fund VI', 2009, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:9fb601894f41524a8bbcb39c1edfb9a9', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Walton Street Real Estate Fund VI', 25000000, 'USD', 2009, 'real_estate', 22161966, 34557753, 1419268, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('WCP NewCold III, LP (Secondary)', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:3402729d381c134bb9240c362e322ceb', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'WCP NewCold III, LP (Secondary)', 35000000, 'USD', 2025, 'real_estate', 25137250, 2597213, 25356793, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wolff Credit Partners III, LP', 2022, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:7d7fe623b4b71e524fee77e55667920b', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Wolff Credit Partners III, LP', 35000000, 'USD', 2022, 'real_estate', 31843137, 9201198, 27979351, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Wolff Credit Partners IV', 2025, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:00d8fb85f07f208a6230be8fcac31355', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Wolff Credit Partners IV', 50000000, 'USD', 2025, 'real_estate', null, null, 0, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private Real Estate Portfolio Only (ex. Timber)', 1989, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:los-angeles-city-employees-retirement-system:lacers-real-estate:85645ffe833ff98f91637af535e35ab0', v_lp, f.gp_company_id, f.fund_id, 'Los Angeles City Employees'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Private Real Estate Portfolio Only (ex. Timber)', 1985813347, 'USD', 1989, 'real_estate', 1656427465, 642692122, 1414879591, null, null, '2025-12-31', 'Real Estate Portfolio Performance Review — Fourth Quarter 2025 (p. 19)', 'lp_disclosure', 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Real Estate Portfolio Performance Review — Fourth Quarter 2025'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.lacers.org/sites/main/files/file-attachments/lacers_q4_2025_ppr.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Los Angeles City Employees'' Retirement System', 'doc', 'lacers-real-estate', 'rows', 50));
end $$;
