-- lpfa: London Pensions Fund Authority -- LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles) (as of 2025-03-31, GBP). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('London Pensions Fund Authority', 'LGPS Fund', 'United Kingdom', 'https://www.lpfa.org.uk');
  select * into f from ingest.fund_for('LPPI Real Estate', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:london-pensions-fund-authority:lpfa:747b79a3925731dfe974a591df84b2e1', v_lp, f.gp_company_id, f.fund_id, 'London Pensions Fund Authority', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LPPI Real Estate', null, 'GBP', null, 'real_estate', null, null, 660249000, null, null, '2025-03-31', 'LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles) (p. 56)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2025/11/LPFA2425_final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LPPI PE Investments (No.1) LP', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:london-pensions-fund-authority:lpfa:9283222b8e252e9ab79f8095169ce95e', v_lp, f.gp_company_id, f.fund_id, 'London Pensions Fund Authority', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LPPI PE Investments (No.1) LP', null, 'GBP', null, 'private_equity', null, null, 461444000, null, null, '2025-03-31', 'LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles) (p. 56)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2025/11/LPFA2425_final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LPPI Credit', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:london-pensions-fund-authority:lpfa:2e11bbb0f3b8d280f0edc58cdc4d68a3', v_lp, f.gp_company_id, f.fund_id, 'London Pensions Fund Authority', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LPPI Credit', null, 'GBP', null, null, null, null, 1173187000, null, null, '2025-03-31', 'LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles) (p. 56)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2025/11/LPFA2425_final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LPPI Infrastructure', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:london-pensions-fund-authority:lpfa:aeebfbd34b51f55099691cc75347cfbf', v_lp, f.gp_company_id, f.fund_id, 'London Pensions Fund Authority', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LPPI Infrastructure', null, 'GBP', null, 'infrastructure', null, null, 930469000, null, null, '2025-03-31', 'LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles) (p. 56)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2025/11/LPFA2425_final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - LPFA Pension Fund Annual Report 2024-25 — investments representing more than 5% of investment assets (LPPI pooled vehicles)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://lgpsboard.org/wp-content/uploads/2025/11/LPFA2425_final.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'London Pensions Fund Authority', 'doc', 'lpfa', 'rows', 4));
end $$;
