-- merseyside: Merseyside Pension Fund -- Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (as of 2025-03-31, GBP). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Merseyside Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://mpfmembers.org.uk');
  select * into f from ingest.fund_for('GLIL', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:merseyside-pension-fund:merseyside:a860a9da92f9f35ca283cadfc50a22e9', v_lp, f.gp_company_id, f.fund_id, 'Merseyside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'GLIL', 487500000, 'GBP', null, 'infrastructure', null, null, null, null, null, '2025-03-31', 'Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (p. 71)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NextPower UK 1 GP Limited', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:merseyside-pension-fund:merseyside:b198a4d59cc358d702abcdb0cfd0e8ae', v_lp, f.gp_company_id, f.fund_id, 'Merseyside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NextPower UK 1 GP Limited', 50000000, 'GBP', null, 'infrastructure', null, null, null, null, null, '2025-03-31', 'Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (p. 71)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('MEF4 Monet Co-Invest SLP', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:merseyside-pension-fund:merseyside:0fdafffdbae8f1af1c7a4fc6810667f2', v_lp, f.gp_company_id, f.fund_id, 'Merseyside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'MEF4 Monet Co-Invest SLP', 46410000, 'GBP', null, 'infrastructure', null, null, null, null, null, '2025-03-31', 'Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (p. 71)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('InfraBridge Global Infrastructure Fund I', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:merseyside-pension-fund:merseyside:7f6c927a4459270e9b3dbf5b5bba8a2a', v_lp, f.gp_company_id, f.fund_id, 'Merseyside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'InfraBridge Global Infrastructure Fund I', 39140000, 'GBP', null, 'infrastructure', null, null, null, null, null, '2025-03-31', 'Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (p. 71)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics Clean Energy UK', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:merseyside-pension-fund:merseyside:8e8ada9541161ce4fca039a165a250c1', v_lp, f.gp_company_id, f.fund_id, 'Merseyside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics Clean Energy UK', 30000000, 'GBP', null, 'infrastructure', null, null, null, null, null, '2025-03-31', 'Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis (p. 71)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Merseyside Pension Fund Report & Accounts 2024/25 — Table 5, Top 5 Largest Infrastructure Holdings on Committed Capital Basis'), disclosure_source_url = coalesce(disclosure_source_url, 'https://lgpsboard.org/wp-content/uploads/2026/03/Merseyside-2425-final.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Merseyside Pension Fund', 'doc', 'merseyside', 'rows', 5));
end $$;
