-- nyc-trs-private-equity-01: Teachers' Retirement System of the City of New York -- NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := '61b12767-046a-49ab-82f1-c2c60917a2d6'::uuid;
  select * into f from ingest.fund_for('FdG Capital Partners II, L.P.', 2004, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:2189a2d1e358bc2d8e625b08356fb16b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FdG Capital Partners II, L.P.', 35000000.0, 'USD', 2004, 'private_equity', 37720808.0, 44959148.0, 770176.0, 3.63, 1.21, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('USPF II Institutional Fund, L.P.', 2005, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:4982bf985ce2b66b7bea95d69d7cde31', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'USPF II Institutional Fund, L.P.', 35000000.0, 'USD', 2005, 'private_equity', 46164567.0, 55381287.0, 230445.0, 3.2, 1.2, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund VI, L.P.', 2006, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:9529f7cc090cff5fb991b8a364d4b2a4', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund VI, L.P.', 35000000.0, 'USD', 2006, 'private_equity', 45048207.0, 67409336.0, 595759.0, 8.61, 1.51, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FTVentures III, L.P.', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:05379f733a8a258f9bd6363a84afaa86', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FTVentures III, L.P.', 14081947.0, 'USD', 2007, 'private_equity', 15022056.0, 25170138.0, 2915289.0, 10.43, 1.87, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('New Mountain Partners III, L.P.', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:106a3d8c3877ba27dda830bbca4977c6', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'New Mountain Partners III, L.P.', 35000000.0, 'USD', 2007, 'private_equity', 37563707.0, 88424718.0, 1365713.0, 14.51, 2.39, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Quaker BioVentures II, L.P.', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:9f3a25d57a98f4cc0a65f73235a58116', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Quaker BioVentures II, L.P.', 15000000.0, 'USD', 2007, 'private_equity', 14977775.0, 16700135.0, 31779.0, 2.4, 1.12, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vista Equity Partners Fund III, L.P.', 2007, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:9207279386a9e12de699437f1662b898', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Vista Equity Partners Fund III, L.P.', 25000000.0, 'USD', 2007, 'private_equity', 26961980.0, 66868413.0, 70174.0, 26.8, 2.48, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund III, L.P.', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:8a0137e3318ecef895aee5c42032da36', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund III, L.P.', 60000000.0, 'USD', 2008, 'private_equity', 71462853.0, 155339754.0, 245528.0, 20.83, 2.18, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridgepoint Europe IV, L.P.', 2008, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:16e98e2d663bf861023bcbc69a8a9046', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridgepoint Europe IV, L.P.', 25935908.0, 'USD', 2008, 'private_equity', 24946822.0, 36492389.0, 2109790.0, 9.13, 1.55, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vista Equity Partners Fund IV, L.P.', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:b8e2f3764f72678d02be5b7c5307e5ef', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Vista Equity Partners Fund IV, L.P.', 100000000.0, 'USD', 2011, 'private_equity', 101639756.0, 139380002.0, 64817427.0, 13.38, 2.01, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Green Equity Investors VI, L.P.', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:f2624aab21fa47e34652aa4570d7e865', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Green Equity Investors VI, L.P.', 100000000.0, 'USD', 2012, 'private_equity', 152285239.0, 232024998.0, 43400014.0, 12.8, 1.81, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund IV, L.P.', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:2f57df018829df7a33047934f04954d5', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund IV, L.P.', 105000000.0, 'USD', 2012, 'private_equity', 117657928.0, 198577097.0, 13928968.0, 13.88, 1.81, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Capital Partners III, L.P.', 2011, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:607dbe855ac0fb3bd7133fa7fb11e15d', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Capital Partners III, L.P.', 115000000.0, 'USD', 2011, 'private_equity', 111696970.0, 225983395.0, 7659796.0, 35.46, 2.09, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Private Equity XI, L.P.', 2012, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:857d58fb7cd7f368b4224549d7366955', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Private Equity XI, L.P.', 175000000.0, 'USD', 2012, 'private_equity', 176336274.0, 256177020.0, 44091763.0, 10.68, 1.7, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund VIII, L.P.', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:4dc3a2888f9e3cca42c112d60bba3cc6', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund VIII, L.P.', 200000000.0, 'USD', 2013, 'private_equity', 201529956.0, 245526967.0, 42641325.0, 8.45, 1.43, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners VI, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:29b894f1d666f48ee0df353caef4d5af', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners VI, L.P.', 176180689.0, 'USD', 2014, 'private_equity', 202142209.0, 310212530.0, 102501525.0, 15.18, 2.04, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VI, L.P.', 2013, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:02e3195dafb13a41cdb9db48ab1e62f5', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VI, L.P.', 112000000.0, 'USD', 2013, 'private_equity', 95045990.0, 128460757.0, 5306810.0, 11.12, 1.41, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VI NYC Co-Invest, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:6e528b319c61c9bd03c564d1c29b2b73', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VI NYC Co-Invest, L.P.', 38000000.0, 'USD', 2014, 'private_equity', 32361220.0, 46497446.0, 39855.0, 10.88, 1.44, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centerbridge Capital Partners III, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:f4fd0e99e3bf89bc9d4c56fd2b98d038', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centerbridge Capital Partners III, L.P.', 33500000.0, 'USD', 2015, 'private_equity', 46768637.0, 54467137.0, 17016828.0, 13.13, 1.53, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners VIII, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:d7e68ba4e9f5797e44b17dd3bdd3e3ae', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners VIII, L.P.', 150000000.0, 'USD', 2014, 'private_equity', 140817280.0, 179480716.0, 51843263.0, 13.73, 1.64, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vista Equity Partners Fund V, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:910a2e3d2dd5044b415a0933125b3aac', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Vista Equity Partners Fund V, L.P.', 125000000.0, 'USD', 2014, 'private_equity', 159324358.0, 256511832.0, 73136254.0, 15.73, 2.07, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VII, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:9716373bce31320bb5d83a73b25f4d25', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VII, L.P.', 134000000.0, 'USD', 2015, 'private_equity', 101804343.0, 123855070.0, 35427890.0, 13.81, 1.56, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VII B NYC Co-Invest, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:193a68ebed08f99e176c9fc0541fe217', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VII B NYC Co-Invest, L.P.', 67000000.0, 'USD', 2015, 'private_equity', 43325429.0, 63808463.0, 20717762.0, 18.41, 1.95, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridgepoint Europe V, L.P.', 2014, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:6fd8e773b14e0002b172ae287cb84050', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridgepoint Europe V, L.P.', 88550846.0, 'USD', 2014, 'private_equity', 81011404.0, 118005737.0, 41607264.0, 16.72, 1.97, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Welsh, Carson, Anderson & Stowe XII, L.P.', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:dc695d6903ba9d6bd63b0a881c809468', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Welsh, Carson, Anderson & Stowe XII, L.P.', 110500000.0, 'USD', 2015, 'private_equity', 104678112.0, 214041759.0, 52386339.0, 24.46, 2.55, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridgepoint Europe V Co-Invest', 2015, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:273a9147de4ad40efaa6fce84def3c8e', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridgepoint Europe V Co-Invest', 25405561.0, 'USD', 2015, 'private_equity', 23183477.0, 49845637.0, 12880515.0, 24.9, 2.71, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Vista Equity Partners Fund VI, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:475776234f8ce125606d6813a871653f', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Vista Equity Partners Fund VI, L.P.', 223000000.0, 'USD', 2016, 'private_equity', 287297922.0, 368403102.0, 201390587.0, 15.38, 1.98, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apax IX USD, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:37bb529ab7b335f9d58db3d2d4d323e9', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apax IX USD, L.P.', 178000000.0, 'USD', 2016, 'private_equity', 194301569.0, 285032253.0, 81218014.0, 17.23, 1.88, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Capital Partners IV, L.P.', 2016, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:df4e921be8c1249f59d907130a91d531', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Capital Partners IV, L.P.', 156000000.0, 'USD', 2016, 'private_equity', 164023308.0, 203426785.0, 113158755.0, 18.1, 1.93, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund V, L.P.', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:c3ab099f23161889ed8f62ebc51fc2c6', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund V, L.P.', 134000000.0, 'USD', 2017, 'private_equity', 150124352.0, 84996637.0, 100489394.0, 4.6, 1.24, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Green Equity Investors VII, L.P.', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:1b94483fd6a8e9a54fecf5c4569a02a1', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Green Equity Investors VII, L.P.', 134000000.0, 'USD', 2017, 'private_equity', 148257245.0, 209049437.0, 89953602.0, 18.09, 2.02, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('KKR Americas Fund XII, L.P.', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:2f6e745309b7b2688b124b7a9007699b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'KKR Americas Fund XII, L.P.', 223000000.0, 'USD', 2017, 'private_equity', 219494876.0, 269442572.0, 289564435.0, 22.68, 2.55, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners VII, L.P.', 2017, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:5bf22838aa8f169d2fc68aa59f87977a', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners VII, L.P.', 155034847.0, 'USD', 2017, 'private_equity', 163623425.0, 186362036.0, 166686924.0, 20.01, 2.16, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apollo Investment Fund IX, L.P.', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:282860bb4084c7e0be53aa60268cb0de', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apollo Investment Fund IX, L.P.', 256000000.0, 'USD', 2018, 'private_equity', 264772201.0, 163877170.0, 236076166.0, 14.57, 1.51, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridgepoint Europe VI, L.P.', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:49efb29b2147802b49d53b501ca10400', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridgepoint Europe VI, L.P.', 96250633.0, 'USD', 2018, 'private_equity', 92099207.0, 75579644.0, 80815506.0, 13.94, 1.7, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT VIII SCSP', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:78b6fb1f1c3987a90ff493f3fd50a72d', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT VIII SCSP', 87449717.0, 'USD', 2018, 'private_equity', 102848358.0, 124102738.0, 67556479.0, 19.96, 1.86, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridgepoint Europe VI Co-Invest', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:6f292a48c674203d74337663a48bd3b0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridgepoint Europe VI Co-Invest', 24400637.0, 'USD', 2019, 'private_equity', 21663539.0, 21518653.0, 21976832.0, 15.81, 2.01, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Capital Partners IV, L.P. (Co-Invest)', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:9542470785de1259f6664d9e2c7636ab', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Capital Partners IV, L.P. (Co-Invest)', 22000000.0, 'USD', 2018, 'private_equity', 22029959.0, 3069976.0, 40073906.0, 12.83, 1.96, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Small Cap Fund, L.P.', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:e870dd4812dc5cc8146ef05c283a5f29', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Small Cap Fund, L.P.', 32500000.0, 'USD', 2018, 'private_equity', 30820161.0, 15128158.0, 32395553.0, 11.81, 1.54, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT VIII SCSP (Co-Invest)', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-01:b745cf604ffcc3764411dd0b210dab2a', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT VIII SCSP (Co-Invest)', 31409196.0, 'USD', 2018, 'private_equity', 31797407.0, 41790517.0, 25875084.0, 25.11, 2.13, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Teachers'' Retirement System of the City of New York', 'doc', 'nyc-trs-private-equity-01', 'rows', 40));
end $$;
