-- nyc-trs-private-equity-04: Teachers' Retirement System of the City of New York -- NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := '61b12767-046a-49ab-82f1-c2c60917a2d6'::uuid;
  select * into f from ingest.fund_for('Ardian Secondary Fund IX, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:f2cf1c9ae5d694a63716bda12ec1279b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ardian Secondary Fund IX, L.P.', 57800000.0, 'USD', 2023, 'private_equity', 24868284.0, 2567496.0, 27545044.0, 22.45, 1.21, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF IX B NYC Co-Invest L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:96689b6069910c2cdf8834dc0b584088', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF IX B NYC Co-Invest L.P.', 86700000.0, 'USD', 2023, 'private_equity', 33303778.0, 796600.0, 42277394.0, 19.99, 1.29, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Clayton, Dubilier & Rice Fund XII, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:9d6f99a3f9744d6dd5717acc4e841670', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Clayton, Dubilier & Rice Fund XII, L.P.', 78000000.0, 'USD', 2023, 'private_equity', 33214506.0, 7473847.0, 40598767.0, null, 1.45, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT Co-Invest Platform (No.15) SCSP', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:567fb1cc23c3db7fc8ebaadc287a1265', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT Co-Invest Platform (No.15) SCSP', 54475185.0, 'USD', 2023, 'private_equity', 25099082.0, 121937.0, 38425652.0, 22.21, 1.54, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT Future SCSp', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:5c2a99a0e7ff3709ccf064e20a5b29f8', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT Future SCSp', 53439554.0, 'USD', 2023, 'private_equity', 39648589.0, 4117076.0, 49142213.0, 22.19, 1.34, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners IX, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:235d5cdacccd6cdc35506aa291b896b0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners IX, L.P.', 150301235.0, 'USD', 2023, 'private_equity', 44548897.0, 2320841.0, 48000839.0, null, 1.13, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('PSG VI L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:b54c51594e8bee228d1c424e85ae78d0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'PSG VI L.P.', 115500000.0, 'USD', 2023, 'private_equity', 29665127.0, 2863216.0, 27646861.0, null, 1.03, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NYC-Northbound Emerging Managers Program II, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:0e64a36b341d853eb0d697375e127293', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NYC-Northbound Emerging Managers Program II, L.P.', 216500000.0, 'USD', 2023, 'private_equity', 24922508.0, null, 25062749.0, null, 1.01, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Resolute Fund VI, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:52329b395f41b9a29b578d56e393f056', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Resolute Fund VI, L.P.', 68250000.0, 'USD', 2023, 'private_equity', 33088064.0, null, 52174272.0, null, 1.58, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TRF VI Co-Investment SMA II, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:34a143db03db0260721ce2eddd8214af', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TRF VI Co-Investment SMA II, L.P.', 22750000.0, 'USD', 2023, 'private_equity', 7542788.0, null, 7974601.0, null, 1.06, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Stellex Capital III NYC Co-Invest LP', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:694531fc9f343bbaf97008733c84a87f', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Stellex Capital III NYC Co-Invest LP', 20000000.0, 'USD', 2024, 'private_equity', 11642411.0, null, 11533378.0, null, 0.99, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Stellex Capital Partners III LP', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:bd2334096acd2e1b7f0cf66091e8c8f0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Stellex Capital Partners III LP', 80000000.0, 'USD', 2024, 'private_equity', 22464156.0, 74508.0, 19393669.0, null, 0.87, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centerbridge Capital Partners V - N Co-Invest, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:a90830db40363b9842803c7dc5aefc45', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centerbridge Capital Partners V - N Co-Invest, L.P.', 81400000.0, 'USD', 2024, 'private_equity', 12484548.0, null, 15612152.0, null, 1.25, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centerbridge Capital Partners V, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:499166042c099f1b95c2fe5cd3bfcbe0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centerbridge Capital Partners V, L.P.', 122100000.0, 'USD', 2024, 'private_equity', 24891226.0, null, 26602173.0, null, 1.07, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('BPEA EQT Mid-Market Growth Partnership SCSp', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:7a17f7d0ad6ee699879c6391dfea4ea9', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'BPEA EQT Mid-Market Growth Partnership SCSp', 75000000.0, 'USD', 2024, 'private_equity', 23611222.0, 669955.0, 26421474.0, null, 1.15, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Clearlake - Neptune Co-Investment, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:85070045860c7c6acbf66c078814fe82', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Clearlake - Neptune Co-Investment, L.P.', 91800000.0, 'USD', 2024, 'private_equity', 25777485.0, null, 28952281.0, null, 1.12, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Clearlake Capital Partners VIII, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:79d75f03ced346d7c1b37070387aee50', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Clearlake Capital Partners VIII, L.P.', 214200000.0, 'USD', 2024, 'private_equity', 14992140.0, 22661.0, 9504670.0, null, 0.64, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Dover Street XI L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:f2830ebcc3d3695d53ed26b54e0e2ecb', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Dover Street XI L.P.', 162150000.0, 'USD', 2024, 'private_equity', 84553982.0, 10561807.0, 101842242.0, null, 1.33, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT PCA Co-Invest Platform (No.1) SCSp', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:9b7e5833a64345bf65288dd2d8886406', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT PCA Co-Invest Platform (No.1) SCSp', 77000000.0, 'USD', 2024, 'private_equity', 57664216.0, null, 72132995.0, null, 1.25, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Co-Investment Fund V-A', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:98f7cccf8bc29cea429db2efced82b34', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Co-Investment Fund V-A', 121000000.0, 'USD', 2024, 'private_equity', 45441478.0, null, 67148637.0, null, 1.48, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Fund V, LP', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:6fa7aca4007696ddd4cf22c5d6cb3c25', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Fund V, LP', 121000000.0, 'USD', 2024, 'private_equity', 32016600.0, 112664.0, 59820847.0, null, 1.87, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Insight Partners XIII, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:313c72bc881fe7311646c110a4ae1b3b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Insight Partners XIII, L.P.', 153750000.0, 'USD', 2024, 'private_equity', 45735514.0, 13859.0, 53350667.0, null, 1.17, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('IP XIII Co-Invest N, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:b8887461bb702bd7471b0a8b7961a2d2', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'IP XIII Co-Invest N, L.P.', 51250000.0, 'USD', 2024, 'private_equity', 14100911.0, null, 13576145.0, null, 0.96, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Small Cap Fund II, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:87e6244291d36c2eaf78439ecc1c130b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Small Cap Fund II, L.P.', 103000000.0, 'USD', 2024, 'private_equity', 24963759.0, 11541058.0, 21175542.0, null, 1.31, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Small Cap Fund II, L.P. - Side Car', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:fc3134bd60c1fe056ea82d12ac633899', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Small Cap Fund II, L.P. - Side Car', 51500000.0, 'USD', 2024, 'private_equity', 12113753.0, null, 13007602.0, null, 1.07, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Secondary Overflow Fund V L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:43e04c58c7d6a2570d948d86b70d8f74', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Secondary Overflow Fund V L.P.', 162150000.0, 'USD', 2024, 'private_equity', 117083431.0, 7046323.0, 140049550.0, null, 1.26, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Sage Equity Investors, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:b7a64c41421ad8c152fbe2f4ede915c0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Sage Equity Investors, L.P.', 109554550.0, 'USD', 2024, 'private_equity', 74858.0, null, 4289900.0, null, 57.31, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Sage Equity Investors-N, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:0be65cea7908a732c390bb9d4804d350', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Sage Equity Investors-N, L.P.', 136635450.0, 'USD', 2024, 'private_equity', 93362.0, null, 6519701.0, null, 69.83, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FTV Ascend I, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:a377dd7156eb1aba1f5a6ad659fffe00', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FTV Ascend I, L.P.', 26473500.0, 'USD', 2024, 'private_equity', 6794098.0, null, 7167049.0, null, 1.05, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FTV VIII, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:735ae86ff688db47c6a4ec85e67c1f35', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FTV VIII, L.P.', 139360500.0, 'USD', 2024, 'private_equity', 75593528.0, 36542.0, 71974399.0, null, 0.95, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Growth VIII-Centre, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:bc88b283c170cfccb290c1d91a81c4e4', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Growth VIII-Centre, L.P.', 41000000.0, 'USD', 2024, 'private_equity', 20517014.0, null, 20405044.0, null, 0.99, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Centre Street Co-Investment Fund L.P. (Series II)', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:db540aa20003e5b1c564c9e3afe1700c', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Centre Street Co-Investment Fund L.P. (Series II)', 201500000.0, 'USD', 2024, 'private_equity', 68006250.0, null, 74041295.0, null, 1.09, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lindsay Goldberg VI - Gotham Co-Inv. L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:e48f21d5ef0f015a34486bf5611383f1', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lindsay Goldberg VI - Gotham Co-Inv. L.P.', 82000000.0, 'USD', 2024, 'private_equity', 4976693.0, 2356251.0, 5044276.0, null, 1.49, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lindsay Goldberg VI L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:e4001fcf4c0f205e10c83ee41732b362', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lindsay Goldberg VI L.P.', 123000000.0, 'USD', 2024, 'private_equity', 4491298.0, 2107476.0, 1362763.0, null, 0.77, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TB Co-Invest Opportunities (Nightingale) II, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:1742c0cd3064ebf83d8f6f14565fd7b4', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TB Co-Invest Opportunities (Nightingale) II, L.P.', 120960000.0, 'USD', 2024, 'private_equity', null, null, null, null, null, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Thoma Bravo Discover Fund V, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:4d77ea5d23e0f167ded195729c446ec7', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Thoma Bravo Discover Fund V, L.P.', 80640000.0, 'USD', 2024, 'private_equity', 11160272.0, null, 10991448.0, null, 0.98, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Thoma Bravo Fund XVI, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:d06207bbcf6cb3304d77ce2892fd8b5b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Thoma Bravo Fund XVI, L.P.', 201600000.0, 'USD', 2024, 'private_equity', 18978075.0, null, 18509776.0, null, 0.98, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TPG Rise Climate II Co-Invest L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:d5b15a16686f0a1a15fc2008c6d10aa6', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TPG Rise Climate II Co-Invest L.P.', 101000000.0, 'USD', 2024, 'private_equity', 21456762.0, null, 21480367.0, null, 1.0, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('TPG Rise Climate II, L.P.', 2024, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:a7cd8af361fabd285c89b5ca8f39ad54', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'TPG Rise Climate II, L.P.', 101000000.0, 'USD', 2024, 'private_equity', null, null, -2632516.0, null, null, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('One Rock Capital Partners - NYC Co-Investment, L.P.', 2023, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-04:4b5d78771eaeebed7ae69052e59fac85', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'One Rock Capital Partners - NYC Co-Investment, L.P.', 50416667.0, 'USD', 2023, 'private_equity', 15623970.0, null, 19447790.0, null, 1.24, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Teachers'' Retirement System of the City of New York', 'doc', 'nyc-trs-private-equity-04', 'rows', 40));
end $$;
