-- nyc-trs-private-equity-02: Teachers' Retirement System of the City of New York -- NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments) (as of 2025-12-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := '61b12767-046a-49ab-82f1-c2c60917a2d6'::uuid;
  select * into f from ingest.fund_for('Vista Equity Partners Fund VII, L.P.', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:acdd35f91f35fbcae2bc4c92d2c94585', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Vista Equity Partners Fund VII, L.P.', 142000000.0, 'USD', 2018, 'private_equity', 141774863.0, 17542187.0, 155308164.0, 4.51, 1.22, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('KKR European Fund V, L.P. - USD', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:f9f3753fe340fb535329ee9245f67527', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'KKR European Fund V, L.P. - USD', 89000000.0, 'USD', 2019, 'private_equity', 86963709.0, 43304295.0, 87076835.0, 11.36, 1.5, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners IX, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:dbf3f4f14e34aecfcac5964b16cda119', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners IX, L.P.', 85125000.0, 'USD', 2019, 'private_equity', 75976673.0, 41408314.0, 76948327.0, 14.66, 1.56, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VIII, L.P.', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:737ee429339752658e17cb6bf4f34f63', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VIII, L.P.', 158000000.0, 'USD', 2018, 'private_equity', 124877766.0, 60747802.0, 113568674.0, 11.84, 1.4, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ASF VIII B NYC Co-Invest, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:f532f4a13d8d9d80e1acdcb3fc57ea74', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ASF VIII B NYC Co-Invest, L.P.', 79000000.0, 'USD', 2019, 'private_equity', 48830028.0, 17395555.0, 45553516.0, 9.68, 1.29, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Warburg Pincus Global Growth, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:4ae378022f0102973f59ac7e1c1af239', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Warburg Pincus Global Growth, L.P.', 114000000.0, 'USD', 2019, 'private_equity', 113078207.0, 68758175.0, 125494267.0, 13.42, 1.72, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('LCP IX Co-Invest Partners B, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:38a56ca71a4c912fa833d2f786293ad0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'LCP IX Co-Invest Partners B, L.P.', 28375000.0, 'USD', 2019, 'private_equity', 20816117.0, 16445408.0, 17597168.0, 19.12, 1.64, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lindsay Goldberg V, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:420d8a4d31a7e3efd20b8b5b63f7fe67', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lindsay Goldberg V, L.P.', 79000000.0, 'USD', 2019, 'private_equity', 68270243.0, 56354370.0, 50127569.0, 17.98, 1.56, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('WCAS XIII, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:9de7fcfbe5edd28832bda475a1638e15', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'WCAS XIII, L.P.', 71000000.0, 'USD', 2019, 'private_equity', 66326165.0, 41222552.0, 71436674.0, 18.08, 1.7, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apax X, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:104adfbacb01ed5ee4bf2bf5551a2502', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apax X, L.P.', 95000000.0, 'USD', 2019, 'private_equity', 95728001.0, 25615662.0, 102506300.0, 9.43, 1.34, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Platinum Equity Capital Partners V, L.P.', 2019, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:a7c7a5965890c3ca060c96edc8693399', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Platinum Equity Capital Partners V, L.P.', 142000000.0, 'USD', 2019, 'private_equity', 141050901.0, 47412145.0, 150788490.0, 8.59, 1.41, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('PECP V Co-Investment, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:6b1061904ada60787e32b620077881d1', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'PECP V Co-Investment, L.P.', 35500000.0, 'USD', 2021, 'private_equity', 38877388.0, 21157301.0, 63610933.0, 23.38, 2.18, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Fund III LP', 2018, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:84d979061e0e4f14960ea8792717f0e4', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Fund III LP', 41111763.0, 'USD', 2018, 'private_equity', 28453264.0, 32569715.0, 24163578.0, 22.4, 1.99, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Green Equity Investors VIII Coinvest N, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:0eb56bc29f50a7fc19e9bcbeba86d0af', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Green Equity Investors VIII Coinvest N, L.P.', 33000000.0, 'USD', 2020, 'private_equity', 27914406.0, 11263892.0, 41219093.0, 16.43, 1.88, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Green Equity Investors VIII, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:46c7b60edcc2c95405efd86a919b5cd5', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Green Equity Investors VIII, L.P.', 99000000.0, 'USD', 2020, 'private_equity', 94385466.0, 36639168.0, 110251094.0, 11.73, 1.56, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Clearlake Capital Partners VI, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:06f9cf96ac787b36fd7663ce227bbef3', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Clearlake Capital Partners VI, L.P.', 42000000.0, 'USD', 2020, 'private_equity', 46659744.0, 11695155.0, 56281018.0, 10.08, 1.46, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('FTV VI, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:52a6beca95f6c50063fd225f8b992155', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'FTV VI, L.P.', 24000000.0, 'USD', 2020, 'private_equity', 26662671.0, 17249948.0, 29265884.0, 15.41, 1.74, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('CVC Capital Partners VIII, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:7233bf201d48d756638f3466280130a7', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'CVC Capital Partners VIII, L.P.', 150785687.0, 'USD', 2021, 'private_equity', 144744893.0, 4132995.0, 182017989.0, 9.47, 1.29, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Hg Genesis 9 L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:42b5812c50e0bc9a6a9f7bf1bd5f87cf', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Hg Genesis 9 L.P.', 46633476.0, 'USD', 2020, 'private_equity', 41301832.0, 16923024.0, 45769044.0, 14.27, 1.52, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Co-Investment Fund III LP', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:2acc9e01cae4747d466b81c1119678c5', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Co-Investment Fund III LP', 20555881.0, 'USD', 2020, 'private_equity', 15192897.0, 15117190.0, 19225940.0, 25.44, 2.26, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('NYC-Northbound Emerging Managers Program, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:bf68781590526f1b1dae8d0d2e5f79e9', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'NYC-Northbound Emerging Managers Program, L.P.', 192000000.0, 'USD', 2020, 'private_equity', 140952723.0, 24684835.0, 189121443.0, 16.75, 1.52, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('One Rock Capital Partners III, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:43235f06ee0b645e6cbe5724b3094047', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'One Rock Capital Partners III, L.P.', 39000000.0, 'USD', 2021, 'private_equity', 37755057.0, 34539247.0, 28437414.0, 20.81, 1.67, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Stellex Capital Partners II, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:b1ff92938967dbc62d1bb11c34de02dc', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Stellex Capital Partners II, L.P.', 46500000.0, 'USD', 2021, 'private_equity', 45909481.0, 9221373.0, 57603090.0, 14.47, 1.46, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT IX (NO.2) USD SCSP', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:67b84e002fedeb5642d71962d2f15479', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT IX (NO.2) USD SCSP', 83678500.0, 'USD', 2020, 'private_equity', 94903751.0, 34699071.0, 96136645.0, 9.84, 1.38, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('EQT IX Co-Invest Platform (No. 3) SCSp', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:3d0898ce3b5e6b565a800673aa7bc119', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'EQT IX Co-Invest Platform (No. 3) SCSp', 22821500.0, 'USD', 2020, 'private_equity', 23110204.0, 913511.0, 32931794.0, 9.11, 1.46, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('KKR Asian Fund IV SCSp', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:9f919c1173e54d496ce7b0bd66a80108', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'KKR Asian Fund IV SCSp', 94000000.0, 'USD', 2020, 'private_equity', 71568559.0, 23506441.0, 86696478.0, 18.51, 1.54, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('T2 Energy Transition Co-Invest', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:11a0c7ed0070f49bc703eabde970af44', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'T2 Energy Transition Co-Invest', 20075198.0, 'USD', 2020, 'private_equity', 19525028.0, 13455926.0, 14211787.0, 10.74, 1.42, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('T2 Energy Transition Fund', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:8c1843a5b75358d7ccee7add71203f7e', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'T2 Energy Transition Fund', 37692095.0, 'USD', 2020, 'private_equity', 35427733.0, 13206809.0, 32538638.0, 7.72, 1.29, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('The Resolute Fund V, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:0e0e8aea53e17e56e04061d50e3a6328', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'The Resolute Fund V, L.P.', 65500000.0, 'USD', 2021, 'private_equity', 63240780.0, 5366365.0, 98981358.0, 15.94, 1.65, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Valor Equity Partners V, L.P.', 2020, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:44ddd751f6e6de01d8de9e635e26fc03', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Valor Equity Partners V, L.P.', 23500000.0, 'USD', 2020, 'private_equity', 20929762.0, 1412244.0, 58528718.0, 27.76, 2.86, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Grain Communications Opportunity Fund III, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:f0adf9165f803ff7f0d1f1a34e9ac9fe', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Grain Communications Opportunity Fund III, L.P.', 11781000.0, 'USD', 2021, 'private_equity', 21120712.0, 11066230.0, 10304244.0, 0.44, 1.01, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Co-Investment Fund IV-A LP', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:6ff456010bfe1800f2b34489cb7e7653', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Co-Investment Fund IV-A LP', 47000000.0, 'USD', 2021, 'private_equity', 40949032.0, 775578.0, 47222902.0, 4.5, 1.17, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('ICG Strategic Equity Fund IV LP', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:56fa75a01c1604242056eee26cf00297', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'ICG Strategic Equity Fund IV LP', 94000000.0, 'USD', 2021, 'private_equity', 100854199.0, 28370389.0, 110753213.0, 13.47, 1.38, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centerbridge Capital Partners IV, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:efc915324f23913cffd33cea834a189b', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centerbridge Capital Partners IV, L.P.', 64000000.0, 'USD', 2021, 'private_equity', 71024448.0, 22487879.0, 83304107.0, 17.25, 1.49, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Centre Street Co-Investment Fund, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:53e55b4aeda98c8f1180dd2126775930', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Centre Street Co-Investment Fund, L.P.', 156000000.0, 'USD', 2021, 'private_equity', 141705206.0, 10409256.0, 196084283.0, 12.98, 1.46, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Apax Digital II L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:16e176fcc9c82e000133c7ef6eeb6fb0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Apax Digital II L.P.', 45000000.0, 'USD', 2021, 'private_equity', 23415571.0, null, 26404959.0, 8.32, 1.13, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Corporate Opportunities Fund VI, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:7f30c536ca9c553eedc93dd893e3c990', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Corporate Opportunities Fund VI, L.P.', 100000000.0, 'USD', 2021, 'private_equity', 132277937.0, 55798744.0, 131816701.0, 15.96, 1.42, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Ares Private Opportunities (NYC), L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:d68b41a3451abe368d09ac5da22e96d3', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Ares Private Opportunities (NYC), L.P.', 60000000.0, 'USD', 2021, 'private_equity', 52899183.0, 3196997.0, 99718259.0, 27.29, 1.95, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Centerbridge Capital Partners IV - N Co-Invest, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:c0012603486e6204e6a2261eb7174697', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Centerbridge Capital Partners IV - N Co-Invest, L.P.', 32000000.0, 'USD', 2021, 'private_equity', 42366403.0, 19108856.0, 56619862.0, 28.87, 1.79, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Clearlake Capital Partners VII, L.P.', 2021, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teachers-retirement-system-of-the-city-of-new-york:nyc-trs-private-equity-02:cbd867c4daa4fadc18eec3eb3650def0', v_lp, f.gp_company_id, f.fund_id, 'Teachers'' Retirement System of the City of New York', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Clearlake Capital Partners VII, L.P.', 144000000.0, 'USD', 2021, 'private_equity', 103506025.0, 594634.0, 114087647.0, 3.7, 1.11, '2025-12-31', 'NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)', 'lp_disclosure', 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - NYC Comptroller Monthly Performance Review Material (June 2026) - TRS, Private Equity Portfolio (active investments)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://comptroller.nyc.gov/wp-content/uploads/documents/Monthly-Performance-Review-Material_06-2026-TRS.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Teachers'' Retirement System of the City of New York', 'doc', 'nyc-trs-private-equity-02', 'rows', 40));
end $$;
