-- nystrs-real-estate-infra-q2-2026: New York State Teachers' Retirement System -- Real Estate Equity Commitments and Funding, Quarter Ended June 30, 2026 (as of 2026-06-30, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := '033443fc-4638-479e-af34-8fd709cc1c4b'::uuid;
  select * into f from ingest.fund_for('Cabot Industrial Value Fund VIII, L.P.', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:new-york-state-teachers-retirement-system:nystrs-real-estate-infra-q2-2026:80749a998bf01cfdda98cc9968add8cd', v_lp, f.gp_company_id, f.fund_id, 'New York State Teachers'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Cabot Industrial Value Fund VIII, L.P.', 150000000, 'USD', null, 'real_estate', null, null, null, null, null, '2026-06-30', 'Real Estate Equity Commitments and Funding, Quarter Ended June 30, 2026 (p. 1)', 'lp_disclosure', 'https://nystrs.org/getmedia/a484bcee-b14d-4816-9600-70e1966187e2/RE_Equity_Commitments.pdf', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackstone Infrastructure Partners, L.P.', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:new-york-state-teachers-retirement-system:nystrs-real-estate-infra-q2-2026:851c12090c61fb1f0e4c58082366a8bb', v_lp, f.gp_company_id, f.fund_id, 'New York State Teachers'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackstone Infrastructure Partners, L.P.', 150000000, 'USD', null, 'infrastructure', null, null, null, null, null, '2026-06-30', 'Real Estate Equity Commitments and Funding, Quarter Ended June 30, 2026 (p. 1)', 'lp_disclosure', 'https://nystrs.org/getmedia/a484bcee-b14d-4816-9600-70e1966187e2/RE_Equity_Commitments.pdf', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('KKR Global Infrastructure Investors V, SCSp', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:new-york-state-teachers-retirement-system:nystrs-real-estate-infra-q2-2026:f8471e2c40d945467f7afaee62ac49ac', v_lp, f.gp_company_id, f.fund_id, 'New York State Teachers'' Retirement System', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'KKR Global Infrastructure Investors V, SCSp', 100000000, 'USD', null, 'infrastructure', null, null, null, null, null, '2026-06-30', 'Real Estate Equity Commitments and Funding, Quarter Ended June 30, 2026 (p. 1)', 'lp_disclosure', 'https://nystrs.org/getmedia/a484bcee-b14d-4816-9600-70e1966187e2/RE_Equity_Commitments.pdf', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Real Estate Equity Commitments and Funding, Quarter Ended June 30, 2026'), disclosure_source_url = coalesce(disclosure_source_url, 'https://nystrs.org/getmedia/a484bcee-b14d-4816-9600-70e1966187e2/RE_Equity_Commitments.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'New York State Teachers'' Retirement System', 'doc', 'nystrs-real-estate-infra-q2-2026', 'rows', 3));
end $$;
