-- teesside-usd: Teesside Pension Fund -- Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (as of 2025-03-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Teesside Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://www.teespen.org.uk');
  select * into f from ingest.fund_for('Blackrock Private Opportunities Fund IV', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:9d1ed8e36e1f3aaf0d2b81a643491565', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackrock Private Opportunities Fund IV', 25000000, 'USD', null, 'private_equity', 19454000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics Global Secondaries V', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:11389cc832d7555c63d9b7b6aaf52705', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics Global Secondaries V', 22000000, 'USD', null, 'private_equity', 13825000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Crown Co-Investment Opportunities II', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:581079832c8146305856f134c568def6', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Crown Co-Investment Opportunities II', 30000000, 'USD', null, 'private_equity', 9633000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Crown Co-Investment Opportunities III', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:618f10d66a26b272e055f140cdb7e893', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Crown Co-Investment Opportunities III', 30000000, 'USD', null, 'private_equity', 22380000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Crown Global Opportunities VII', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:5d15346c946904817e2cec86d261e8e0', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Crown Global Opportunities VII', 40000000, 'USD', null, 'private_equity', 22474000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Crown Secondaries Special Opportunities II', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:40e8a7a81b7128118a573f9840175641', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Crown Secondaries Special Opportunities II', 25000000, 'USD', null, 'private_equity', 18458000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Global Co Investment Opportunities IV', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:cebbee45d5b227a94802f07e5cf149fb', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Global Co Investment Opportunities IV', 30000000, 'USD', null, 'private_equity', 21005000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackrock Global Energy & Power Infrastructure Fund III', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:e36aea43e1e579dc47ce1b99ba34ae64', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackrock Global Energy & Power Infrastructure Fund III', 25000000, 'USD', null, 'infrastructure', 16888000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Blackrock Global Renewable Power III', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:8b4ed4442e6d1dbc372254bfeac02365', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Blackrock Global Renewable Power III', 25000000, 'USD', null, 'infrastructure', 21124000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Senior Debt Secondaries II', null, 'private_credit');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside-usd:fa341bc2f09182737c0af6707ec7339b', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Senior Debt Secondaries II', 25000000, 'USD', null, 'private_credit', 18916000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments'), disclosure_source_url = coalesce(disclosure_source_url, 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Teesside Pension Fund', 'doc', 'teesside-usd', 'rows', 10));
end $$;
