-- teesside: Teesside Pension Fund -- Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (as of 2025-03-31, GBP). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Teesside Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://www.teespen.org.uk');
  select * into f from ingest.fund_for('Border to Coast Private Equity Series 1A', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:6205c0f5c7581af3019e26d15d715027', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity Series 1A', 100000000, 'GBP', null, 'private_equity', 67639000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity Series 1B', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:35a42234703269d2dea772902bb1cf54', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity Series 1B', 50000000, 'GBP', null, 'private_equity', 34856000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity Series 1C', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:735bb0201914ee4ea37ff2ad48c15b05', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity Series 1C', 50000000, 'GBP', null, 'private_equity', 42077000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity Series 2A', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:6b10747c1971d37e0a3b11ab9138aa91', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity Series 2A', 100000000, 'GBP', null, 'private_equity', 37736000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity Series 2B', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:6664c571c5200b48c990efdf99469c63', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity Series 2B', 100000000, 'GBP', null, 'private_equity', 20839000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics LGPS Collective for Pools 18/19', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:10c769faa1fb1d3d886a01315e125a23', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics LGPS Collective for Pools 18/19', 10000000, 'GBP', null, 'private_equity', 8068000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Foresight Regional Investments IV', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:b11f993bd9ca6ea799a79c6db190fc41', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Foresight Regional Investments IV', 5000000, 'GBP', null, 'private_equity', 1609000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Hermes Innovation Fund', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:6d2c3fcc988c6728827d8cebbd570c3a', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Hermes Innovation Fund', 20000000, 'GBP', null, 'private_equity', 15743000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure Series 1A', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:7709d13ae0cbc70e844f40b7eefd548b', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure Series 1A', 100000000, 'GBP', null, 'infrastructure', 70210000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure Series 1B', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:05bed6f2982fdcaa541462d3ab3aa12f', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure Series 1B', 50000000, 'GBP', null, 'infrastructure', 36582000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure Series 1C', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:8c8a713d0d9ac61d7ff635fa832ce8e5', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure Series 1C', 50000000, 'GBP', null, 'infrastructure', 40420000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure Series 2A', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:de4d64492817b9b2f9cf4f047e949671', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure Series 2A', 150000000, 'GBP', null, 'infrastructure', 79279000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure Series 2B', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:1ec22a7da58ec1aab921f10ef70fac21', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure Series 2B', 150000000, 'GBP', null, 'infrastructure', 42866000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Climate Opportunities Series 2A', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:394f80eb6bfc2c469865401860e79637', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Climate Opportunities Series 2A', 80000000, 'GBP', null, 'infrastructure', 36024000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics Clean Energy Infrastructure UK', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:ef55fc16e0b7ac5d43a3064fda00cb1b', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics Clean Energy Infrastructure UK', 20000000, 'GBP', null, 'infrastructure', 5110000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 57)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics Clean Energy Infrastructure Fund VIII', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:0689eebdff9f48cfb11078e063a3233f', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics Clean Energy Infrastructure Fund VIII', 20000000, 'GBP', null, 'infrastructure', 18734000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital Dynamics Clean Energy Infrastructure Fund VIII - Co Investment', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:dc0e6d109d2f85c753c5e13ec89f19e1', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital Dynamics Clean Energy Infrastructure Fund VIII - Co Investment', 10000000, 'GBP', null, 'infrastructure', 9367000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Gresham House, British Strategic Investment Infrastructure Fund', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:a47f205d4f257b18927e0f4fbbfef20e', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Gresham House, British Strategic Investment Infrastructure Fund', 20000000, 'GBP', null, 'infrastructure', 17533000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Gresham House, British Strategic Investment Infrastructure Fund II', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:085e8280cc9980d702e0a13ef1afb8b9', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Gresham House, British Strategic Investment Infrastructure Fund II', 25000000, 'GBP', null, 'infrastructure', 24740000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Innisfree PFI Continuation Fund', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:0c9818c8e82c8ef83a7da90350fa7219', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Innisfree PFI Continuation Fund', 10000000, 'GBP', null, 'infrastructure', 9708000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Innisfree PFI Secondary Fund 2', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:389fc1fd35165e70d35a30f92621d381', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Innisfree PFI Secondary Fund 2', 10000000, 'GBP', null, 'infrastructure', 8353000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Bridges Evergreen TPF Housing Co-Investment LP', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:72d5e04e179fa4b33da8f77d1ab81688', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Bridges Evergreen TPF Housing Co-Investment LP', 5000000, 'GBP', null, 'real_estate', 807000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Gresham House BSI Housing LP', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:0239842fea51f0778bda6a4d8f84fe24', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Gresham House BSI Housing LP', 20000000, 'GBP', null, 'real_estate', 19546000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('St Arthur Homes', null, 'private_credit');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:teesside-pension-fund:teesside:08e7bbb5ee6f05cd47dc70ad439baf50', v_lp, f.gp_company_id, f.fund_id, 'Teesside Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'St Arthur Homes', 27500000, 'GBP', null, 'private_credit', 17388000, null, null, null, null, '2025-03-31', 'Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments (p. 58)', 'lp_disclosure', 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Teesside Pension Fund Annual Report and Accounts for the year ended 31 March 2025 — note 13 Outstanding Commitments'), disclosure_source_url = coalesce(disclosure_source_url, 'https://moderngov.middlesbrough.gov.uk/documents/s37319/Appendix%20-%20Pension%20Fund%20Annual%20Report.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Teesside Pension Fund', 'doc', 'teesside', 'rows', 24));
end $$;
