-- tyne-and-wear-eur: Tyne and Wear Pension Fund -- Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (as of 2025-03-31, EUR). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Tyne and Wear Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://www.twpf.info');
  select * into f from ingest.fund_for('Pantheon Europe Fund IV', 2005, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:5c0bff2d845c073bcf05be9ec1b2bbee', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Europe Fund IV', 25000000, 'EUR', 2005, null, 23400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Europe Fund V', 2006, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:d68b9f534e7ff0213b97621f522eca01', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Europe Fund V', 35000000, 'EUR', 2006, null, 33100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Europe Fund VI', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:fee123710eee1a2a1563c8af335a449a', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Europe Fund VI', 40000000, 'EUR', 2007, null, 37900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Co-Investment Partners Europe (Lexington CIP Europe)', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:4e7b27cc25e8dc9eb11638ab0bb8e21e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Co-Investment Partners Europe (Lexington CIP Europe)', 30000000, 'EUR', 2007, null, 28500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Secondary 2009 (EURO)', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:9a8a2e0b6fb892b1449c46454fee84e0', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Secondary 2009 (EURO)', 60000000, 'EUR', 2010, null, 57200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Real Estate 2011 S.C.A., SICAR', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:d4b8e273fb0ee77468319721acd7c110', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Real Estate 2011 S.C.A., SICAR', 145000000, 'EUR', 2010, null, 127900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Infrastructure 2009', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:e53825bdd97cb70f553ca653c171084d', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Infrastructure 2009', 70000000, 'EUR', 2010, null, 61200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Direct Infrastructure 2011', 2011, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:2812849c5e36c8c1b964093e25db18b7', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Direct Infrastructure 2011', 85000000, 'EUR', 2011, null, 74800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest International Private Equity Partners VI - Partnership', 2011, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:6dd96941714b07c20bc4a802d483af76', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest International Private Equity Partners VI - Partnership', 50000000, 'EUR', 2011, null, 47500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Europe Fund VII', 2012, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:6e386f069db89c64059b91edf338742e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Europe Fund VII', 25000000, 'EUR', 2012, null, 22900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Infrastructure 2012', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:86063c0b89224c67a399d3d4128795b3', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Infrastructure 2012', 45000000, 'EUR', 2013, null, 37100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Income 2014', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:965e9ac3d7ff24f380f1778fbeb1965d', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Income 2014', 23000000, 'EUR', 2013, null, 20900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Antin Infrastructure Partners II', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:19ed5dce861e8d487c41122f72de7061', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Antin Infrastructure Partners II', 24000000, 'EUR', 2013, null, 20900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Access EUR 2016', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:11d4b627f6869d8f80fde61ccdf1200a', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Access EUR 2016', 24300000, 'EUR', 2017, null, 20600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Access EUR 2018', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:dba37e39aace5ca1368fcce31d955aa9', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Access EUR 2018', 50000000, 'EUR', 2018, null, 39400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Value Real Estate 2019', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:6b579780f610fffb4817f4a0140757c0', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Value Real Estate 2019', 165000000, 'EUR', 2018, null, 122300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Infrastructure 2018', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-eur:697e085be62b414e6ae11e85928b7ff6', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Infrastructure 2018', 110000000, 'EUR', 2019, null, 91800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments'), disclosure_source_url = coalesce(disclosure_source_url, 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Tyne and Wear Pension Fund', 'doc', 'tyne-and-wear-eur', 'rows', 17));
end $$;
