-- tyne-and-wear: Tyne and Wear Pension Fund -- Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (as of 2025-03-31, GBP). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Tyne and Wear Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://www.twpf.info');
  select * into f from ingest.fund_for('Infracapital Partners I', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:b05e0a2a90dedd9da23614cfa0721054', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Infracapital Partners I', 35000000, 'GBP', 2007, null, 32800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Infracapital Partners II', 2014, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:079269254070c0c652535bd2d1d2932f', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Infracapital Partners II', 19600000, 'GBP', 2014, null, 19200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Aberdeen UK PRS Opportunities LP', 2016, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:00f0ab60be0f78338d230ca8f900b97f', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Aberdeen UK PRS Opportunities LP', 64300000, 'GBP', 2016, null, 59100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Infracapital Greenfield Partners I', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:dbdee5d94d1f6a8bb145d02eb6202c8e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Infracapital Greenfield Partners I', 20000000, 'GBP', 2017, null, 19500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Infracapital Partners III', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:ca480ae38320171f938fed98bc53145f', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Infracapital Partners III', 20000000, 'GBP', 2017, null, 17700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pemberton European Debt Investments Jersey II', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:8d0bfecf44c26e0553f8ab0a9cb5dcbb', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pemberton European Debt Investments Jersey II', 190000000, 'GBP', 2018, null, 163400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S1A', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:54872c190b011512c78961297713daf1', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S1A', 80000000, 'GBP', 2019, null, 62200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S1A', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:bcff414f1706349e339ebaa0407df8f9', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S1A', 60000000, 'GBP', 2019, null, 48500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S1A&B', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:bd7d9486f1580d431b1612b9d2d79a25', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S1A&B', 160000000, 'GBP', 2019, null, 124400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S1B', 2020, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:7b49070454d649c5332c361e6d117b37', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S1B', 120000000, 'GBP', 2020, null, 87300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S1B', 2020, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:ebebd4905adfdf00a2561f672bb19a6e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S1B', 90000000, 'GBP', 2020, null, 65500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S1C', 2021, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:08d2732b6fa3d8619da3df620dec4cf2', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S1C', 350000000, 'GBP', 2021, null, 294800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S1C', 2021, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:e9ba2969f10fecb93d7ae9b2627b6be9', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S1C', 348200000, 'GBP', 2021, null, 235500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S2A', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:7da5d212ce6ebd9d58a5666e019f58ae', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S2A', 225000000, 'GBP', 2022, null, 87500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S2A', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:3e8b26eb6c225086e962730eceeb52d2', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S2A', 250000000, 'GBP', 2022, null, 132800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S2A', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:8f6766b3d0183563b2acc9a19c6f2231', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S2A', 300000000, 'GBP', 2022, null, 124400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Climate Opportunities 1', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:68140e7d5be47f01dfbcbb178296fe40', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Climate Opportunities 1', 465000000, 'GBP', 2022, null, 211000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('M&G Shared Ownership Fund', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:8d43c75d7965c323b3c3b047e4b3e1cf', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'M&G Shared Ownership Fund', 40000000, 'GBP', 2022, null, 0, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S2B', 2023, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:18e6a9f416cc7511f15315df7e118606', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S2B', 200000000, 'GBP', 2023, null, 41900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S2B', 2023, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:b1546e56d70acd41a73b6e96efe4ce47', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S2B', 225000000, 'GBP', 2023, null, 64500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S2B', 2023, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:084614857e6909da573444cb911d6fea', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S2B', 225000000, 'GBP', 2023, null, 45500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Global Value Add Real Estate Fund', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:240e35b7a2d7695b21050af88ab59951', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Global Value Add Real Estate Fund', 150000000, 'GBP', 2024, null, 11700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Global Core Real Estate Fund', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:8a8de3eca1e4f7e86363a8e2bb69aefb', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Global Core Real Estate Fund', 50000000, 'GBP', 2024, null, 9400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S2C', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:a3f03feb0030b6a7bb9fc9b5722a24e1', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S2C', 175000000, 'GBP', 2024, null, 15100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Climate Opportunities 2', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:144c0d17515e40968e8d2d61450c31be', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Climate Opportunities 2', 200000000, 'GBP', 2024, null, 19500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast UK Opportunities', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:327ca7111504525d8cd01e742c50c0b3', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast UK Opportunities', 100000000, 'GBP', 2024, null, 7400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S2C', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:c24336b83f7eb724d192d67ddbeeede4', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S2C', 175000000, 'GBP', 2024, null, 34200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S2C', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:656761406e49b3b03506b6845e75257f', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S2C', 200000000, 'GBP', 2024, null, 17100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon PSD III', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:5d44441b8b3f619a820cce1dce7ea849', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon PSD III', 50000000, 'GBP', 2024, null, 19400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Foresight Regional Investment IV', 2024, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:48d508cf21016454d779ce806010176a', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Foresight Regional Investment IV', 30000000, 'GBP', 2024, null, 9800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Equity S3A', 2025, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:7c58db9b7a94b11dd7a49449cb38b585', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Equity S3A', 250000000, 'GBP', 2025, null, 0, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Infrastructure S3A', 2025, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:844ad355a71b668d97187c85e2932171', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Infrastructure S3A', 150000000, 'GBP', 2025, null, 0, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Border to Coast Private Debt S3A', 2025, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear:91137288ac8aabea55d840db28d5ac02', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Border to Coast Private Debt S3A', 250000000, 'GBP', 2025, null, 0, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments'), disclosure_source_url = coalesce(disclosure_source_url, 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Tyne and Wear Pension Fund', 'doc', 'tyne-and-wear', 'rows', 33));
end $$;
