-- tyne-and-wear-usd: Tyne and Wear Pension Fund -- Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (as of 2025-03-31, USD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Tyne and Wear Pension Fund', 'LGPS Fund', 'United Kingdom', 'https://www.twpf.info');
  select * into f from ingest.fund_for('HarbourVest Partners VII Cayman Venture Fund', 2002, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:877e6531534bf1b9af65b0206b7171dd', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners VII Cayman Venture Fund', 28000000, 'USD', 2002, null, 27500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Asia Fund IV', 2005, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:5ba887d78a6f2e0d9274b29e5b50eedf', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Asia Fund IV', 20000000, 'USD', 2005, null, 18900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon USA Fund VI', 2005, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:0f32db1642529c9d77660f6492f4ff2c', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon USA Fund VI', 30000000, 'USD', 2005, null, 28300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners VI-B', 2005, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:ce21d55a08306b4a7a4e853db2b02826', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners VI-B', 30000000, 'USD', 2005, null, 29500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Morgan Stanley PMF III', 2005, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:4e1bb416e7d995e5a3b3d7128e2315a9', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Morgan Stanley PMF III', 50000000, 'USD', 2005, null, 48700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners VIII Cayman Buyout Fund', 2006, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:c064bcd23ac3b53e973152bea9898e22', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners VIII Cayman Buyout Fund', 112000000, 'USD', 2006, null, 108600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners VIII Cayman Venture Fund', 2006, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:9798752ceacae148107291fe5ff776e1', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners VIII Cayman Venture Fund', 56000000, 'USD', 2006, null, 54900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon USA Fund VII', 2006, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:46e237ca9127159c56b381af068de1ba', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon USA Fund VII', 35000000, 'USD', 2006, null, 32600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Morgan Stanley Global Distressed Opportunites Fund', 2006, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:b560d87bcc9877d01b09519fbcabe17c', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Morgan Stanley Global Distressed Opportunites Fund', 10000000, 'USD', 2006, null, 9800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners 2007 Direct Fund', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:aaf71279f9199525e43bce97f7662f10', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners 2007 Direct Fund', 30000000, 'USD', 2007, null, 29300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Asia Fund V', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:6c4d9a380265d5975ed6ab9187b2d767', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Asia Fund V', 20000000, 'USD', 2007, null, 19100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon USA Fund VIII', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:63dfdf2d2d35433443b9b4afd43cdd05', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon USA Fund VIII', 35000000, 'USD', 2007, null, 32500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Morgan Stanley PMF IV', 2007, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:5011979902116a33ec79cd94c7dcd4c4', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Morgan Stanley PMF IV', 30000000, 'USD', 2007, null, 29800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Capital International Private Equity Fund VI', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:23e4e5675912a7b75831706f1a9f5a7a', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Capital International Private Equity Fund VI', 35000000, 'USD', 2010, null, 31700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners VII', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:3381639acf2011937d92efbd3804c096', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners VII', 29000000, 'USD', 2010, null, 24400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Asia-Pacific & Emerging Markets Real Estate 2009 LP', 2010, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:1f448ecbdb94723fd1843bf5a4126c50', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Asia-Pacific & Emerging Markets Real Estate 2009 LP', 40000000, 'USD', 2010, null, 37700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Direct Real Estate 2011 S.C.A., SICAR', 2011, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:140629df132e804b922c2bc4b8d30b24', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Direct Real Estate 2011 S.C.A., SICAR', 100000000, 'USD', 2011, null, 92200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Asia-Pacific Real Estate 2011 S.C.A., SICAR', 2011, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:a97ecfcc254016297b6e4ce08e4243be', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Asia-Pacific Real Estate 2011 S.C.A., SICAR', 65000000, 'USD', 2011, null, 55100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Global Infrastructure Partners II', 2011, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:adb615d22f38b60421dbbb7db3f05475', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Global Infrastructure Partners II', 43000000, 'USD', 2011, null, 39000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners VI', 2012, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:4d99c080943c19abad537cb7f84bb73c', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners VI', 33900000, 'USD', 2012, null, 31600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Asia Fund VI', 2012, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:2a1f0c0f6bd7481f56c5f096956fc022', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Asia Fund VI', 40000000, 'USD', 2012, null, 37600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon USA Fund IX', 2012, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:767d51747c389ac521de30569068bdfc', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon USA Fund IX', 30000000, 'USD', 2012, null, 27200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate 2014', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:0990e64f513ec4ceefe996345e7f5703', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate 2014', 64000000, 'USD', 2013, null, 46500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Global Real Estate 2013', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:cee9d807449bb785783fd7970a0bcf01', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Global Real Estate 2013', 130000000, 'USD', 2013, null, 101300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Secondary 2013', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:db3c251dffba1a0ea23e132968e35a17', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Secondary 2013', 65000000, 'USD', 2013, null, 46800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Dover Street VIII Cayman Fund LP', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:831eb98eb0b8443aedc0ebb03b233c43', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Dover Street VIII Cayman Fund LP', 30000000, 'USD', 2013, null, 27600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners IX - Cayman Buyout Fund', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:bfa9a7e8c3c7b6a385d465432dbcd3c8', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners IX - Cayman Buyout Fund', 60000000, 'USD', 2013, null, 52800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners IX - Cayman Venture Fund', 2013, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:a84e791513994b5673fac3d385d6f493', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners IX - Cayman Venture Fund', 30000000, 'USD', 2013, null, 28500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners 2013 Cayman Direct Fund LP', 2014, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:b568edf236996749f8c4d7c4d59913dc', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners 2013 Cayman Direct Fund LP', 30000000, 'USD', 2014, null, 29000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners VIII', 2014, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:ef6fccff0bebf157bb134e086ed11148', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners VIII', 30000000, 'USD', 2014, null, 24200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest International Private Equity Partners VII - Partnership', 2014, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:7d0ab901724518f56eaeeea3b1dd42a6', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest International Private Equity Partners VII - Partnership', 70000000, 'USD', 2014, null, 64000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Neuberger Berman Crossroads Fund XX', 2014, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:07e3287088f5af81404cbd503d492fa7', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Neuberger Berman Crossroads Fund XX', 26000000, 'USD', 2014, null, 19600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners VII', 2015, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:e341923d5b05609a3489bdf67e246d51', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners VII', 45000000, 'USD', 2015, null, 31200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners X - AIF Buyout Fund', 2015, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:c7fce2e71b129d80ab05ddb3031383a8', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners X - AIF Buyout Fund', 50000000, 'USD', 2015, null, 39600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners X - AIF Venture Fund', 2015, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:83a95e19d7fbcce13290fd162328f87c', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners X - AIF Venture Fund', 25000000, 'USD', 2015, null, 23500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Dover Street IX LP', 2016, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:dcd0a4ae3b98d6879506621fc585ceb2', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Dover Street IX LP', 30000000, 'USD', 2016, null, 27300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Direct Infrastructure 2015', 2016, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:226f87988798e808faa21d7573e3980c', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Direct Infrastructure 2015', 140000000, 'USD', 2016, null, 117600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners Co-Investment Fund IV AIF', 2016, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:589bd4fa7da26019cdd33eed7c4b3c4e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners Co-Investment Fund IV AIF', 30000000, 'USD', 2016, null, 27900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 60)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Access USD 2016', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:4abcd1215ff5d5c723d0e28bfc33c4f9', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Access USD 2016', 65000000, 'USD', 2017, null, 59000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HIPEP VIII Partnership Fund', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:21f9f621e8b20494846f6f864e3ccee6', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HIPEP VIII Partnership Fund', 80000000, 'USD', 2017, null, 72600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Global Infrastructure III', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:6f9477cc5f968470151e40b817d40d54', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Global Infrastructure III', 55000000, 'USD', 2017, null, 49600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Global Infrastructure III (former NCC)', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:e32f535feff81c59122d4fc5d311da35', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Global Infrastructure III (former NCC)', 54000000, 'USD', 2017, null, 48900000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Secondary 2017', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:c1b2c4d9111f721354a269a5fc1823c5', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Secondary 2017', 135000000, 'USD', 2017, null, 83700000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Access USD 2017', 2017, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:0dcf43fd8ec19a71adee2a1da42250df', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Access USD 2017', 65200000, 'USD', 2017, null, 54800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners XI', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:43f62c0b4ed2a93c0fbd723fe1a32663', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners XI', 100000000, 'USD', 2018, null, 83200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Lexington Capital Partners IX', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:e73f9130ab595b1afbc57c7af874940e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Lexington Capital Partners IX', 70000000, 'USD', 2018, null, 55400000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Access USD 2018', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:84a9bcdc9bc92934582e14ed638f5277', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Access USD 2018', 120000000, 'USD', 2018, null, 104200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Partners Co-Investment V Feeder AIF', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:6427cadcd9235fb495405852777d4f2e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Partners Co-Investment V Feeder AIF', 70000000, 'USD', 2018, null, 63000000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('InfraBridge Global Infrastructure II', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:906b5f1fc4c6297af385d9987ed818dd', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'InfraBridge Global Infrastructure II', 55000000, 'USD', 2018, null, 54500000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Opportunities 2019', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:5f43e68c18cd6d5a62d6afee29698113', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Opportunities 2019', 380000000, 'USD', 2018, null, 242600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HPS Core Senior Lending Fund', 2018, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:7a72861196f6e6ec07f16d1a6479aada', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HPS Core Senior Lending Fund', 250000000, 'USD', 2018, null, 200200000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Coller International Partners VIII', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:108d373ab62bc840a18b860726dc996a', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Coller International Partners VIII', 80000000, 'USD', 2019, null, 46600000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('HarbourVest Dover Street X', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:1938a486ceb2a68a8ea336fb7c95c8f8', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'HarbourVest Dover Street X', 80000000, 'USD', 2019, null, 64800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Pantheon Private Debt PSD II', 2019, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:18f4260878470e0aeb9091748cbfdf7e', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Pantheon Private Debt PSD II', 200000000, 'USD', 2019, null, 158300000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Direct Infrastructure III (2020)', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:9a12c1a8c8cbbf82433fd2810f706bda', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Direct Infrastructure III (2020)', 70000000, 'USD', 2022, null, 50100000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Partners Group Real Estate Secondary 2021', 2022, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:tyne-and-wear-pension-fund:tyne-and-wear-usd:ffb98d316ab3d939a4092e8336bc0992', v_lp, f.gp_company_id, f.fund_id, 'Tyne and Wear Pension Fund', coalesce(null, (select name from public.companies where id = f.gp_company_id)), 'Partners Group Real Estate Secondary 2021', 280000000, 'USD', 2022, null, 135800000, null, null, null, null, '2025-03-31', 'Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments (p. 61)', 'lp_disclosure', 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf', '2025-03-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Tyne and Wear Pension Fund Annual Report 2024/25 — note 22 Outstanding Commitments'), disclosure_source_url = coalesce(disclosure_source_url, 'https://lgpsboard.org/wp-content/uploads/2026/03/Tyne-and-Wear-2425-final.pdf') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Tyne and Wear Pension Fund', 'doc', 'tyne-and-wear-usd', 'rows', 56));
end $$;
