-- unisuper: UniSuper -- UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (as of 2026-06-30, AUD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('UniSuper', 'Superannuation Fund', 'Australia', 'https://www.unisuper.com.au');
  select * into f from ingest.fund_for('Private equity mandate (Clearbell Capital LLP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:b2832a81b5e48fc2afa768f64424cf5f', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Clearbell Capital LLP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Clearbell Capital LLP)', null, 'AUD', null, 'private_equity', null, null, 1588, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Apax Partners Worldwide LLP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:b538750f3140be052ef59d983bc22271', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Apax Partners Worldwide LLP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Apax Partners Worldwide LLP)', null, 'AUD', null, 'private_equity', null, null, 1726238, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Astarte Capital Partners LLP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:a5708385ecd73b33a22c25cf761e128e', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Astarte Capital Partners LLP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Astarte Capital Partners LLP)', null, 'AUD', null, 'private_equity', null, null, 55726043, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Catalyst Investment Managers Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:2cd6450db5e1322dbabd166d94ab1a1d', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Catalyst Investment Managers Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Catalyst Investment Managers Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 464314, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Clarus Ventures II GP, L.P.)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:925519e57bee3bf16f6f66933fb795db', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Clarus Ventures II GP, L.P.', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Clarus Ventures II GP, L.P.)', null, 'AUD', null, 'private_equity', null, null, 198672, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Commonwealth Venture (GP) Partners IV L.P.)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:381ee08f09f5cc7c5b21a22474c339bd', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Commonwealth Venture (GP) Partners IV L.P.', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Commonwealth Venture (GP) Partners IV L.P.)', null, 'AUD', null, 'private_equity', null, null, 1671663, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (ECP Asset Management Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:85f9a60d5ac5b14a08699cda42cfb503', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('ECP Asset Management Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (ECP Asset Management Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 7331642, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (First Sentier Investors (australia) IM Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:178e24bf5ad7df9991a18c0f4a999624', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('First Sentier Investors (australia) IM Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (First Sentier Investors (australia) IM Limited)', null, 'AUD', null, 'private_equity', null, null, 238602319, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Generation Investment Management US LLP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:3bab127b0ecf427c60311ffc3161913d', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Generation Investment Management US LLP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Generation Investment Management US LLP)', null, 'AUD', null, 'private_equity', null, null, 44356, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Hancock Park Associates LLP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:9405cec2b47e45a0e10cec4e03b0d153', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Hancock Park Associates LLP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Hancock Park Associates LLP)', null, 'AUD', null, 'private_equity', null, null, 1478712, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (IFM Investors Pty Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:b9b397ac082f4e486e4a10070346a5ac', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('IFM Investors Pty Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (IFM Investors Pty Limited)', null, 'AUD', null, 'private_equity', null, null, 250318545, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Lennox Capital Partners Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:f44bbd9f444f70c8850864f07d6a38b3', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Lennox Capital Partners Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Lennox Capital Partners Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 17550700, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Macquarie Asset Management)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:1d835a96dd5f7a21d8409f55f59bbea8', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Macquarie Asset Management', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Macquarie Asset Management)', null, 'AUD', null, 'private_equity', null, null, 451802632, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Macquarie Fund Advisers Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:987249d32f721081f160a7a18d78a0a2', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Macquarie Fund Advisers Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Macquarie Fund Advisers Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 58156, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Manulife Investment Management)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:f99692d57f6d0b3aac60f83e53cbf411', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Manulife Investment Management', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Manulife Investment Management)', null, 'AUD', null, 'private_equity', null, null, 1774031, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Partners Group AG)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:4e5d6d97aa05ef2875c09bb4d60b7511', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Partners Group AG', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Partners Group AG)', null, 'AUD', null, 'private_equity', null, null, 112853505, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Pendal Fund Services Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:0f7fbcb8e5390ae30e47e612b07c058a', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Pendal Fund Services Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Pendal Fund Services Limited)', null, 'AUD', null, 'private_equity', null, null, 268428632, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Perennial Value Management Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:c7d9a0edd17f77fdde25bc8c8c801d53', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Perennial Value Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Perennial Value Management Limited)', null, 'AUD', null, 'private_equity', null, null, 75059458, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Polaris Ventures Partners LP)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:b02d0055797f4df005d035c2a0b6bafb', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Polaris Ventures Partners LP', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Polaris Ventures Partners LP)', null, 'AUD', null, 'private_equity', null, null, 2640676, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Regal Funds MGMT Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:52e0cfdd9acdd3da4305c54ee1221fd9', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Regal Funds MGMT Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Regal Funds MGMT Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 192721857, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (State Street BNK and Trust CPY)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:497dea5eb93a808807853b6cc867f105', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('State Street BNK and Trust CPY', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (State Street BNK and Trust CPY)', null, 'AUD', null, 'private_equity', null, null, 855346, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (T. Rowe Price Australia Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:2586047b4f43e9ee492fe18783272708', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('T. Rowe Price Australia Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (T. Rowe Price Australia Limited)', null, 'AUD', null, 'private_equity', null, null, 6890879, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Tencap INV MGMT Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:4bd8a5bc206b8d068cae8e1fcef92869', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Tencap INV MGMT Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Tencap INV MGMT Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 585804901, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Fitzwalter Capital Partners GP II Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:c25a0f704dc66a2ee5d3ff7c4b6aa477', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Fitzwalter Capital Partners GP II Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Fitzwalter Capital Partners GP II Ltd)', null, 'AUD', null, 'private_equity', null, null, 82150898, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Fitzwalter Capital Partners GP Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:ff91b2e9c36c2932f6120ff29d7cbd71', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Fitzwalter Capital Partners GP Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Fitzwalter Capital Partners GP Ltd)', null, 'AUD', null, 'private_equity', null, null, 95496896, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Uniseed Management Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:743ba49f89abf6b482e9db2efb8429d4', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Uniseed Management Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Uniseed Management Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 58278078, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Kohlberg Kravis Roberts & CO)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:a99527edd3d3a6bfa0b21e36e421743f', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Kohlberg Kravis Roberts & CO', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Kohlberg Kravis Roberts & CO)', null, 'AUD', null, 'private_equity', null, null, 324895511, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (The GPT Group)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:9a8efdc52cc9fbd05ce2162101f50965', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('The GPT Group', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (The GPT Group)', null, 'AUD', null, 'real_estate', null, null, 1092691083, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Clearbell Fund Management Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:9ed9447d907f82b1a8082ba281f8fdec', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Clearbell Fund Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Clearbell Fund Management Limited)', null, 'AUD', null, 'real_estate', null, null, 24362806, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Dexus Capital Funds Management Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:b026b5a70a8631be0b79c889b4cfa6fc', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Dexus Capital Funds Management Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Dexus Capital Funds Management Limited)', null, 'AUD', null, 'real_estate', null, null, 14132255, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Goodman Funds Management Australia Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:c3e430e4c189179be5f0f1d610d04ad5', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Goodman Funds Management Australia Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Goodman Funds Management Australia Limited)', null, 'AUD', null, 'real_estate', null, null, 113593451, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (IFM Real Estate)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:20bdaa5f6c3b45ef951d2628ec4f6d53', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('IFM Real Estate', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (IFM Real Estate)', null, 'AUD', null, 'real_estate', null, null, 260759810, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Lendlease Real Estate Investments Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:17b9aaf58e5840d8314f22c6a7aaef6f', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Lendlease Real Estate Investments Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Lendlease Real Estate Investments Limited)', null, 'AUD', null, 'real_estate', null, null, 64775319, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Mirvac Funds Management Australia Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:58a63833eb79c3aaab689989c0efa051', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Mirvac Funds Management Australia Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Mirvac Funds Management Australia Limited)', null, 'AUD', null, 'real_estate', null, null, 97945849, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (Richmond Bridge Investment Manager 1 Pty)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:dc97678fd9d95f45afb47fc97d14b5b9', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Richmond Bridge Investment Manager 1 Pty', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (Richmond Bridge Investment Manager 1 Pty)', null, 'AUD', null, 'real_estate', null, null, 1152649574, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (SC Invest MGMT Pty Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:c0331f0f49e12ce4b79e6766d629b811', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('SC Invest MGMT Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (SC Invest MGMT Pty Ltd)', null, 'AUD', null, 'real_estate', null, null, 19107574, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (First Sentier Investors (australia) IM Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:404cdc5ce2aeb3998727dae4c83c2e39', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('First Sentier Investors (australia) IM Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (First Sentier Investors (australia) IM Limited)', null, 'AUD', null, 'infrastructure', null, null, 212629716, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (IFM Investors Pty Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:1f10144a799d7355fec2d56df75511c0', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('IFM Investors Pty Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (IFM Investors Pty Limited)', null, 'AUD', null, 'infrastructure', null, null, 478526422, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Macquarie Asset Management)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:ba99b6dc2870ae39a9d871f7629f4466', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Macquarie Asset Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Macquarie Asset Management)', null, 'AUD', null, 'infrastructure', null, null, 302629815, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Macquarie Investment Management Global Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:0ffb1d105f34f50f1898cf38ca0b8480', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Macquarie Investment Management Global Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Macquarie Investment Management Global Limited)', null, 'AUD', null, 'infrastructure', null, null, 105601467, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Manulife Investment Management)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:ce849643a593312e001f597a680780ee', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Manulife Investment Management', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Manulife Investment Management)', null, 'AUD', null, 'infrastructure', null, null, 239434902, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (MACQUARIE ASSET MANAGEMENT EUROPE S.à r.l.)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:98dca9b4bd02066c37e6524e4066e04a', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('MACQUARIE ASSET MANAGEMENT EUROPE S.à r.l.', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (MACQUARIE ASSET MANAGEMENT EUROPE S.à r.l.)', null, 'AUD', null, 'infrastructure', null, null, 1, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (New Forests Asset Management Pty Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:d55742368ae3077c39ceea6792a9ba0f', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('New Forests Asset Management Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (New Forests Asset Management Pty Ltd)', null, 'AUD', null, 'infrastructure', null, null, 105261044, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Palisade Investment Partners Limited)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:02c234a231056ff3b03bbd858f49902c', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Palisade Investment Partners Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Palisade Investment Partners Limited)', null, 'AUD', null, 'infrastructure', null, null, 173168255, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Infra Capital Group Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:00f6b46324f0bb79e8765eb846c2d413', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Infra Capital Group Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Infra Capital Group Ltd)', null, 'AUD', null, 'infrastructure', null, null, 280955142, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted alternatives mandate (Fidera Vecta Limited)', null, null);
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:unisuper:unisuper:4cb3596110cf28853e31ae070655ea7f', v_lp, f.gp_company_id, f.fund_id, 'UniSuper', coalesce('Fidera Vecta Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted alternatives mandate (Fidera Vecta Limited)', null, 'AUD', null, null, null, null, 57311389, null, null, '2026-06-30', 'UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets (p. 1)', 'lp_disclosure', 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile', '2026-06-30')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - UniSuper option holdings - Portfolio Holdings Information for Balanced - Table 1 Assets'), disclosure_source_url = coalesce(disclosure_source_url, 'https://www.unisuper.com.au/api/sitecore/investment/GetPortfolioHoldingsFile') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'UniSuper', 'doc', 'unisuper', 'rows', 46));
end $$;
