-- vision-super: Vision Super -- Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (as of 2025-12-31, AUD). Generated; re-run freely.
do $$
declare v_lp uuid; f record;
begin
  v_lp := ingest.lp_company('Vision Super', 'Superannuation Fund', 'Australia', 'https://www.visionsuper.com.au');
  select * into f from ingest.fund_for('Private equity mandate (Baillie Gifford Overseas Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:d23c9c469102222787bb14ec2db653ab', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('Baillie Gifford Overseas Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Baillie Gifford Overseas Limited)', null, 'AUD', null, 'private_equity', null, null, 7153770.53, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (First Sentier Investors (Australia) IM Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:178e24bf5ad7df9991a18c0f4a999624', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('First Sentier Investors (Australia) IM Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (First Sentier Investors (Australia) IM Limited)', null, 'AUD', null, 'private_equity', null, null, 921406.71, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (First Sentier Investors RQI Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:dadf7e6fb5ec500f1c95085d500ac9b8', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('First Sentier Investors RQI Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (First Sentier Investors RQI Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 828377.6, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (IFM Investors Pty Ltd)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:8a6bb0f7b35d752aa56f05b09d8664a2', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'private_equity', null, null, 922982.34, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Lexington Partners)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:1d6c9bba7ee963b0167f820cc7887169', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('Lexington Partners', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Lexington Partners)', null, 'AUD', null, 'private_equity', null, null, 235879.11, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (ROC Capital Pty Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:489f1a5e344fa7b757f890095949b390', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('ROC Capital Pty Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (ROC Capital Pty Limited)', null, 'AUD', null, 'private_equity', null, null, 1285336.31, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (Stafford Capital Partners Pty Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:de18965f4671070e243e682d8d92795c', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('Stafford Capital Partners Pty Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (Stafford Capital Partners Pty Limited)', null, 'AUD', null, 'private_equity', null, null, 1360989.54, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (State Street Global Advisors, Australia, Limited)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:909d1e644460f2eb953ae8e8036a31e2', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('State Street Global Advisors, Australia, Limited', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (State Street Global Advisors, Australia, Limited)', null, 'AUD', null, 'private_equity', null, null, 6805884.81, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (StepStone VC Global Partners IV, L.P.)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:a8bb6618d06d268f50f79f47d09cfc1e', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('StepStone VC Global Partners IV, L.P.', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (StepStone VC Global Partners IV, L.P.)', null, 'AUD', null, 'private_equity', null, null, 348527.88, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Private equity mandate (VenCap International plc)', null, 'private_equity');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:b39fdce170f1b1d30ec24601b99205f4', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('VenCap International plc', (select name from public.companies where id = f.gp_company_id)), 'Private equity mandate (VenCap International plc)', null, 'AUD', null, 'private_equity', null, null, 20259727.14, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (First Sentier Investors (Australia) IM Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:42590913661f5e4348072c6e73248702', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('First Sentier Investors (Australia) IM Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (First Sentier Investors (Australia) IM Limited)', null, 'AUD', null, 'real_estate', null, null, 898276.66, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (ISPT Pty Ltd)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:fa5ab9022ee2243516f46a714eafe206', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('ISPT Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (ISPT Pty Ltd)', null, 'AUD', null, 'real_estate', null, null, 298788010.7, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted property mandate (State Street Global Advisors, Australia, Limited)', null, 'real_estate');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:68fc26b3a6600affe1dbbfb910f058e0', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('State Street Global Advisors, Australia, Limited', (select name from public.companies where id = f.gp_company_id)), 'Unlisted property mandate (State Street Global Advisors, Australia, Limited)', null, 'AUD', null, 'real_estate', null, null, 4281459.5, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (Copenhagen Infrastructure Partners P/S)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:1fc3915ebd5eae8dcb5ff3bef6339fa4', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('Copenhagen Infrastructure Partners P/S', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (Copenhagen Infrastructure Partners P/S)', null, 'AUD', null, 'infrastructure', null, null, 29749795.84, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  select * into f from ingest.fund_for('Unlisted infrastructure mandate (IFM Investors Pty Ltd)', null, 'infrastructure');
  insert into public.commitments as c (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, commitment_year, asset_class, contributed, distributed, remaining_value, net_irr, multiple, as_of, disclosure_type, source, source_url, source_date)
  values ('lpdoc:vision-super:vision-super:f78811fa203c37a6bf56212d1863956d', v_lp, f.gp_company_id, f.fund_id, 'Vision Super', coalesce('IFM Investors Pty Ltd', (select name from public.companies where id = f.gp_company_id)), 'Unlisted infrastructure mandate (IFM Investors Pty Ltd)', null, 'AUD', null, 'infrastructure', null, null, 834192075, null, null, '2025-12-31', 'Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025) (p. 1)', 'lp_disclosure', 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx', '2025-12-31')
  on conflict (external_key) do update set gp_company_id = coalesce(excluded.gp_company_id, c.gp_company_id), fund_id = coalesce(excluded.fund_id, c.fund_id), gp_name = coalesce(excluded.gp_name, c.gp_name), amount = excluded.amount, commitment_year = excluded.commitment_year, asset_class = excluded.asset_class, contributed = excluded.contributed, distributed = excluded.distributed, remaining_value = excluded.remaining_value, net_irr = excluded.net_irr, multiple = excluded.multiple, as_of = excluded.as_of, disclosure_type = excluded.disclosure_type, source_url = excluded.source_url, source_date = excluded.source_date;
  update public.companies set discloses_commitments = coalesce(discloses_commitments, 'Yes - Vision Super - Portfolio Holdings Information for Investment Option Balanced growth - Table 1 Assets (as at 31 Dec 2025)'), disclosure_source_url = coalesce(disclosure_source_url, 'https://docs.visionsuper.com.au/PHD/vision/superNCAP/balancedgrowth/xlsx') where id = v_lp;
  insert into ingest.log (what, detail) values ('load_lp_document', jsonb_build_object('lp', 'Vision Super', 'doc', 'vision-super', 'rows', 15));
end $$;
