-- data_072_of_120.sql: intelligence dataset 2026-09-29, part 72 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:al-nassr:public-investment-fund:august-2026', null, 'August 2026', 'stake_sale', 'sports', 'football', 'Al Nassr', 'club', 'Saudi Arabia', (select id from public.sports_teams where external_key = 'saudi-pro-league--al-nassr'), null, 'Public Investment Fund', 'sovereign_wealth', (select id from public.companies where lower(name) = lower('Public Investment Fund') limit 1), (select id from public.sports_investors where lower(name) = lower('Public Investment Fund') limit 1), 'Al Nassr non-profit foundation (via the Ministry of Sport)', 25, null, null, null, null, 'PIF takes the remaining 25% of Al Nassr from its non-profit foundation', 'The Saudi sports ministry began transferring the 25% foundation stakes in Al Ittihad, Al Ahli, Al Hilal and Al Nassr to PIF, which took 75% in 2023.', 'AGBI', 'https://www.agbi.com/business-of-sport/2026/08/pif-acquires-25-stakes-in-four-saudi-pro-league-clubs/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:al-ittihad:public-investment-fund:august-2026', null, 'August 2026', 'stake_sale', 'sports', 'football', 'Al Ittihad', 'club', 'Saudi Arabia', (select id from public.sports_teams where external_key = 'saudi-pro-league--al-ittihad'), null, 'Public Investment Fund', 'sovereign_wealth', (select id from public.companies where lower(name) = lower('Public Investment Fund') limit 1), (select id from public.sports_investors where lower(name) = lower('Public Investment Fund') limit 1), 'Al Ittihad non-profit foundation (via the Ministry of Sport)', 25, null, null, null, null, 'PIF takes the remaining 25% of Al Ittihad from its non-profit foundation', 'Part of the transfer of the 25% foundation stakes in the four PIF-backed clubs.', 'AGBI', 'https://www.agbi.com/business-of-sport/2026/08/pif-acquires-25-stakes-in-four-saudi-pro-league-clubs/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:al-ahli:public-investment-fund:august-2026', null, 'August 2026', 'stake_sale', 'sports', 'football', 'Al Ahli', 'club', 'Saudi Arabia', (select id from public.sports_teams where external_key = 'saudi-pro-league--al-ahli'), null, 'Public Investment Fund', 'sovereign_wealth', (select id from public.companies where lower(name) = lower('Public Investment Fund') limit 1), (select id from public.sports_investors where lower(name) = lower('Public Investment Fund') limit 1), 'Al Ahli non-profit foundation (via the Ministry of Sport)', 25, null, null, null, null, 'PIF takes the remaining 25% of Al Ahli from its non-profit foundation', 'Part of the transfer of the 25% foundation stakes in the four PIF-backed clubs.', 'AGBI', 'https://www.agbi.com/business-of-sport/2026/08/pif-acquires-25-stakes-in-four-saudi-pro-league-clubs/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
