-- data_106_of_120.sql: intelligence dataset 2026-09-29, part 106 of 120. Run in order; safe to re-run.

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:the-resolute-fund-vii:2026', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('The Resolute Fund VII') limit 1), (select id from public.companies where lower(name) = lower('The Jordan Company') limit 1)), (select id from public.funds where lower(name) = lower('The Resolute Fund VII') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'The Jordan Company', 'The Resolute Fund VII', 150000000, 'USD', null, null, 'August 2026 board meeting', 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/psers-board-announces-investment-actions-and-results', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:trinity-hunt-partners-viii:2026', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('Trinity Hunt Partners VIII') limit 1), (select id from public.companies where lower(name) = lower('Trinity Hunt Partners') limit 1)), (select id from public.funds where lower(name) = lower('Trinity Hunt Partners VIII') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'Trinity Hunt Partners', 'Trinity Hunt Partners VIII', 100000000, 'USD', null, null, 'August 2026 board meeting', 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/psers-board-announces-investment-actions-and-results', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:eqt-exeter-industrial-core-plus-fund-v:2026', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('EQT Exeter Industrial Core-Plus Fund V') limit 1), (select id from public.companies where lower(name) = lower('EQT Exeter') limit 1)), (select id from public.funds where lower(name) = lower('EQT Exeter Industrial Core-Plus Fund V') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'EQT Exeter', 'EQT Exeter Industrial Core-Plus Fund V', 100000000, 'USD', null, null, 'August 2026 board meeting', 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/psers-board-announces-investment-actions-and-results', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:washington-state-investment-board:francisco-partners-viii:2026-02-19', (select id from public.companies where lower(name) = lower('Washington State Investment Board') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('Francisco Partners VIII') limit 1), (select id from public.companies where lower(name) = lower('Francisco Partners') limit 1)), (select id from public.funds where lower(name) = lower('Francisco Partners VIII') limit 1), 'Washington State Investment Board', 'Francisco Partners', 'Francisco Partners VIII', 400000000, 'USD', null, '2026-02-19', null, 2026, 'board_minutes', 'web_research', 'https://www.pionline.com/searches-hires-mandates/pi-washington-state-investment-board-private-equity-february-2026/', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;
