-- data_102_of_120.sql: intelligence dataset 2026-09-29, part 102 of 120. Run in order; safe to re-run.

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('techstartups.com/2026/09/24/venture-capital-startup-funding-roundup-september-24-2026-ark-invest-evolution-equity-mirae-asset-capital-socratic-partners-more', '2026-09-24', 'venture_capital', 'deal', 'Island raises $400m Series F led by Evolution Equity Partners', 'About $1bn raised in total.', array['Island', 'Evolution Equity Partners']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['island', 'evolution equity partners']::text[])), 'Tech Startups', 'https://techstartups.com/2026/09/24/venture-capital-startup-funding-roundup-september-24-2026-ark-invest-evolution-equity-mirae-asset-capital-socratic-partners-more/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('alternativeswatch.com/2026/09/25/pccp-raises-5-billion-real-estate-equity-credit-funds', '2026-09-25', 'real_estate', 'fund_close', 'PCCP raises $5bn across its latest real estate equity and credit funds, both above hard cap', 'Pension commitments across both vehicles.', array['PCCP']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['pccp']::text[])), 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/09/25/pccp-raises-5-billion-real-estate-equity-credit-funds/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('alternativecreditinvestor.com/2026/09/24/blackstone-launches-private-markets-fund-open-to-non-us-investors', '2026-09-24', 'private_equity', 'news', 'Blackstone launches Blackstone Private Markets Fund (BXPM) for non-US investors', 'A perpetual flagship giving non-US investors access to its perpetual funds through one vehicle.', array['Blackstone']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['blackstone']::text[])), 'Alternative Credit Investor', 'https://alternativecreditinvestor.com/2026/09/24/blackstone-launches-private-markets-fund-open-to-non-us-investors/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('alternativeswatch.com/2026/09/28/calstrs-private-equity-real-estate-investments-h1-2026', '2026-09-28', 'private_equity', 'news', 'CalSTRS reports more than $9bn of private equity and real estate activity in the first half of 2026', 'Disclosed at trustees'' September meeting; more than $5bn to real estate.', array['CalSTRS']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['calstrs']::text[])), 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/09/28/calstrs-private-equity-real-estate-investments-h1-2026/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('news.fundsforngos.org/2026/09/28/eif-three-seas-infrastructure-fund-of-funds-360m-mobilise-2b', '2026-09-24', 'infrastructure', 'fundraise', 'EIF launches Three Seas Infrastructure Fund of Funds with €360m to mobilise at least €2bn', 'National partners from Poland, Romania, Lithuania, Bulgaria, Croatia and Slovenia; energy, mobility, digital and social infrastructure.', array['European Investment Fund']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['european investment fund']::text[])), 'fundsforNGOs News', 'https://news.fundsforngos.org/2026/09/28/eif-three-seas-infrastructure-fund-of-funds-360m-mobilise-2b/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-28/samsung-to-invest-1-billion-in-kkr-s-ai-infrastructure-company', '2026-09-28', 'infrastructure', 'deal', 'Samsung group companies to invest $1bn in KKR-backed Helix Digital Infrastructure', 'AI infrastructure company backed by KKR.', array['Samsung', 'KKR', 'Helix Digital Infrastructure']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['samsung', 'kkr', 'helix digital infrastructure']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-28/samsung-to-invest-1-billion-in-kkr-s-ai-infrastructure-company', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/features/2026-09-22/private-equity-firms-hold-assets-longer-in-high-interest-rate-era', '2026-09-22', 'private_equity', 'news', 'Private equity firms hold assets longer in the high-rate era', 'Hellman & Friedman and JMI have held UKG for 19 years with no sale or IPO imminent, Bloomberg reports.', array['Hellman & Friedman', 'JMI Equity', 'UKG']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['hellman & friedman', 'jmi equity', 'ukg']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/features/2026-09-22/private-equity-firms-hold-assets-longer-in-high-interest-rate-era', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
