-- data_095_of_120.sql: intelligence dataset 2026-09-29, part 95 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:general-catalyst-fund-xii:general-catalyst:2024-10-24', '2024-10-24', null, 'fund_close', 'venture_capital', null, 'General Catalyst Fund XII', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('General Catalyst Fund XII') limit 1), 'General Catalyst', 'private_equity', (select id from public.companies where lower(name) = lower('General Catalyst') limit 1), (select id from public.sports_investors where lower(name) = lower('General Catalyst') limit 1), null, null, 8000000000, 'USD', null, null, 'General Catalyst raises $8bn, with $750m set aside for health care', '$4.5bn for seed and growth funds, $1.5bn for company creation and $2bn of separately managed accounts.', 'TechCrunch', 'https://techcrunch.com/2024/10/24/general-catalyst-raises-8b-in-fresh-funds-to-back-startups-globally', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:anthropic:gic-and-coatue-leads:2026-02-12', '2026-02-12', null, 'minority_investment', 'venture_capital', null, 'Anthropic', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Anthropic') limit 1), 'GIC and Coatue (leads)', 'institutional', (select id from public.companies where lower(name) = lower('GIC and Coatue (leads)') limit 1), (select id from public.sports_investors where lower(name) = lower('GIC and Coatue (leads)') limit 1), null, null, 30000000000, 'USD', 380000000000, 'USD', 'Anthropic raises $30bn Series G at a $380bn post-money valuation', 'Led by GIC and Coatue, co-led by D. E. Shaw Ventures, Dragoneer, Founders Fund, ICONIQ and MGX, with BlackRock-affiliated funds, Fidelity, General Catalyst, Sequoia, Temasek and TPG.', 'Anthropic', 'https://www.anthropic.com/news/anthropic-raises-30-billion-series-g-funding-380-billion-post-money-valuation', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:anthropic:altimeter-dragoneer-greenoaks-sequoia-capital-group-coatue-and-d1-co-leads:2026-05-28', '2026-05-28', null, 'minority_investment', 'venture_capital', null, 'Anthropic', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Anthropic') limit 1), 'Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)', 'institutional', (select id from public.companies where lower(name) = lower('Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)') limit 1), (select id from public.sports_investors where lower(name) = lower('Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)') limit 1), null, null, 65000000000, 'USD', 965000000000, 'USD', 'Anthropic closes $65bn Series H at a $965bn post-money valuation', 'Co-led by Altimeter Capital, Dragoneer, Greenoaks, Sequoia Capital, Capital Group, Coatue, D1 Capital Partners and others.', 'Anthropic', 'https://www.anthropic.com/news/series-h', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
