-- data_076_of_120.sql: intelligence dataset 2026-09-29, part 76 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:leeds-equity-partners-2026-private-equity-fund:leeds-equity-partners:april-2026', null, 'April 2026', 'fund_close', 'private_equity', null, 'Leeds Equity Partners 2026 private equity fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Leeds Equity Partners 2026 private equity fund') limit 1), 'Leeds Equity Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Leeds Equity Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Leeds Equity Partners') limit 1), null, null, 1900000000, 'USD', null, null, 'Leeds Equity Partners closes $1.9bn private equity fund', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/04/kirkland-advises-leeds-equity-partners-on-close-of-1-9-billion-private-equity-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:citation-capital-inaugural-fund:citation-capital:july-2026', null, 'July 2026', 'fund_close', 'private_equity', null, 'Citation Capital inaugural fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Citation Capital inaugural fund') limit 1), 'Citation Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Citation Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Citation Capital') limit 1), null, null, 1200000000, 'USD', null, null, 'Citation Capital closes inaugural fund with $1.2bn in total commitments', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/07/kirkland-advises-citation-capital-on-closing-inaugural-fund-with-1-2-billion-in-total-commitments', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:palm-peak-capital-debut-fund:palm-peak-capital:february-2026', null, 'February 2026', 'fund_close', 'private_equity', null, 'Palm Peak Capital debut fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Palm Peak Capital debut fund') limit 1), 'Palm Peak Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Palm Peak Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Palm Peak Capital') limit 1), null, null, 374000000, 'USD', null, null, 'Palm Peak Capital closes oversubscribed debut fund at $374m', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/02/kirkland-advises-palm-peak-capital-on-close-of-oversubscribed-debut-fund-at-$374-million', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
