-- data_109_of_120.sql: intelligence dataset 2026-09-29, part 109 of 120. Run in order; safe to re-run.

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:dry_powder:q2-2025:pitchbook:closed-end-private-capital-dry-powder-en', 'private_equity', null, 'dry_powder', 'Closed-end private capital dry powder, end Q2 2025 (up $201.5bn from year-end 2024)', 4630000000000, 'USD', 'Q2 2025', 'Global', 'PitchBook', null, 'https://pitchbook.com/news/articles/global-private-market-funds-dry-powder-dashboard-2026', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:dry_powder:2025:cherry-bekaert:us-private-equity-dry-powder-record-high', 'private_equity', null, 'dry_powder', 'US private equity dry powder, record high', 1100000000000, 'USD', '2025', 'US', 'Cherry Bekaert', null, 'https://www.cbh.com/insights/reports/private-equity-report-2025-trends-and-2026-outlook/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:index_return:2025:cambridge-associates:cambridge-associates-us-private-equity-i', 'private_equity', null, 'index_return', 'Cambridge Associates US Private Equity Index, calendar year 2025', 8.7, 'pct', '2025', 'US', 'Cambridge Associates', null, 'https://www.cambridgeassociates.com/insight/us-pe-vc-benchmark-commentary-calendar-year-2025/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:pe_growth:index_return:2025:cambridge-associates:cambridge-associates-us-growth-equity-ca', 'private_equity', 'pe_growth', 'index_return', 'Cambridge Associates US growth equity, calendar year 2025', 11.9, 'pct', '2025', 'US', 'Cambridge Associates', null, 'https://www.cambridgeassociates.com/insight/us-pe-vc-benchmark-commentary-calendar-year-2025/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:pe_buyout:index_return:2025:cambridge-associates:cambridge-associates-us-buyouts-calendar', 'private_equity', 'pe_buyout', 'index_return', 'Cambridge Associates US buyouts, calendar year 2025', 7.6, 'pct', '2025', 'US', 'Cambridge Associates', null, 'https://www.cambridgeassociates.com/insight/us-pe-vc-benchmark-commentary-calendar-year-2025/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:fundraising_total:h1-2026:cherry-bekaert:private-equity-capital-commitments-close', 'private_equity', null, 'fundraising_total', 'Private equity capital commitments closed in H1 2026 (more than half of 2025''s $490bn)', 312000000000, 'USD', 'H1 2026', 'Global', 'Cherry Bekaert', null, 'https://www.cbh.com/insights/reports/private-equity-mid-year-2026-report/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:direct_lending:index_return:12-months-to-jun-2026:cliffwater:cliffwater-direct-lending-index-trailing', 'private_credit', 'direct_lending', 'index_return', 'Cliffwater Direct Lending Index, trailing year to 30 June 2026', 7.7, 'pct', '12 months to Jun 2026', 'US', 'Cliffwater', null, 'https://www.prnewswire.com/news-releases/private-credit-shows-resilience-in-cliffwater-direct-lending-index-data-302854703.html', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:all:fundraising_total:2025:mckinsey-preqin-data:closed-end-private-credit-fundraising-20', 'private_credit', null, 'fundraising_total', 'Closed-end private credit fundraising, 2025, down 16% year on year', 165000000000, 'USD', '2025', 'Global', 'McKinsey (Preqin data)', null, 'https://www.mckinsey.com/industries/private-capital/our-insights/global-private-markets-report/private-credit', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;
