-- data_057_of_120.sql: intelligence dataset 2026-09-29, part 57 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arsenal-football-club:kroenke-sports-entertainment-kse-uk-inc:july-august-2020', null, 'July-August 2020', 'stadium_financing', 'sports', 'football', 'Arsenal Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--arsenal'), null, 'Kroenke Sports & Entertainment (KSE UK Inc)', 'individual', (select id from public.companies where lower(name) = lower('Kroenke Sports & Entertainment (KSE UK Inc)') limit 1), (select id from public.sports_investors where lower(name) = lower('Kroenke Sports & Entertainment (KSE UK Inc)') limit 1), null, null, 144000000, 'GBP', null, null, 'KSE redeems Emirates Stadium bonds, replaces them with owner loan', 'Arsenal Securities PLC redeemed the two outstanding bonds (about £144m) taken out to build the Emirates Stadium; KSE replaced them with a new owner loan, removing bondholder covenants and the ~£36m debt service reserve requirement. Arsenal Supporters'' Trust put KSE''s combined refinancing outlay at an estimated £214m.', 'Arsenal Supporters'' Trust', 'https://www.arsenaltrust.org/feed/afc-finances/2020/AST-Debt-Redemption-KSE', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arsenal-football-club:bank-of-england-covid-corporate-financing-facility:january-2021', null, 'January 2021', 'debt_financing', 'sports', 'football', 'Arsenal Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--arsenal'), null, 'Bank of England COVID Corporate Financing Facility', 'other', (select id from public.companies where lower(name) = lower('Bank of England COVID Corporate Financing Facility') limit 1), (select id from public.sports_investors where lower(name) = lower('Bank of England COVID Corporate Financing Facility') limit 1), null, null, 120000000, 'GBP', null, null, 'Arsenal borrows £120m from Bank of England CCFF', 'Arsenal confirmed a £120m loan from the COVID Corporate Financing Facility to cover pandemic losses; the club said KSE would assist in repaying it.', 'Goal', 'https://www.goal.com/en/news/arsenal-120m-bank-of-england-loan/1bom1d3f102fd1v94k39u2rlsk', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arsenal-football-club:kroenke-sports-entertainment:2024-25-accounts-reported-march-2025', null, '2024-25 accounts (reported March 2025)', 'debt_financing', 'sports', 'football', 'Arsenal Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--arsenal'), null, 'Kroenke Sports & Entertainment', 'individual', (select id from public.companies where lower(name) = lower('Kroenke Sports & Entertainment') limit 1), (select id from public.sports_investors where lower(name) = lower('Kroenke Sports & Entertainment') limit 1), null, null, 324100000, 'GBP', null, null, 'Arsenal owes £324.1m in low-interest loans to KSE', 'Owner loans from KSE, accumulated since 2020-21 and described as low-interest rather than interest-free, stood at £324.1m per the club''s accounts.', 'ArsenalNews.co.uk', 'https://arsenalnews.co.uk/2025/03/20/arsenal-now-owe-324-1million-to-owners-kroenke-sports-entertainment/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
