-- data_084_of_120.sql: intelligence dataset 2026-09-29, part 84 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arcmont-direct-lending-fund-iv:arcmont-asset-management:january-2024', null, 'January 2024', 'fund_close', 'private_credit', null, 'Arcmont Direct Lending Fund IV', 'fund', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('Arcmont Direct Lending Fund IV') limit 1), 'Arcmont Asset Management', 'private_credit', (select id from public.companies where lower(name) = lower('Arcmont Asset Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Arcmont Asset Management') limit 1), null, null, 10000000000, 'EUR', null, null, 'Arcmont completes €10bn fundraise for Direct Lending Fund IV', 'High end of the €8–10bn target; about 55% committed at close.', 'Arcmont', 'https://arcmont.com/news-and-insights/arcmont-completes-e10bn-fundraise-for-its-latest-european-direct-lending-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:hps-specialty-loan-fund-vi:hps-investment-partners:2024-06-24', '2024-06-24', null, 'fund_close', 'private_credit', null, 'HPS Specialty Loan Fund VI', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('HPS Specialty Loan Fund VI') limit 1), 'HPS Investment Partners', 'private_credit', (select id from public.companies where lower(name) = lower('HPS Investment Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('HPS Investment Partners') limit 1), null, null, 21100000000, 'USD', null, null, 'HPS closes Specialty Loan Fund VI with $21.1bn of investable capital', 'Final close announced 24 June 2024.', 'PR Newswire via StreetInsider', 'https://www.streetinsider.com/PRNewswire/HPS+Investment+Partners+Raises+Over+$21+Billion+for+Specialty+Loan+Fund+VI/23387571.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:brookfield-infrastructure-debt-fund:brookfield-asset-management:2025-10-01', '2025-10-01', null, 'fund_close', 'private_credit', null, 'Brookfield infrastructure debt fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Brookfield infrastructure debt fund') limit 1), 'Brookfield Asset Management', 'private_credit', (select id from public.companies where lower(name) = lower('Brookfield Asset Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Brookfield Asset Management') limit 1), null, null, 4000000000, 'USD', null, null, 'Brookfield raises $4bn for infrastructure debt fund', 'Reported by Bloomberg on 1 October 2025.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2025-10-01/brookfield-raises-4-billion-for-infrastructure-debt-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
