-- data_063_of_120.sql: intelligence dataset 2026-09-29, part 63 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:burnley-football-club:msd-uk-holdings:december-2020', null, 'December 2020', 'debt_financing', 'sports', 'football', 'Burnley Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--burnley'), null, 'MSD UK Holdings', 'family_office', (select id from public.companies where lower(name) = lower('MSD UK Holdings') limit 1), (select id from public.sports_investors where lower(name) = lower('MSD UK Holdings') limit 1), null, null, 65000000, 'GBP', null, null, 'MSD UK Holdings lends £65m to fund ALK takeover', 'Michael Dell''s family office MSD UK Holdings provided a £65m loan, reported at 8-9% interest, secured against Turf Moor and the club, with a large portion falling due on relegation. Burnley repaid £32.3m of the loan in 2022 after relegation.', 'Sportico', 'https://www.sportico.com/business/sales/2021/alk-capital-burnley-debt-1234621513/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:burnley-football-club:malcolm-jenkins-malcolm-inc:october-2021', null, 'October 2021', 'minority_investment', 'sports', 'football', 'Burnley Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--burnley'), null, 'Malcolm Jenkins (Malcolm Inc.)', 'individual', (select id from public.companies where lower(name) = lower('Malcolm Jenkins (Malcolm Inc.)') limit 1), (select id from public.sports_investors where lower(name) = lower('Malcolm Jenkins (Malcolm Inc.)') limit 1), null, null, null, null, null, null, 'NFL''s Malcolm Jenkins becomes minority investor in Burnley', 'New Orleans Saints safety Malcolm Jenkins'' company Malcolm Inc. took a minority stake in Burnley via ALK Capital, becoming the first active NFL player with a stake in a Premier League club. Terms were not disclosed.', 'New Orleans Saints', 'https://www.neworleanssaints.com/news/new-orleans-saints-safety-malcolm-jenkins-becomes-minority-investor-in-burnley-f', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:burnley-football-club:jj-watt-and-kealia-watt:may-2023', null, 'May 2023', 'minority_investment', 'sports', 'football', 'Burnley Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--burnley'), null, 'JJ Watt and Kealia Watt', 'individual', (select id from public.companies where lower(name) = lower('JJ Watt and Kealia Watt') limit 1), (select id from public.sports_investors where lower(name) = lower('JJ Watt and Kealia Watt') limit 1), null, null, null, null, null, null, 'JJ and Kealia Watt take minority stake in Burnley', 'Retired NFL defensive end JJ Watt and NWSL player Kealia Watt acquired a minority ownership stake in Burnley ahead of the club''s return to the Premier League. Terms were not disclosed; ALK Capital retains 84% with the remaining 16% held by individual shareholders.', 'Front Office Sports', 'https://frontofficesports.com/jj-watt-kealia-watt-invest-in-burnley-fc-english-premier-league/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
