-- data_083_of_120.sql: intelligence dataset 2026-09-29, part 83 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:carlyle-infrastructure-credit-fund-ii:carlyle:september-2026', null, 'September 2026', 'fund_close', 'private_credit', null, 'Carlyle Infrastructure Credit Fund II', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Carlyle Infrastructure Credit Fund II') limit 1), 'Carlyle', 'private_credit', (select id from public.companies where lower(name) = lower('Carlyle') limit 1), (select id from public.sports_investors where lower(name) = lower('Carlyle') limit 1), null, null, 2300000000, 'USD', null, null, 'Carlyle closes Infrastructure Credit Fund II with about $2.3bn', 'Above its $2bn target.', 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/09/14/carlyle-infrastructure-credit-fund-ii-close-2-3-billion/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arini-european-direct-lending-fund:arini-capital-management:2026-09-10', '2026-09-10', null, 'fundraise', 'private_credit', null, 'Arini European direct lending fund', 'fund', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('Arini European direct lending fund') limit 1), 'Arini Capital Management', 'private_credit', (select id from public.companies where lower(name) = lower('Arini Capital Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Arini Capital Management') limit 1), null, null, 4000000000, 'USD', null, null, 'Arini nears $4bn final close of its first European direct lending fund', 'Would rank among the region''s largest debut private credit funds.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-10/arini-nears-4-billion-final-close-of-first-direct-lending-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:oaktree-opportunities-fund-xii:oaktree-capital-management:2025-02-11', '2025-02-11', null, 'fund_close', 'private_credit', null, 'Oaktree Opportunities Fund XII', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Oaktree Opportunities Fund XII') limit 1), 'Oaktree Capital Management', 'private_credit', (select id from public.companies where lower(name) = lower('Oaktree Capital Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Oaktree Capital Management') limit 1), null, null, 16000000000, 'USD', null, null, 'Oaktree closes Opportunities Fund XII at about $16bn', 'Including co-investment and affiliated vehicles; more than $7bn invested or committed at close.', 'Business Wire', 'https://www.businesswire.com/news/home/20250210248809/en/Oaktree-Closes-Opportunities-Fund-XII-at-$16-Billion', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
