-- data_093_of_120.sql: intelligence dataset 2026-09-29, part 93 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:lux-ventures-ix:lux-capital:2026-01-07', '2026-01-07', null, 'fund_close', 'venture_capital', null, 'Lux Ventures IX', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Lux Ventures IX') limit 1), 'Lux Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Lux Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Lux Capital') limit 1), null, null, 1500000000, 'USD', null, null, 'Lux Capital lands more than $1.5bn for Lux IX, its largest fund', 'Closed three months after launch; science, technology and national security focus; AUM above $7bn.', 'TechCrunch', 'https://techcrunch.com/2026/01/07/lux-capital-lands-1-5-billion-for-its-largest-fund-ever/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:andreessen-horowitz-2026-funds:andreessen-horowitz:2026-01-09', '2026-01-09', null, 'fund_close', 'venture_capital', null, 'Andreessen Horowitz 2026 funds', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Andreessen Horowitz 2026 funds') limit 1), 'Andreessen Horowitz', 'private_equity', (select id from public.companies where lower(name) = lower('Andreessen Horowitz') limit 1), (select id from public.sports_investors where lower(name) = lower('Andreessen Horowitz') limit 1), null, null, 15000000000, 'USD', null, null, 'Andreessen Horowitz raises more than $15bn across new funds, its largest haul', 'American Dynamism $1.176bn, Apps $1.7bn, Bio + Health $700m, Infrastructure $1.7bn, Growth $6.75bn and other venture strategies $3bn; AUM above $90bn.', 'CNBC', 'https://www.cnbc.com/2026/01/09/andreessen-horowitz-raises-15-billion-big-in-infrastructure-defense.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:thrive-x:thrive-capital:2026-02-17', '2026-02-17', null, 'fund_close', 'venture_capital', null, 'Thrive X', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Thrive X') limit 1), 'Thrive Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Thrive Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Thrive Capital') limit 1), null, null, 10000000000, 'USD', null, null, 'Thrive Capital raises $10bn for Thrive X, its largest fund', 'About $1bn for early stage and $9bn for growth; heavily oversubscribed.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-02-17/josh-kushner-s-thrive-capital-raises-10-billion-in-new-funding', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
