-- data_105_of_120.sql: intelligence dataset 2026-09-29, part 105 of 120. Run in order; safe to re-run.

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:warwick-v:2026-03-19', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('Warwick V') limit 1), (select id from public.companies where lower(name) = lower('Warwick Investment Group') limit 1)), (select id from public.funds where lower(name) = lower('Warwick V') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'Warwick Investment Group', 'Warwick V', 75000000, 'USD', null, '2026-03-19', null, 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/03192026', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:tpg-peppertree-fund-xi-a:2026-06-17', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('TPG Peppertree Fund XI-A') limit 1), (select id from public.companies where lower(name) = lower('TPG') limit 1)), (select id from public.funds where lower(name) = lower('TPG Peppertree Fund XI-A') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'TPG', 'TPG Peppertree Fund XI-A', 75000000, 'USD', 'up to 75,000,000', '2026-06-17', null, 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/06172026', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:pai-mid-market:2026-06-17', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('PAI Mid-Market') limit 1), (select id from public.companies where lower(name) = lower('PAI Partners') limit 1)), (select id from public.funds where lower(name) = lower('PAI Mid-Market') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'PAI Partners', 'PAI Mid-Market', 100000000, 'EUR', 'up to 100,000,000', '2026-06-17', null, 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/06172026', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:pennsylvania-public-school-employees-retirement-system:american-industrial-partners-capital-fund-ix:2026', (select id from public.companies where lower(name) = lower('Pennsylvania Public School Employees'' Retirement System') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('American Industrial Partners Capital Fund IX') limit 1), (select id from public.companies where lower(name) = lower('American Industrial Partners') limit 1)), (select id from public.funds where lower(name) = lower('American Industrial Partners Capital Fund IX') limit 1), 'Pennsylvania Public School Employees'' Retirement System', 'American Industrial Partners', 'American Industrial Partners Capital Fund IX', 150000000, 'USD', null, null, 'August 2026 board meeting', 2026, 'board_minutes', 'web_research', 'https://www.pa.gov/agencies/psers/newsroom/psers-board-announces-investment-actions-and-results', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;
