-- data_075_of_120.sql: intelligence dataset 2026-09-29, part 75 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:26north-inaugural-private-equity-fund:26north:april-2026', null, 'April 2026', 'fund_close', 'private_equity', null, '26North inaugural private equity fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('26North inaugural private equity fund') limit 1), '26North', 'private_equity', (select id from public.companies where lower(name) = lower('26North') limit 1), (select id from public.sports_investors where lower(name) = lower('26North') limit 1), null, null, 5900000000, 'USD', null, null, '26North closes inaugural private equity fund at $5.9bn', 'Kirkland & Ellis represented 26North on the close.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/04/kirkland-represents-26north-on-close-of-inaugural-private-equity-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:percheron-fund-iii:percheron-capital:april-2026', null, 'April 2026', 'fund_close', 'private_equity', null, 'Percheron Fund III', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Percheron Fund III') limit 1), 'Percheron Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Percheron Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Percheron Capital') limit 1), null, null, 3100000000, 'USD', null, null, 'Percheron closes Fund III at its $3.1bn hard cap', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/04/kirkland-advises-percheron-on-close-of-fund-iii-at-hard-cap', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:court-square-capital-partners-v:court-square-capital-partners:april-2026', null, 'April 2026', 'fund_close', 'private_equity', null, 'Court Square Capital Partners V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Court Square Capital Partners V') limit 1), 'Court Square Capital Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Court Square Capital Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Court Square Capital Partners') limit 1), null, null, 3800000000, 'USD', null, null, 'Court Square closes fifth flagship fund at $3.8bn', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/04/kirkland-advises-court-square-capital-on-close-of-fifth-flagship-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
