-- data_101_of_120.sql: intelligence dataset 2026-09-29, part 101 of 120. Run in order; safe to re-run.

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-15/blackstone-seeks-8-billion-for-green-infrastructure-credit-fund', '2026-09-15', 'infrastructure', 'fundraise', 'Blackstone seeks $8bn for an energy transition and digital infrastructure credit fund', 'A green infrastructure credit strategy, per Bloomberg.', array['Blackstone']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['blackstone']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-15/blackstone-seeks-8-billion-for-green-infrastructure-credit-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('newprivatemarkets.com/blackstone-targets-8-5bn-for-latest-energy-transition-fund', null, 'private_equity', 'fundraise', 'Blackstone targets $8.5bn hard cap for Blackstone Energy Transition Partners V, final close expected this month', 'BETP V held a first close in June; targets a 20% net IRR, 85% North America; predecessor BETP IV closed at $5.6bn in February 2025.', array['Blackstone']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['blackstone']::text[])), 'New Private Markets', 'https://www.newprivatemarkets.com/blackstone-targets-8-5bn-for-latest-energy-transition-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('businesswire.com/news/home/20260923261356/en/bessemer-venture-partners-closes-$5.75-billion-to-back-founders-from-seed-through-growth', '2026-09-23', 'venture_capital', 'fund_close', 'Bessemer Venture Partners closes $5.75bn in a single close: $1.75bn seed and early, $4bn growth', 'Largest raise since its 2022 close of $4.6bn; more than 260 AI-native companies backed since 2022.', array['Bessemer Venture Partners']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['bessemer venture partners']::text[])), 'Business Wire', 'https://www.businesswire.com/news/home/20260923261356/en/Bessemer-Venture-Partners-Closes-$5.75-Billion-to-Back-Founders-From-Seed-Through-Growth', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('techcrunch.com/2026/09/09/harvey-hits-15-5b-valuation-months-after-reaching-11b', '2026-09-09', 'venture_capital', 'deal', 'Harvey raises $550m at a $15.5bn valuation, co-led by Diffusion and Lightspeed', 'Sapphire Ventures and Whale Rock join; Sequoia, a16z, Kleiner Perkins, Coatue and GIC return; ARR above $400m.', array['Harvey', 'Lightspeed Venture Partners', 'Sequoia Capital', 'Andreessen Horowitz', 'Coatue', 'GIC']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['harvey', 'lightspeed venture partners', 'sequoia capital', 'andreessen horowitz', 'coatue', 'gic']::text[])), 'TechCrunch', 'https://techcrunch.com/2026/09/09/harvey-hits-15-5b-valuation-months-after-reaching-11b/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('techstartups.com/2026/09/24/venture-capital-startup-funding-roundup-september-24-2026-ark-invest-evolution-equity-mirae-asset-capital-socratic-partners-more', '2026-09-24', 'venture_capital', 'deal', 'Island raises $400m Series F led by Evolution Equity Partners', 'About $1bn raised in total.', array['Island', 'Evolution Equity Partners']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['island', 'evolution equity partners']::text[])), 'Tech Startups', 'https://techstartups.com/2026/09/24/venture-capital-startup-funding-roundup-september-24-2026-ark-invest-evolution-equity-mirae-asset-capital-socratic-partners-more/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('alternativeswatch.com/2026/09/25/pccp-raises-5-billion-real-estate-equity-credit-funds', '2026-09-25', 'real_estate', 'fund_close', 'PCCP raises $5bn across its latest real estate equity and credit funds, both above hard cap', 'Pension commitments across both vehicles.', array['PCCP']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['pccp']::text[])), 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/09/25/pccp-raises-5-billion-real-estate-equity-credit-funds/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
