-- data_096_of_120.sql: intelligence dataset 2026-09-29, part 96 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:blue-owl-strategic-equity:blue-owl-capital:february-2026', null, 'February 2026', 'fund_close', 'secondaries', null, 'Blue Owl Strategic Equity', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Blue Owl Strategic Equity') limit 1), 'Blue Owl Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Blue Owl Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Blue Owl Capital') limit 1), null, null, 3000000000, 'USD', null, null, 'Blue Owl closes inaugural strategic equity secondaries strategy with over $3bn', 'Raised across institutional and private wealth channels.', 'Blue Owl Capital', 'https://www.blueowl.com/news/blue-owl-capital-closes-inaugural-strategic-equity-secondaries-strategy-over-3-billion-raised', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:pa-secondary-fund-v:future-standard:june-2026', null, 'June 2026', 'fund_close', 'secondaries', null, 'PA Secondary Fund V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('PA Secondary Fund V') limit 1), 'Future Standard', 'private_equity', (select id from public.companies where lower(name) = lower('Future Standard') limit 1), (select id from public.sports_investors where lower(name) = lower('Future Standard') limit 1), null, null, 3000000000, 'USD', null, null, 'Future Standard closes PA Secondary Fund V with about $3bn, its largest private fund', 'Final close of PASF V.', 'PR Newswire', 'https://www.prnewswire.com/news-releases/future-standard-closes-firms-largest-private-fund-to-date-with-approximately-3-billion-in-commitments-302794070.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:stepstone-secondaries-infrastructure-fund:stepstone-group:2026-08-26', '2026-08-26', null, 'fund_close', 'secondaries', null, 'StepStone Secondaries Infrastructure Fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('StepStone Secondaries Infrastructure Fund') limit 1), 'StepStone Group', 'private_equity', (select id from public.companies where lower(name) = lower('StepStone Group') limit 1), (select id from public.sports_investors where lower(name) = lower('StepStone Group') limit 1), null, null, 1700000000, 'USD', null, null, 'StepStone closes infrastructure secondaries fund with $1.7bn across the fund and separate accounts', 'Final close announced 26 August 2026.', 'StepStone Group', 'https://www.stepstonegroup.com/news-insights/stepstone-group-closes-its-infrastructure-secondaries-fund-raising-1-7-billion-across-the-fund-and-related-separate-accounts/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
