-- data_119_of_120.sql: intelligence dataset 2026-09-29, part 119 of 120. Run in order; safe to re-run.

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Advent International') limit 1), (select id from public.companies where lower(name) = lower('Advent International') limit 1) || ':' || 'ccc-intelligent-solutions', 'CCC Intelligent Solutions', null, 'Auto collision repair software platform.', 'Vertical market software', null, null, null, null, null, 'web_research', 'https://pitchbook.com/profiles/investor/10015-12'
  where (select id from public.companies where lower(name) = lower('Advent International') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'chelsea-football-club', 'Chelsea Football Club', null, null, 'Sports', 'London, United Kingdom', 'current', 2022, null, null, 'web_research', 'https://clearlake.com/portfolio/chelsea-fc/'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'fleetgo', 'FleetGO', null, 'Investment on 17 September 2026.', 'Business software', null, 'current', 2026, null, null, 'web_research', 'https://pitchbook.com/profiles/investor/10359-28'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'key-collision', 'Key Collision', null, null, 'Collision repair', 'Southaven, Mississippi', null, null, null, null, 'web_research', 'https://pitchbook.com/profiles/investor/10359-28'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'dun-bradstreet', 'Dun & Bradstreet', null, 'Named among Fund VIII''s recent investments.', 'Data and analytics', null, 'current', null, null, null, 'web_research', 'https://clearlake.com/news/clearlake-capital-closes-on-148-billion-to-capitalize-on-ai-driven-transformation-and-continue-sector-focused-investment-strategy/'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'qualus', 'Qualus', null, 'Named among Fund VIII''s recent investments.', 'Power engineering services', null, 'current', null, null, null, 'web_research', 'https://clearlake.com/news/clearlake-capital-closes-on-148-billion-to-capitalize-on-ai-driven-transformation-and-continue-sector-focused-investment-strategy/'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) || ':' || 'modmed', 'ModMed', null, 'Named among Fund VIII''s recent investments.', 'Healthcare software', null, 'current', null, null, null, 'web_research', 'https://clearlake.com/news/clearlake-capital-closes-on-148-billion-to-capitalize-on-ai-driven-transformation-and-continue-sector-focused-investment-strategy/'
  where (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;
