-- data_100_of_120.sql: intelligence dataset 2026-09-29, part 100 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:freestone-grove-partners:freestone-grove-partners:january-2024', null, 'January 2024', 'fundraise', 'hedge_funds', null, 'Freestone Grove Partners', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Freestone Grove Partners') limit 1), 'Freestone Grove Partners', 'institutional', (select id from public.companies where lower(name) = lower('Freestone Grove Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Freestone Grove Partners') limit 1), null, null, 3500000000, 'USD', null, null, 'Freestone Grove Partners debuts with $3.5bn as an ''anti-pod'' multi-manager', 'Founded by Citadel alumni Todd Barker and Daniel Morillio; San Francisco-based, six sectors.', 'Hedgeweek', 'https://www.hedgeweek.com/freestone-grove-raises-3-5bn-for-anti-pod-multimanager/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-18/fedex-led-group-completes-7-8-billion-buyout-of-poland-s-inpost', '2026-09-18', 'private_equity', 'deal', 'FedEx-led group completes €7.8bn buyout of Poland''s InPost', 'The consortium with Advent International, A&R and PPF cleared the 80% acceptance threshold with about 89.8% of shares tendered; offer of €15.60 a share.', array['FedEx', 'Advent International', 'InPost', 'PPF']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['fedex', 'advent international', 'inpost', 'ppf']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-18/fedex-led-group-completes-7-8-billion-buyout-of-poland-s-inpost', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-14/us-private-credit-default-rate-hits-a-record-of-6-3-fitch-says', '2026-09-14', 'private_credit', 'performance', 'US private credit default rate hits a record 6.3%, Fitch says', 'Trailing 12-month rate across about 1,300 borrowers rose to 6.3% at end-August from 6.1%; 14 default events in the month; healthcare, industrials and manufacturing at 9.9%, software at 0.6%.', array['Fitch Ratings']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['fitch ratings']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-14/us-private-credit-default-rate-hits-a-record-of-6-3-fitch-says', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-17/private-credit-defaults-are-1-6-or-19-depending-who-you-ask', '2026-09-17', 'private_credit', 'news', 'Private credit defaults are 1%, 6% or 19%, depending who you ask', 'Bloomberg on the spread between default measures across data providers.', '{}'::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any('{}'::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-17/private-credit-defaults-are-1-6-or-19-depending-who-you-ask', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bridgepointgroup.com/about-us/news-and-insights/press-releases/2026/bridgepoint-credit-announces-eur1bn-continuation-vehicle-led-by-pantheon', '2026-09-08', 'private_credit', 'deal', 'Bridgepoint Credit moves €1.2bn of Direct Lending II loans into a Pantheon-led continuation vehicle', 'Senior secured loans to European middle-market companies from the 2017-vintage fund; investors could cash out or roll; oversubscribed after a competitive process.', array['Bridgepoint', 'Pantheon']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['bridgepoint', 'pantheon']::text[])), 'Bridgepoint', 'https://www.bridgepointgroup.com/about-us/news-and-insights/press-releases/2026/bridgepoint-credit-announces-eur1bn-continuation-vehicle-led-by-pantheon', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-10/arini-nears-4-billion-final-close-of-first-direct-lending-fund', '2026-09-10', 'private_credit', 'fundraise', 'Arini nears $4bn final close of its first European direct lending fund', 'Among the region''s largest debut private credit funds.', array['Arini Capital Management']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['arini capital management']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-10/arini-nears-4-billion-final-close-of-first-direct-lending-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
