-- data_091_of_120.sql: intelligence dataset 2026-09-29, part 91 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:core-spaces-flagship-fund:core-spaces:may-2026', null, 'May 2026', 'fund_close', 'real_estate', null, 'Core Spaces flagship fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Core Spaces flagship fund') limit 1), 'Core Spaces', 'private_equity', (select id from public.companies where lower(name) = lower('Core Spaces') limit 1), (select id from public.sports_investors where lower(name) = lower('Core Spaces') limit 1), null, null, 1640000000, 'USD', null, null, 'Core Spaces closes $1.64bn flagship fund', 'Kirkland & Ellis advised.', 'Kirkland & Ellis', 'https://www.kirkland.com/news/press-release/2026/05/kirkland-advises-core-spaces-on-close-of-1-64-billion-flagship-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:blackstone-real-estate-debt-strategies-v:blackstone:2025-03-07', '2025-03-07', null, 'fund_close', 'real_estate', null, 'Blackstone Real Estate Debt Strategies V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Blackstone Real Estate Debt Strategies V') limit 1), 'Blackstone', 'private_credit', (select id from public.companies where lower(name) = lower('Blackstone') limit 1), (select id from public.sports_investors where lower(name) = lower('Blackstone') limit 1), null, null, 8000000000, 'USD', null, null, 'Blackstone closes BREDS V with about $8bn of commitments', 'Latest real estate debt strategies fund.', 'Blackstone', 'https://www.blackstone.com/news/press/blackstone-announces-8-billion-final-close-for-latest-real-estate-debt-strategies-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:1-6-million-sq-ft-us-infill-logistics-portfolio-13-assets:eqt-real-estate:2026-01-06', '2026-01-06', null, 'acquisition', 'real_estate', null, '1.6 million sq ft US infill logistics portfolio (13 assets)', 'asset', 'United States', null, null, 'EQT Real Estate', 'private_equity', (select id from public.companies where lower(name) = lower('EQT Real Estate') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT Real Estate') limit 1), null, null, null, null, null, null, 'EQT Real Estate Industrial Value Fund VI acquires 13-asset, 1.6m sq ft US logistics portfolio', 'Orlando, Jacksonville, Chicago, Greenville-Spartanburg, Houston, San Antonio and Indianapolis; price not disclosed.', 'EQT', 'https://eqtgroup.com/news/eqt-real-estate-acquires-16-million-square-foot-us-logistics-portfolio-spanning-key-infill-markets-2026-01-06', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
