-- data_082_of_120.sql: intelligence dataset 2026-09-29, part 82 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:ares-pathfinder-fund-iii:ares-management:2026-06-09', '2026-06-09', null, 'fund_close', 'private_credit', null, 'Ares Pathfinder Fund III', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Ares Pathfinder Fund III') limit 1), 'Ares Management', 'private_credit', (select id from public.companies where lower(name) = lower('Ares Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Ares Management') limit 1), null, null, 8500000000, 'USD', null, null, 'Ares closes Pathfinder Fund III at $8.5bn, $12.7bn with related vehicles, for asset-based finance', 'First and final close under six months after a January 2026 launch; above the $6.5bn target and the $6.6bn Pathfinder II.', 'Business Wire', 'https://www.businesswire.com/news/home/20260609667600/en/Ares-Raises-$12.7-Billion-to-Invest-in-Asset-Based-Finance-Through-the-Pathfinder-Closed-End-Strategy', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:blue-owl-asset-special-opportunities-fund-ix:blue-owl-capital:2026-03-31', '2026-03-31', null, 'fund_close', 'private_credit', null, 'Blue Owl Asset Special Opportunities Fund IX', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Blue Owl Asset Special Opportunities Fund IX') limit 1), 'Blue Owl Capital', 'private_credit', (select id from public.companies where lower(name) = lower('Blue Owl Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Blue Owl Capital') limit 1), null, null, 2900000000, 'USD', null, null, 'Blue Owl closes Asset Special Opportunities Fund IX at about $2.9bn', 'Above the $2.5bn target; asset-backed opportunistic strategy.', 'Blue Owl Capital', 'https://www.blueowl.com/news/blue-owl-capital-announces-29-billion-final-close-asset-special-opportunities-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:carlyle-infrastructure-credit-fund-ii:carlyle:september-2026', null, 'September 2026', 'fund_close', 'private_credit', null, 'Carlyle Infrastructure Credit Fund II', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Carlyle Infrastructure Credit Fund II') limit 1), 'Carlyle', 'private_credit', (select id from public.companies where lower(name) = lower('Carlyle') limit 1), (select id from public.sports_investors where lower(name) = lower('Carlyle') limit 1), null, null, 2300000000, 'USD', null, null, 'Carlyle closes Infrastructure Credit Fund II with about $2.3bn', 'Above its $2bn target.', 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/09/14/carlyle-infrastructure-credit-fund-ii-close-2-3-billion/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
