-- data_099_of_120.sql: intelligence dataset 2026-09-29, part 99 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:lexington-capital-partners-x:lexington-partners:2024-01-09', '2024-01-09', null, 'fund_close', 'secondaries', null, 'Lexington Capital Partners X', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Lexington Capital Partners X') limit 1), 'Lexington Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Lexington Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Lexington Partners') limit 1), null, null, 22700000000, 'USD', null, null, 'Lexington closes LCP X with $22.7bn against a $15bn target', 'Largest secondary fund closed at the time; 2022 vintage, over 40% committed across 50+ transactions.', 'Lexington Partners', 'https://www.lexingtonpartners.com/press-releases/lexington-partners-raises-22-7-billion-for-global-secondary-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:millennium-management-multistrategy-fund:millennium-management:2026-09-25', '2026-09-25', null, 'fundraise', 'hedge_funds', null, 'Millennium Management multistrategy fund', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Millennium Management multistrategy fund') limit 1), 'Millennium Management', 'institutional', (select id from public.companies where lower(name) = lower('Millennium Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Millennium Management') limit 1), null, null, 20000000000, 'USD', null, null, 'Millennium''s record $20bn capital raise draws more than $30bn of client demand', 'Raised in two tranches; the firm manages more than $92bn.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-25/millennium-s-new-cash-raise-draws-30-billion-in-client-demand', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:jain-global:jain-global:2024-07-01', '2024-07-01', null, 'fundraise', 'hedge_funds', null, 'Jain Global', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Jain Global') limit 1), 'Jain Global', 'institutional', (select id from public.companies where lower(name) = lower('Jain Global') limit 1), (select id from public.sports_investors where lower(name) = lower('Jain Global') limit 1), null, null, 5300000000, 'USD', null, null, 'Bobby Jain''s Jain Global launches with $5.3bn, the biggest hedge fund debut since 2018', 'Backers included Abu Dhabi Investment Authority, Goldman Sachs, UBS, Morgan Stanley and HSBC; trading began 1 July 2024.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2024-06-24/jain-raises-5-3-billion-in-biggest-hedge-fund-debut-since-2018', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
