-- data_115_of_120.sql: intelligence dataset 2026-09-29, part 115 of 120. Run in order; safe to re-run.

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:all:aum:q4-2025:hfr:global-hedge-fund-industry-capital-end-o', 'hedge_funds', null, 'aum', 'Global hedge fund industry capital, end of 2025', 5160000000000, 'USD', 'Q4 2025', 'Global', 'HFR', null, 'https://www.hfr.com/media/market-commentary/hedge-fund-launches-accelerate-into-2026-on-record-hfri-performance-capital-growth/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:all:index_return:2025:hfr:hfri-fund-weighted-composite-index-2025-', 'hedge_funds', null, 'index_return', 'HFRI Fund Weighted Composite Index, 2025 (strongest calendar year since 2009)', 12.5, 'pct', '2025', 'Global', 'HFR', null, 'https://www.hfr.com/media/market-commentary/hedge-fund-launches-accelerate-into-2026-on-record-hfri-performance-capital-growth/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:hf_equity:index_return:2025:hfr:hfri-equity-hedge-total-index-2025', 'hedge_funds', 'hf_equity', 'index_return', 'HFRI Equity Hedge (Total) Index, 2025', 17.1, 'pct', '2025', 'Global', 'HFR', null, 'https://www.hfr.com/media/market-commentary/hedge-fund-launches-accelerate-into-2026-on-record-hfri-performance-capital-growth/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:hf_credit:index_return:2025:hfr:hfri-event-driven-total-index-2025', 'hedge_funds', 'hf_credit', 'index_return', 'HFRI Event-Driven (Total) Index, 2025', 10.9, 'pct', '2025', 'Global', 'HFR', null, 'https://www.hfr.com/media/market-commentary/hedge-fund-launches-accelerate-into-2026-on-record-hfri-performance-capital-growth/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:all:fund_count:q1-2026:hfr:new-hedge-fund-launches-q1-2026-136-in-t', 'hedge_funds', null, 'fund_count', 'New hedge fund launches, Q1 2026 (136 in the prior quarter; highest since 2022)', 166, 'count', 'Q1 2026', 'Global', 'HFR', null, 'https://www.hedgeweek.com/hedge-fund-launches-and-closures-both-climb-in-volatile-start-to-2026-hfr-says/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('sports:all:other:2024-25:deloitte:deloitte-football-money-league-2026-comb', 'sports', null, 'other', 'Deloitte Football Money League 2026: combined revenue of the top 20 clubs, 2024/25 (up 11%)', 12400000000, 'EUR', '2024/25', 'Europe', 'Deloitte', null, 'https://www.deloitte.com/uk/en/services/consulting-financial/analysis/deloitte-football-money-league.html', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('sports:all:other:2026:forbes:forbes-average-value-of-the-30-most-valu', 'sports', null, 'other', 'Forbes: average value of the 30 most valuable soccer teams, 2026 (up 21%)', 2900000000, 'USD', '2026', 'Global', 'Forbes', '2026-05-29', 'https://www.forbes.com/sites/justinteitelbaum/2026/05/29/the-worlds-most-valuable-soccer-teams-2026/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.portfolio_companies (gp_company_id, external_key, name, domain, description, sector, hq, status, invested_year, exit_year, fund_name, source, source_url)
  select (select id from public.companies where lower(name) = lower('Thoma Bravo') limit 1), (select id from public.companies where lower(name) = lower('Thoma Bravo') limit 1) || ':' || 'dayforce', 'Dayforce', null, 'Take-private at $12.3bn.', 'Software', null, 'current', null, null, null, 'web_research', 'https://www.thomabravo.com/portfolio'
  where (select id from public.companies where lower(name) = lower('Thoma Bravo') limit 1) is not null
  on conflict (external_key) do update set name = excluded.name, domain = excluded.domain, description = excluded.description, sector = excluded.sector, hq = excluded.hq, status = excluded.status, invested_year = excluded.invested_year, exit_year = excluded.exit_year, fund_name = excluded.fund_name, source_url = excluded.source_url;
