-- data_098_of_120.sql: intelligence dataset 2026-09-29, part 98 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:apollo-s3-equity-and-hybrid-solutions-fund-i:apollo:2025-05-01', '2025-05-01', null, 'fund_close', 'secondaries', null, 'Apollo S3 Equity and Hybrid Solutions Fund I', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Apollo S3 Equity and Hybrid Solutions Fund I') limit 1), 'Apollo', 'private_equity', (select id from public.companies where lower(name) = lower('Apollo') limit 1), (select id from public.sports_investors where lower(name) = lower('Apollo') limit 1), null, null, 5400000000, 'USD', null, null, 'Apollo closes debut secondaries fund at $5.4bn, above target', 'Flagship equity secondaries drawdown fund of the S3 platform; platform capital near $10bn since 2022.', 'GlobeNewswire', 'https://www.globenewswire.com/news-release/2025/05/01/3072318/0/en/Apollo-Closes-its-Debut-Secondaries-Fund-at-5-4-Billion-Exceeding-Target.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:ardian-secondary-fund-ix:ardian:2025-01-16', '2025-01-16', null, 'fund_close', 'secondaries', null, 'Ardian Secondary Fund IX', 'fund', 'France', null, (select id from public.companies where lower(name) = lower('Ardian Secondary Fund IX') limit 1), 'Ardian', 'private_equity', (select id from public.companies where lower(name) = lower('Ardian') limit 1), (select id from public.sports_investors where lower(name) = lower('Ardian') limit 1), null, null, 30000000000, 'USD', null, null, 'Ardian closes ASF IX at its $30bn hard cap, a record for secondaries', '465 investors across 44 countries including a $4bn commitment from ADIA; 22% from private wealth.', 'Alternatives Watch', 'https://www.alternativeswatch.com/2025/01/16/ardian-raises-record-30-billion-secondary-fund-ix-private-equity-platform/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:dover-street-xi:harbourvest-partners:2024-08-16', '2024-08-16', null, 'fund_close', 'secondaries', null, 'Dover Street XI', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Dover Street XI') limit 1), 'HarbourVest Partners', 'private_equity', (select id from public.companies where lower(name) = lower('HarbourVest Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('HarbourVest Partners') limit 1), null, null, 15100000000, 'USD', null, null, 'HarbourVest closes Dover Street XI at $15.1bn, $18.5bn with Secondary Overflow Fund V', 'Oversubscribed at its hard cap; 40–60 investments of $200–400m expected.', 'Business Wire', 'https://www.businesswire.com/news/home/20240816931847/en', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
