-- data_085_of_120.sql: intelligence dataset 2026-09-29, part 85 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:wwex-group-and-auctane:blackstone-and-ares-33-lenders:2026-03-05', '2026-03-05', null, 'debt_financing', 'private_credit', null, 'WWEX Group and Auctane', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('WWEX Group and Auctane') limit 1), 'Blackstone and Ares (33 lenders)', 'private_credit', (select id from public.companies where lower(name) = lower('Blackstone and Ares (33 lenders)') limit 1), (select id from public.sports_investors where lower(name) = lower('Blackstone and Ares (33 lenders)') limit 1), null, null, 5000000000, 'USD', 11600000000, 'USD', 'Blackstone and Ares lead $5bn private credit financing for Thoma Bravo''s WWEX–Auctane merger', '$4.8bn covenant-lite unitranche plus a revolver at 5.75 points over the benchmark; Blackstone the largest lender, Ares agent; 33 lenders including 26North, Blue Owl, HPS, Oaktree and Goldman Sachs.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-03-05/blackstone-ares-provide-5-billion-for-thoma-bravo-wwex-buyout', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:covetrus:blue-owl-capital:2026-01-16', '2026-01-16', null, 'debt_financing', 'private_credit', null, 'Covetrus', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Covetrus') limit 1), 'Blue Owl Capital', 'private_credit', (select id from public.companies where lower(name) = lower('Blue Owl Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Blue Owl Capital') limit 1), null, null, 2500000000, 'USD', null, null, 'CD&R and TPG look to Blue Owl for at least $2.5bn of Covetrus debt', 'Talks to refinance about $2bn of existing debt and fund a potential acquisition of Cencora''s veterinary division; pricing indicated at 500bp+ over the benchmark.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-01-16/cd-r-tpg-look-to-blue-owl-to-finance-2-5-billion-covetrus-debt', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:kkr-global-infrastructure-investors-v:kkr:2026-08-03', '2026-08-03', null, 'fund_close', 'infrastructure', null, 'KKR Global Infrastructure Investors V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('KKR Global Infrastructure Investors V') limit 1), 'KKR', 'private_equity', (select id from public.companies where lower(name) = lower('KKR') limit 1), (select id from public.sports_investors where lower(name) = lower('KKR') limit 1), null, null, 19200000000, 'USD', null, null, 'KKR closes Global Infrastructure Investors V at $19.2bn, its largest infrastructure fund', 'Core+ fund for critical infrastructure primarily in North America and Western Europe.', 'Business Wire', 'https://www.businesswire.com/news/home/20260803095185/en/KKR-Closes-$19.2-Billion-Infrastructure-Fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
