-- data_069_of_120.sql: intelligence dataset 2026-09-29, part 69 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:777-partners:2024-06-01', '2024-06-01', null, 'other', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, '777 Partners', 'private_equity', (select id from public.companies where lower(name) = lower('777 Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('777 Partners') limit 1), 'Farhad Moshiri', 94.1, null, null, null, null, '777 Partners takeover collapses after missed deadline', '777 missed the 31 May 2024 deadline to complete, having failed to repay the £158m MSP Sports Capital loan and to satisfy Premier League conditions. Everton began seeking a new buyer.', 'Malay Mail', 'https://malaymail.com/news/sports/2024/06/01/everton-takeover-by-us-private-equity-firm-falls-through/137613', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:the-friedkin-group:september-2024', null, 'September 2024', 'acquisition', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'The Friedkin Group', 'corporate', (select id from public.companies where lower(name) = lower('The Friedkin Group') limit 1), (select id from public.sports_investors where lower(name) = lower('The Friedkin Group') limit 1), 'Farhad Moshiri', null, null, null, null, null, 'Friedkin Group agrees to buy Moshiri''s majority stake', 'The Friedkin Group and Farhad Moshiri agreed a deal for Moshiri''s majority stake, subject to Premier League, FA, WPLL and FCA approval. The buyer was to assume £150m owed to Rights and Media Funding and about £200m owed to 777 Partners.', 'ESPN', 'https://www.espn.com/soccer/story/_/id/41397704/friedkin-group-farhad-moshiri-agree-deal', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:the-friedkin-group:2024-12-19', '2024-12-19', null, 'acquisition', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'The Friedkin Group', 'corporate', (select id from public.companies where lower(name) = lower('The Friedkin Group') limit 1), (select id from public.sports_investors where lower(name) = lower('The Friedkin Group') limit 1), 'Farhad Moshiri', 98.8, 400000000, 'GBP', null, null, 'Friedkin Group completes Everton takeover with 98.8% stake', 'Regulatory approvals granted; The Friedkin Group took a 98.8% stake in a deal reported as worth in excess of £400m, making Everton the 10th English top-flight club under majority American ownership.', 'ESPN / Sky Sports', 'https://www.espn.com/soccer/story/_/id/42952286/everton-get-us-owners-friedkin-group-takeover-completed', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
