-- data_092_of_120.sql: intelligence dataset 2026-09-29, part 92 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:25-property-us-logistics-portfolio-4-3-million-sq-ft:eqt-real-estate:2026-03-05', '2026-03-05', null, 'acquisition', 'real_estate', null, '25-property US logistics portfolio (4.3 million sq ft)', 'asset', 'United States', null, null, 'EQT Real Estate', 'private_equity', (select id from public.companies where lower(name) = lower('EQT Real Estate') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT Real Estate') limit 1), 'Mapletree Investments', null, null, null, null, null, 'EQT Real Estate acquires 25 logistics properties across major US distribution corridors from Mapletree', '4.3 million sq ft; price not disclosed.', 'EQT', 'https://eqtgroup.com/news/eqt-real-estate-acquires-portfolio-of-25-logistics-properties-across-major-us-distribution-corridors-from-mapletree-2026-03-05', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:2-million-sq-ft-southern-new-jersey-infill-logistics-portfolio-9-buildings:eqt-real-estate:march-2026', null, 'March 2026', 'acquisition', 'real_estate', null, '2 million sq ft Southern New Jersey infill logistics portfolio (9 buildings)', 'asset', 'United States', null, null, 'EQT Real Estate', 'private_equity', (select id from public.companies where lower(name) = lower('EQT Real Estate') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT Real Estate') limit 1), null, null, null, null, null, null, 'EQT Real Estate acquires nine-building, 2m sq ft infill logistics portfolio in Southern New Jersey', 'Price not disclosed.', 'PR Newswire', 'https://www.prnewswire.com/news-releases/eqt-real-estate-acquires-2-million-square-foot-infill-logistics-portfolio-in-southern-new-jersey-302722018.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:38-property-5-9-million-sq-ft-us-industrial-portfolio:pccp-and-stonemont-financial-group:2026-07-30', '2026-07-30', null, 'acquisition', 'real_estate', null, '38-property, 5.9 million sq ft US industrial portfolio', 'asset', 'United States', null, null, 'PCCP and Stonemont Financial Group', 'private_equity', (select id from public.companies where lower(name) = lower('PCCP and Stonemont Financial Group') limit 1), (select id from public.sports_investors where lower(name) = lower('PCCP and Stonemont Financial Group') limit 1), 'Blackstone', null, 1000000000, 'USD', null, null, 'PCCP and Stonemont buy 5.9m sq ft industrial portfolio from Blackstone for upwards of $1bn', '38 properties across 14 markets in 10 states including Denver, Dallas, Atlanta, Charlotte and El Paso.', 'The Real Deal', 'https://therealdeal.com/national/2026/07/30/blackstone-sells-6m-sf-industrial-portfolio-for-1b/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
