-- data_095_of_120.sql: intelligence dataset 2026-09-29, part 95 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:anthropic:gic-and-coatue-leads:2026-02-12', '2026-02-12', null, 'minority_investment', 'venture_capital', null, 'Anthropic', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Anthropic') limit 1), 'GIC and Coatue (leads)', 'institutional', (select id from public.companies where lower(name) = lower('GIC and Coatue (leads)') limit 1), (select id from public.sports_investors where lower(name) = lower('GIC and Coatue (leads)') limit 1), null, null, 30000000000, 'USD', 380000000000, 'USD', 'Anthropic raises $30bn Series G at a $380bn post-money valuation', 'Led by GIC and Coatue, co-led by D. E. Shaw Ventures, Dragoneer, Founders Fund, ICONIQ and MGX, with BlackRock-affiliated funds, Fidelity, General Catalyst, Sequoia, Temasek and TPG.', 'Anthropic', 'https://www.anthropic.com/news/anthropic-raises-30-billion-series-g-funding-380-billion-post-money-valuation', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:anthropic:altimeter-dragoneer-greenoaks-sequoia-capital-group-coatue-and-d1-co-leads:2026-05-28', '2026-05-28', null, 'minority_investment', 'venture_capital', null, 'Anthropic', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Anthropic') limit 1), 'Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)', 'institutional', (select id from public.companies where lower(name) = lower('Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)') limit 1), (select id from public.sports_investors where lower(name) = lower('Altimeter, Dragoneer, Greenoaks, Sequoia, Capital Group, Coatue and D1 (co-leads)') limit 1), null, null, 65000000000, 'USD', 965000000000, 'USD', 'Anthropic closes $65bn Series H at a $965bn post-money valuation', 'Co-led by Altimeter Capital, Dragoneer, Greenoaks, Sequoia Capital, Capital Group, Coatue, D1 Capital Partners and others.', 'Anthropic', 'https://www.anthropic.com/news/series-h', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:cvc-secondary-opportunities-fund-vi:cvc-secondary-partners:2026-09-03', '2026-09-03', null, 'fund_close', 'secondaries', null, 'CVC Secondary Opportunities Fund VI', 'fund', 'Luxembourg', null, (select id from public.companies where lower(name) = lower('CVC Secondary Opportunities Fund VI') limit 1), 'CVC Secondary Partners', 'private_equity', (select id from public.companies where lower(name) = lower('CVC Secondary Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('CVC Secondary Partners') limit 1), null, null, 10000000000, 'USD', null, null, 'CVC Secondary Partners closes SOF VI with $10bn, its largest secondaries fund', 'Predecessors raised $5.8bn in 2023 and $2.7bn in 2019.', 'CVC', 'https://www.cvc.com/media/news/2026/cvc-secondary-partners-raises-10-billion-for-its-sixth-global-secondary-private-equity-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
