-- data_070_of_120.sql: intelligence dataset 2026-09-29, part 70 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:the-friedkin-group:january-2025', null, 'January 2025', 'other', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'The Friedkin Group', 'corporate', (select id from public.companies where lower(name) = lower('The Friedkin Group') limit 1), (select id from public.sports_investors where lower(name) = lower('The Friedkin Group') limit 1), null, null, 233440000, 'GBP', null, null, 'Friedkin restructures Everton balance sheet with £233.44m share issue and loan-to-equity conversion', 'Filings showed shares issued for £233.44m to fund working capital and repay Rights and Media Funding and 777/A-Cap loans, with the £451m Moshiri shareholder loan converted into equity.', 'The Esk', 'https://theesk.org/2025/01/09/details-of-the-friedkin-financial-restructuring-of-everton-emerge/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:jpmorgan-chase:2025-01-07', '2025-01-07', null, 'debt_financing', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'JPMorgan Chase', 'institutional', (select id from public.companies where lower(name) = lower('JPMorgan Chase') limit 1), (select id from public.sports_investors where lower(name) = lower('JPMorgan Chase') limit 1), null, null, 130000000, 'GBP', null, null, 'JPMorgan provides £130m loan to Friedkin Group for Everton and sounds out £300m+ stadium refinancing', 'Bloomberg reported JPMorgan was lending £130m to The Friedkin Group for the club and approaching institutional investors to raise more than £300m of debt to refinance the stadium.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2025-01-07/jpmorgan-sounds-out-investors-for-everton-fc-stadium-financing', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:consortium-of-institutional-lenders-placement-agent-jpmorgan-securities:2025-03-26', '2025-03-26', null, 'stadium_financing', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'Consortium of institutional lenders (placement agent JPMorgan Securities)', 'consortium', (select id from public.companies where lower(name) = lower('Consortium of institutional lenders (placement agent JPMorgan Securities)') limit 1), (select id from public.sports_investors where lower(name) = lower('Consortium of institutional lenders (placement agent JPMorgan Securities)') limit 1), null, null, 350000000, 'GBP', null, null, 'Everton refinances stadium debt with £350m senior secured notes', 'A private placement of £350m senior secured notes, co-issued by two club subsidiaries and secured against the new stadium, refinanced Rights and Media Funding borrowings. The club said the offering was oversubscribed multiple times.', 'ESPN / Inside World Football', 'https://www.espn.com/soccer/story/_/id/44134148/everton-secure-350-million-financing-deal-new-stadium', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
