-- data_079_of_120.sql: intelligence dataset 2026-09-29, part 79 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:emerald-holding:apollo:2026-05-11', '2026-05-11', null, 'company_acquisition', 'private_equity', null, 'Emerald Holding', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Emerald Holding') limit 1), 'Apollo', 'private_equity', (select id from public.companies where lower(name) = lower('Apollo') limit 1), (select id from public.sports_investors where lower(name) = lower('Apollo') limit 1), null, null, null, null, 1500000000, 'USD', 'Apollo funds to take Emerald private at a $1.5bn enterprise value and combine it with Questex', '$5.03 a share in cash, a 42.1% premium; closing expected in the second half of 2026.', 'Apollo Global Management', 'https://ir.apollo.com/news-events/press-releases/detail/624/apollo-funds-to-acquire-emerald-and-questex-to-create', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:easyjet:apollo:2026-08-06', '2026-08-06', null, 'company_acquisition', 'private_equity', null, 'easyJet', 'company', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('easyJet') limit 1), 'Apollo', 'private_equity', (select id from public.companies where lower(name) = lower('Apollo') limit 1), (select id from public.sports_investors where lower(name) = lower('Apollo') limit 1), null, null, null, null, 5700000000, 'GBP', 'easyJet board recommends £5.7bn takeover by Apollo funds after Castlelake withdraws', '£7.15 a share in cash; founder Stelios Haji-Ioannou''s holdings (about 15.3%) support the deal; completion expected by the end of Q1 2027.', 'easyJet', 'https://www.easyjet.com/en/news/airline/article/acquisition-of-easyjet-updates', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:intertek-group:eqt-with-adia-and-mubadala:2026-06-18', '2026-06-18', null, 'company_acquisition', 'private_equity', null, 'Intertek Group', 'company', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('Intertek Group') limit 1), 'EQT (with ADIA and Mubadala)', 'private_equity', (select id from public.companies where lower(name) = lower('EQT (with ADIA and Mubadala)') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT (with ADIA and Mubadala)') limit 1), null, null, null, null, 10900000000, 'GBP', 'EQT-led consortium agrees £10.9bn take-private of Intertek', '£60 a share in cash plus the final dividend; ADIA co-invests £1.0bn for 16% and Mubadala £0.5bn for 8%; expected effective late 2026 or early 2027.', 'Intertek (Rule 2.7 announcement)', 'https://www.intertek.com/siteassets/investors/offer/rule-2.7-announcement-dated-18-june-2026.pdf', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
