-- data_094_of_120.sql: intelligence dataset 2026-09-29, part 94 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:lightspeed-2025-funds-fund-xv-a-xv-b-select-vi-opportunity-iii-co-investment-i:lightspeed-venture-partners:2025-12-15', '2025-12-15', null, 'fund_close', 'venture_capital', null, 'Lightspeed 2025 funds (Fund XV-A, XV-B, Select VI, Opportunity III, Co-Investment I)', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Lightspeed 2025 funds (Fund XV-A, XV-B, Select VI, Opportunity III, Co-Investment I)') limit 1), 'Lightspeed Venture Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Lightspeed Venture Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Lightspeed Venture Partners') limit 1), null, null, 9000000000, 'USD', null, null, 'Lightspeed closes over $9bn across six vehicles, its largest fundraise', 'Fund XV-A $980m, XV-B $1.2bn, Select VI $1.8bn, Opportunity Fund III $3.3bn, Co-Investment Fund I $600m, plus $1.25bn in single-investor vehicles.', 'Business Wire', 'https://www.businesswire.com/news/home/20251215319417/en/Lightspeed-Closes-Over-$9B-in-New-Funds-Aimed-at-Backing-Category-Definers-Worldwide', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:sequoia-capital-early-stage-funds-750m-series-a-fund-and-200m-seed-fund:sequoia-capital:2025-10-27', '2025-10-27', null, 'fund_close', 'venture_capital', null, 'Sequoia Capital early-stage funds ($750m Series A fund and $200m seed fund)', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Sequoia Capital early-stage funds ($750m Series A fund and $200m seed fund)') limit 1), 'Sequoia Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Sequoia Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Sequoia Capital') limit 1), null, null, 950000000, 'USD', null, null, 'Sequoia unveils $950m in new early-stage funds', 'A $750m Series A fund and a $200m seed fund.', 'TechCrunch', 'https://techcrunch.com/2025/10/27/sequoia-unveils-950m-in-new-early-stage-funds-as-it-strives-to-be-only-as-good-as-our-next-investment/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:general-catalyst-fund-xii:general-catalyst:2024-10-24', '2024-10-24', null, 'fund_close', 'venture_capital', null, 'General Catalyst Fund XII', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('General Catalyst Fund XII') limit 1), 'General Catalyst', 'private_equity', (select id from public.companies where lower(name) = lower('General Catalyst') limit 1), (select id from public.sports_investors where lower(name) = lower('General Catalyst') limit 1), null, null, 8000000000, 'USD', null, null, 'General Catalyst raises $8bn, with $750m set aside for health care', '$4.5bn for seed and growth funds, $1.5bn for company creation and $2bn of separately managed accounts.', 'TechCrunch', 'https://techcrunch.com/2024/10/24/general-catalyst-raises-8b-in-fresh-funds-to-back-startups-globally', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
