-- data_111_of_120.sql: intelligence dataset 2026-09-29, part 111 of 120. Run in order; safe to re-run.

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:all:default_rate:end-2026-forecast:fitch-ratings:fitch-forecast-us-leveraged-loan-default', 'private_credit', null, 'default_rate', 'Fitch forecast: US leveraged loan default rate by end of 2026 (range 4.5–5%)', 4.5, 'pct', 'end 2026 (forecast)', 'US', 'Fitch Ratings', null, 'https://www.investmentexecutive.com/news/research-and-markets/u-s-leveraged-loan-defaults-to-ease-in-2026-fitch/', 'Range 4.5% to 5%; high yield 2.5% to 3%.', 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:all:default_rate:sep-2026:pitchbook-lcd:pitchbook-lcd-default-predictor-rolling-', 'private_credit', null, 'default_rate', 'PitchBook LCD Default Predictor: rolling 12-month leveraged loan default rate by issuer count, 30 Sep 2026 (estimate)', 1.48, 'pct', 'Sep 2026', 'US', 'PitchBook LCD', null, 'https://pitchbook.com/news/articles/introducing-default-predictor-a-six-month-view-on-leveraged-loan-defaults', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:clo_structured:deal_volume:2025:bloomberg:us-clo-new-issuance-2025-record', 'private_credit', 'clo_structured', 'deal_volume', 'US CLO new issuance, 2025 (record)', 201500000000, 'USD', '2025', 'US', 'Bloomberg', '2025-12-17', 'https://www.bloomberg.com/news/articles/2025-12-17/us-clo-sales-reach-fresh-record-in-2025-as-demand-stays-strong', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:clo_structured:deal_volume:2025:maples-group:european-clo-new-issuance-2025-record-49', 'private_credit', 'clo_structured', 'deal_volume', 'European CLO new issuance, 2025 (record; €49bn in 2024)', 60000000000, 'EUR', '2025', 'Europe', 'Maples Group', null, 'https://maples.com/knowledge/european-clo-market-2025-record-issuance-regulatory-reform-and-what-to-expect-in-2026', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_credit:clo_structured:deal_volume:2025:valuation-research-corp:us-middle-market-clo-issuance-2025-68-tr', 'private_credit', 'clo_structured', 'deal_volume', 'US middle market CLO issuance, 2025 (68 transactions, record)', 35700000000, 'USD', '2025', 'US', 'Valuation Research Corp.', null, 'https://www.valuationresearch.com/insights/structured-products-market-trends-q2-2026/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('infrastructure:all:fundraising_total:q1q3-2025:preqin:private-infrastructure-fundraising-q1q3-', 'infrastructure', null, 'fundraising_total', 'Private infrastructure fundraising, Q1–Q3 2025 (first time above $175bn)', 175000000000, 'USD', 'Q1–Q3 2025', 'Global', 'Preqin', null, 'https://www.preqin.com/insights/research/quarterly-updates/infrastructure-q4-2025-preqin-quarterly-update', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('infrastructure:all:fundraising_total:h1-2025:cbre-investment-management:private-infrastructure-fundraising-h1-20', 'infrastructure', null, 'fundraising_total', 'Private infrastructure fundraising, H1 2025', 134000000000, 'USD', 'H1 2025', 'Global', 'CBRE Investment Management', null, 'https://www.cbreim.com/insights/articles/infrastructure-quarterly-q3-2025', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;
