-- data_087_of_120.sql: intelligence dataset 2026-09-29, part 87 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:global-infrastructure-partners-v:global-infrastructure-partners:june-2025', null, 'June 2025', 'fund_close', 'infrastructure', null, 'Global Infrastructure Partners V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Global Infrastructure Partners V') limit 1), 'Global Infrastructure Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Global Infrastructure Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Global Infrastructure Partners') limit 1), null, null, 25200000000, 'USD', null, null, 'GIP closes Fund V on $25.2bn, its largest flagship', '278 institutional investors across 35 countries; above the $25bn target and Fund IV''s $22bn.', 'Pensions & Investments', 'https://www.pionline.com/alternatives-investments/pi-gip-closes-25-billion-dollar-fund-blackrock/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:eqt-infrastructure-vi:eqt:2025-03-28', '2025-03-28', null, 'fund_close', 'infrastructure', null, 'EQT Infrastructure VI', 'fund', 'Sweden', null, (select id from public.companies where lower(name) = lower('EQT Infrastructure VI') limit 1), 'EQT', 'private_equity', (select id from public.companies where lower(name) = lower('EQT') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT') limit 1), null, null, 21500000000, 'EUR', null, null, 'EQT Infrastructure VI holds final close at its €21.5bn hard cap', 'Above the €20bn target and 35% larger than Infrastructure V; about 70% from existing clients.', 'EQT', 'https://eqtgroup.com/news/eqt-infrastructure-vi-holds-final-close-at-its-hard-cap-raising-eur-215-billion-in-total-commitments-2025-03-28', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:ardian-infrastructure-fund-vi:ardian:october-2025', null, 'October 2025', 'fund_close', 'infrastructure', null, 'Ardian Infrastructure Fund VI', 'fund', 'France', null, (select id from public.companies where lower(name) = lower('Ardian Infrastructure Fund VI') limit 1), 'Ardian', 'private_equity', (select id from public.companies where lower(name) = lower('Ardian') limit 1), (select id from public.sports_investors where lower(name) = lower('Ardian') limit 1), null, null, 20000000000, 'USD', null, null, 'Ardian raises $20bn for its sixth infrastructure platform', '$13.5bn hard cap plus $6.5bn of co-investment; 229 LPs; over 40% deployed including Verne.', 'Ardian', 'https://www.ardian.com/news-insights/press-releases/ardian-raises-20bn-power-essential-european-infrastructure', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
