-- data_065_of_120.sql: intelligence dataset 2026-09-29, part 65 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:chelsea-football-club:blueco-22-midco-ltd-chelsea-s-parent-holding-company:2024-06-28', '2024-06-28', '28 June 2024', 'stake_sale', 'sports', 'football', 'Chelsea Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--chelsea'), null, 'BlueCo 22 Midco Ltd (Chelsea''s parent holding company)', 'corporate', (select id from public.companies where lower(name) = lower('BlueCo 22 Midco Ltd (Chelsea''s parent holding company)') limit 1), (select id from public.sports_investors where lower(name) = lower('BlueCo 22 Midco Ltd (Chelsea''s parent holding company)') limit 1), 'Chelsea FC Holdings Limited', 100, 198700000, 'GBP', 200000000, 'GBP', 'Chelsea sells women''s team to sister company BlueCo for £198.7m', 'Chelsea FC Holdings transferred the women''s team to BlueCo 22 Midco, a related company owned by the same ownership group, booking £198.7m from disposal of subsidiaries and a £128.4m pre-tax profit for 2023-24. The transaction helped with Premier League PSR compliance; UEFA does not recognise income from sales to sister companies.', 'ESPN', 'https://www.espn.com/soccer/story/_/id/44481589/chelsea-huge-profit-repositioning-women-team', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:chelsea-football-club:alexis-ohanian:2025-05-15', '2025-05-15', 'May 2025', 'minority_investment', 'sports', 'football', 'Chelsea Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--chelsea'), null, 'Alexis Ohanian', 'individual', (select id from public.companies where lower(name) = lower('Alexis Ohanian') limit 1), (select id from public.sports_investors where lower(name) = lower('Alexis Ohanian') limit 1), 'BlueCo', 10, 20000000, 'GBP', 200000000, 'GBP', 'Alexis Ohanian buys 10% of Chelsea Women at £200m valuation', 'Reddit co-founder Alexis Ohanian acquired a 10% stake in Chelsea FC Women for around £20m, valuing the women''s club at £200m, and joined its board.', 'SportsPro', 'https://www.sportspro.com/news/chelsea-women-alexis-ohanian-wsl-investment-stake-may-2025/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:chelsea-football-club:clearlake-capital-group:2026-09-16', '2026-09-16', '16 September 2026', 'stake_sale', 'sports', 'football', 'Chelsea Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--chelsea'), null, 'Clearlake Capital Group', 'private_equity', (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.sports_investors where lower(name) = lower('Clearlake Capital Group') limit 1), 'Todd Boehly and Mark Walter', 25.66, 950000000, 'GBP', 5000000000, 'GBP', 'Clearlake buys out Boehly and Walter for £950m, takes full control of Chelsea', 'Clearlake Capital, already holding 61.5%, acquired the roughly 12.8% stakes each of Todd Boehly and Mark Walter for a combined £950m, valuing Chelsea at £5bn including debt. Boehly stepped down as chairman; Hansjörg Wyss remains a shareholder.', 'CNBC', 'https://www.cnbc.com/2026/09/17/chelsea-mark-walter-bohely-clearlake-capital.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
