-- data_097_of_120.sql: intelligence dataset 2026-09-29, part 97 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:alpinvest-atom-fund-ii:carlyle-alpinvest:2026-07-15', '2026-07-15', null, 'fund_close', 'secondaries', null, 'AlpInvest Atom Fund II', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('AlpInvest Atom Fund II') limit 1), 'Carlyle AlpInvest', 'private_equity', (select id from public.companies where lower(name) = lower('Carlyle AlpInvest') limit 1), (select id from public.sports_investors where lower(name) = lower('Carlyle AlpInvest') limit 1), null, null, 1700000000, 'USD', null, null, 'Carlyle AlpInvest closes Atom Fund II at its $1.7bn hard cap for single-asset continuation vehicles', 'Above the $1bn target; single-asset CV capacity across the platform now $7bn.', 'Carlyle', 'https://www.carlyle.com/media-room/news-release-archive/carlyle-alpinvest-closes-alpinvest-atom-fund-ii-17-billion-hard-cap', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:coller-international-partners-ix:coller-capital:2026-01-13', '2026-01-13', null, 'fund_close', 'secondaries', null, 'Coller International Partners IX', 'fund', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('Coller International Partners IX') limit 1), 'Coller Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Coller Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Coller Capital') limit 1), null, null, 12500000000, 'USD', null, null, 'Coller closes CIP IX at its $12.5bn hard cap, $17bn across the secondaries platform', 'More than 250 investors; CIP IX over 70% deployed; AUM $50bn.', 'Alternatives Watch', 'https://www.alternativeswatch.com/2026/01/13/coller-17-billion-pe-secondaries-cip-ix-9/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:blackstone-strategic-partners-infrastructure-iv:blackstone-strategic-partners:2025-09-02', '2025-09-02', null, 'fund_close', 'secondaries', null, 'Blackstone Strategic Partners Infrastructure IV', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Blackstone Strategic Partners Infrastructure IV') limit 1), 'Blackstone Strategic Partners', 'private_equity', (select id from public.companies where lower(name) = lower('Blackstone Strategic Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('Blackstone Strategic Partners') limit 1), null, null, 5500000000, 'USD', null, null, 'Blackstone Strategic Partners closes the largest infrastructure secondaries fund ever raised at $5.5bn', 'Final close announced 2 September 2025.', 'Business Wire', 'https://www.businesswire.com/news/home/20250902790732/en/Blackstone-Strategic-Partners-Closes-Largest-Infrastructure-Secondaries-Fund-Ever-Raised-at-$5.5-Billion', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
