-- data_103_of_120.sql: intelligence dataset 2026-09-29, part 103 of 120. Run in order; safe to re-run.

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-24/hedge-fund-with-235-return-says-gold-price-decline-is-temporary', '2026-09-24', 'hedge_funds', 'performance', 'Long-short gold hedge fund with a 235% return says the gold decline is temporary', 'Raphael Lamm''s fund, up more than 200% net since launch last year.', '{}'::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any('{}'::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-24/hedge-fund-with-235-return-says-gold-price-decline-is-temporary', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('hfr.com/media/market-commentary/global-hedge-fund-industry-capital-surges-past-historic-5-trillion-milestone', null, 'hedge_funds', 'performance', 'Global hedge fund capital surges to $5.6tn in Q2 2026, a 15th consecutive quarterly rise', 'Top-decile HFRI managers returned 36.4% on average in the quarter, the bottom decile lost 8.2%.', array['HFR']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['hfr']::text[])), 'HFR', 'https://www.hfr.com/media/market-commentary/global-hedge-fund-industry-capital-surges-past-historic-5-trillion-milestone/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('bloomberg.com/news/articles/2026-09-03/cvc-raises-10-billion-for-its-largest-ever-secondaries-fund', '2026-09-03', 'secondaries', 'fund_close', 'CVC raises $10bn for its largest-ever secondaries fund', 'Secondary Opportunities Fund VI; predecessors raised $5.8bn (2023) and $2.7bn (2019).', array['CVC Secondary Partners']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['cvc secondary partners']::text[])), 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-03/cvc-raises-10-billion-for-its-largest-ever-secondaries-fund', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('pitchbook.com/news/articles/continuation-funds-drive-record-h1-for-secondary-market', null, 'secondaries', 'performance', 'Continuation funds drive a record first half for the secondary market: volume above $120bn, GP-led about $65bn', 'GP-led volume up 35% year on year and 54% of activity in H1 2026, overtaking LP-led for the first time since 2021.', '{}'::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any('{}'::text[])), 'PitchBook', 'https://pitchbook.com/news/articles/continuation-funds-drive-record-h1-for-secondary-market', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('sportspro.com/news/finance-investment/serie-a-international-media-rights-private-equity-investment-apollo-ares-cvc-april-2026', null, 'sports', 'news', 'Serie A sounds out private equity for a stake in its international media rights business', 'Interest gauged from investors including Apollo, Ares and CVC, SportsPro reports.', array['Serie A', 'Apollo', 'Ares Management', 'CVC Capital Partners']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['serie a', 'apollo', 'ares management', 'cvc capital partners']::text[])), 'SportsPro', 'https://www.sportspro.com/news/finance-investment/serie-a-international-media-rights-private-equity-investment-apollo-ares-cvc-april-2026/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.signals (external_key, date, asset_class, kind, headline, summary, entities, company_ids, source_name, source_url, source)
  values ('footballbenchmark.com/w/private-equity-s-expanding-footprint-in-football-risks-rewards-and-the-future', null, 'sports', 'performance', 'Real Madrid reaches a record €7.7bn enterprise value in Football Benchmark''s 2026 club valuation ranking', 'Multi-club owners hold stakes in nearly 48% of Big Five clubs in 2025-26, up from 41.7%.', array['Real Madrid']::text[], (select coalesce(array_agg(id), '{}'::uuid[]) from public.companies where lower(name) = any(array['real madrid']::text[])), 'Football Benchmark', 'https://footballbenchmark.com/w/private-equity-s-expanding-footprint-in-football-risks-rewards-and-the-future', 'web_research')
  on conflict (external_key) do update set date = excluded.date, asset_class = excluded.asset_class, kind = excluded.kind, headline = excluded.headline, summary = excluded.summary, entities = excluded.entities, company_ids = excluded.company_ids, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
