-- data_080_of_120.sql: intelligence dataset 2026-09-29, part 80 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:intertek-group:eqt-with-adia-and-mubadala:2026-06-18', '2026-06-18', null, 'company_acquisition', 'private_equity', null, 'Intertek Group', 'company', 'United Kingdom', null, (select id from public.companies where lower(name) = lower('Intertek Group') limit 1), 'EQT (with ADIA and Mubadala)', 'private_equity', (select id from public.companies where lower(name) = lower('EQT (with ADIA and Mubadala)') limit 1), (select id from public.sports_investors where lower(name) = lower('EQT (with ADIA and Mubadala)') limit 1), null, null, null, null, 10900000000, 'GBP', 'EQT-led consortium agrees £10.9bn take-private of Intertek', '£60 a share in cash plus the final dividend; ADIA co-invests £1.0bn for 16% and Mubadala £0.5bn for 8%; expected effective late 2026 or early 2027.', 'Intertek (Rule 2.7 announcement)', 'https://www.intertek.com/siteassets/investors/offer/rule-2.7-announcement-dated-18-june-2026.pdf', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:mai-capital-management:carlyle:2026-06-04', '2026-06-04', null, 'company_acquisition', 'private_equity', null, 'MAI Capital Management', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('MAI Capital Management') limit 1), 'Carlyle', 'private_equity', (select id from public.companies where lower(name) = lower('Carlyle') limit 1), (select id from public.sports_investors where lower(name) = lower('Carlyle') limit 1), 'Galway Holdings, Harvest Partners and Oak Hill Capital', null, null, null, 2800000000, 'USD', 'Carlyle completes acquisition of a majority stake in MAI Capital Management at a valuation above $2.8bn', 'MAI had about $77.3bn in combined client assets managed or advised as of 30 April 2026.', 'Business Wire', 'https://www.businesswire.com/news/home/20260608981780/en/Carlyle-Completes-Acquisition-of-Majority-Stake-in-MAI-Capital-Management', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:champions-group:blackstone:2026-02-17', '2026-02-17', null, 'company_acquisition', 'private_equity', null, 'Champions Group', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Champions Group') limit 1), 'Blackstone', 'private_equity', (select id from public.companies where lower(name) = lower('Blackstone') limit 1), (select id from public.sports_investors where lower(name) = lower('Blackstone') limit 1), 'Odyssey Investment Partners', null, null, null, null, null, 'Blackstone agrees to acquire home services provider Champions Group from Odyssey', 'Definitive agreement announced 17 February 2026; terms not disclosed in the release.', 'Blackstone', 'https://www.blackstone.com/news/press/blackstone-announces-agreement-to-acquire-champions-group/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
