-- data_068_of_120.sql: intelligence dataset 2026-09-29, part 68 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:farhad-moshiri:february-2016', null, 'February 2016', 'acquisition', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'Farhad Moshiri', 'individual', (select id from public.companies where lower(name) = lower('Farhad Moshiri') limit 1), (select id from public.sports_investors where lower(name) = lower('Farhad Moshiri') limit 1), null, 49.9, 270000000, 'USD', null, null, 'Farhad Moshiri buys 49.9% of Everton', 'Moshiri acquired an initial 49.9% shareholding in Everton in February 2016, reported at $270m.', 'Front Office Sports', 'https://frontofficesports.com/everton-owner-invests-135m-in-club-increases-stake/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:farhad-moshiri:september-2018', null, 'September 2018', 'stake_sale', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'Farhad Moshiri', 'individual', (select id from public.companies where lower(name) = lower('Farhad Moshiri') limit 1), (select id from public.sports_investors where lower(name) = lower('Farhad Moshiri') limit 1), null, 68.6, null, null, null, null, 'Moshiri raises Everton stake to 68.6%, on course for 77.2%', 'In September 2018 Moshiri increased his shareholding from 49.9% to 68.6% and said he expected it to reach 77.2% by July 2019.', 'Sky Sports', 'https://www.skysports.com/football/news/11671/11736100/farhad-moshiri-increases-everton-ownership-to-77-2-per-cent', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:everton-football-club:msp-sports-capital-andy-bell-george-downing:may-2023', null, 'May 2023', 'stadium_financing', 'sports', 'football', 'Everton Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--everton'), null, 'MSP Sports Capital, Andy Bell, George Downing', 'consortium', (select id from public.companies where lower(name) = lower('MSP Sports Capital, Andy Bell, George Downing') limit 1), (select id from public.sports_investors where lower(name) = lower('MSP Sports Capital, Andy Bell, George Downing') limit 1), null, null, 158000000, 'GBP', null, null, 'MSP Sports Capital-led group lends £158m for Bramley-Moore Dock stadium', 'At the end of May 2023 MSP Sports Capital, with local businessmen Andy Bell and George Downing, provided a loan that grew to £158m, mostly for stadium construction payments. The loan was repaid by The Friedkin Group during its 2024 takeover negotiations.', 'The Esk', 'https://theesk.org/2024/03/30/moshiri-is-about-to-lose-control-of-everton-the-question-is-to-whom/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
