-- data_096_of_120.sql: intelligence dataset 2026-09-29, part 96 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:cvc-secondary-opportunities-fund-vi:cvc-secondary-partners:2026-09-03', '2026-09-03', null, 'fund_close', 'secondaries', null, 'CVC Secondary Opportunities Fund VI', 'fund', 'Luxembourg', null, (select id from public.companies where lower(name) = lower('CVC Secondary Opportunities Fund VI') limit 1), 'CVC Secondary Partners', 'private_equity', (select id from public.companies where lower(name) = lower('CVC Secondary Partners') limit 1), (select id from public.sports_investors where lower(name) = lower('CVC Secondary Partners') limit 1), null, null, 10000000000, 'USD', null, null, 'CVC Secondary Partners closes SOF VI with $10bn, its largest secondaries fund', 'Predecessors raised $5.8bn in 2023 and $2.7bn in 2019.', 'CVC', 'https://www.cvc.com/media/news/2026/cvc-secondary-partners-raises-10-billion-for-its-sixth-global-secondary-private-equity-fund/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:blue-owl-strategic-equity:blue-owl-capital:february-2026', null, 'February 2026', 'fund_close', 'secondaries', null, 'Blue Owl Strategic Equity', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Blue Owl Strategic Equity') limit 1), 'Blue Owl Capital', 'private_equity', (select id from public.companies where lower(name) = lower('Blue Owl Capital') limit 1), (select id from public.sports_investors where lower(name) = lower('Blue Owl Capital') limit 1), null, null, 3000000000, 'USD', null, null, 'Blue Owl closes inaugural strategic equity secondaries strategy with over $3bn', 'Raised across institutional and private wealth channels.', 'Blue Owl Capital', 'https://www.blueowl.com/news/blue-owl-capital-closes-inaugural-strategic-equity-secondaries-strategy-over-3-billion-raised', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:pa-secondary-fund-v:future-standard:june-2026', null, 'June 2026', 'fund_close', 'secondaries', null, 'PA Secondary Fund V', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('PA Secondary Fund V') limit 1), 'Future Standard', 'private_equity', (select id from public.companies where lower(name) = lower('Future Standard') limit 1), (select id from public.sports_investors where lower(name) = lower('Future Standard') limit 1), null, null, 3000000000, 'USD', null, null, 'Future Standard closes PA Secondary Fund V with about $3bn, its largest private fund', 'Final close of PASF V.', 'PR Newswire', 'https://www.prnewswire.com/news-releases/future-standard-closes-firms-largest-private-fund-to-date-with-approximately-3-billion-in-commitments-302794070.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
