-- data_058_of_120.sql: intelligence dataset 2026-09-29, part 58 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:arsenal-football-club:kroenke-sports-entertainment:2024-25-accounts-reported-march-2025', null, '2024-25 accounts (reported March 2025)', 'debt_financing', 'sports', 'football', 'Arsenal Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--arsenal'), null, 'Kroenke Sports & Entertainment', 'individual', (select id from public.companies where lower(name) = lower('Kroenke Sports & Entertainment') limit 1), (select id from public.sports_investors where lower(name) = lower('Kroenke Sports & Entertainment') limit 1), null, null, 324100000, 'GBP', null, null, 'Arsenal owes £324.1m in low-interest loans to KSE', 'Owner loans from KSE, accumulated since 2020-21 and described as low-interest rather than interest-free, stood at £324.1m per the club''s accounts.', 'ArsenalNews.co.uk', 'https://arsenalnews.co.uk/2025/03/20/arsenal-now-owe-324-1million-to-owners-kroenke-sports-entertainment/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:aston-villa-football-club:nswe-nassef-sawiris-and-wes-edens:2018-07-20', '2018-07-20', 'July 2018', 'acquisition', 'sports', 'football', 'Aston Villa Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--aston-villa'), null, 'NSWE (Nassef Sawiris and Wes Edens)', 'consortium', (select id from public.companies where lower(name) = lower('NSWE (Nassef Sawiris and Wes Edens)') limit 1), (select id from public.sports_investors where lower(name) = lower('NSWE (Nassef Sawiris and Wes Edens)') limit 1), 'Tony Xia (Recon Group)', 55, 30000000, 'GBP', null, null, 'Sawiris and Edens buy 55% controlling stake in Aston Villa for about £30m', 'Egyptian billionaire Nassef Sawiris and Fortress co-founder Wes Edens, through NSWE, acquired a 55% stake in Championship club Aston Villa for about £30m ($39m). Previous owner Tony Xia stayed as co-chairman. The club had faced cash-flow problems and a potential HMRC winding-up order over an unpaid £4m tax bill.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2018-07-20/billionaire-sawiris-wes-edens-to-buy-aston-villa-club-stake', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:aston-villa-football-club:nswe-nassef-sawiris-and-wes-edens:august-2019', null, 'August 2019', 'acquisition', 'sports', 'football', 'Aston Villa Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--aston-villa'), null, 'NSWE (Nassef Sawiris and Wes Edens)', 'consortium', (select id from public.companies where lower(name) = lower('NSWE (Nassef Sawiris and Wes Edens)') limit 1), (select id from public.sports_investors where lower(name) = lower('NSWE (Nassef Sawiris and Wes Edens)') limit 1), 'Tony Xia (Recon Group)', 45, null, null, null, null, 'Sawiris and Edens buy out Tony Xia''s remaining shares to own 100% of Aston Villa', 'Following promotion to the Premier League, NSWE increased its 55% holding to a full purchase of the club in August 2019, buying out Tony Xia''s remaining stake. Terms were not disclosed in the sources found.', 'Wikipedia (V Sports)', 'https://en.wikipedia.org/wiki/V_Sports', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
