-- data_011_of_120.sql: intelligence dataset 2026-09-29, part 11 of 120. Run in order; safe to re-run.

insert into public.sports_teams (external_key, name, short_name, sport, league, country, city, stadium, stadium_capacity, stadium_capacity_source_url, founded_year, domain, ownership_type, ownership_summary, ownership_source_url, revenue, revenue_currency, revenue_season, revenue_source_name, revenue_source_url, valuation, valuation_currency, valuation_year, valuation_source_name, valuation_source_url, social_followers, social_as_of, social_source_url, social_platforms, notes, sources, verification, source)
  values ('la-liga--atletico-de-madrid', 'Atlético de Madrid', 'Atlético Madrid', 'football', 'La Liga', 'Spain', 'Madrid', 'Metropolitano', 70813, 'https://en.wikipedia.org/wiki/List_of_football_stadiums_in_Spain', null, null, null, null, null, 454500000, 'EUR', '2024/25', 'Deloitte Football Money League 2026', 'https://www.goal.com/en/news/deloitte-football-money-league-2026/bltedf9c4b411ec7212', 1700000000, 'USD', 2025, 'Forbes (2025 list, via SI)', 'https://www.si.com/soccer/30-most-valuable-soccer-teams-2026-ranked', null, null, null, '[]'::jsonb, null, '["https://en.wikipedia.org/wiki/List_of_football_stadiums_in_Spain", "https://www.goal.com/en/news/deloitte-football-money-league-2026/bltedf9c4b411ec7212", "https://www.si.com/soccer/30-most-valuable-soccer-teams-2026-ranked"]'::jsonb, '[]'::jsonb, 'web_research')
  on conflict (external_key) do update set name = excluded.name, short_name = excluded.short_name, sport = excluded.sport, league = excluded.league, country = excluded.country, city = excluded.city, stadium = excluded.stadium, stadium_capacity = excluded.stadium_capacity, stadium_capacity_source_url = excluded.stadium_capacity_source_url, founded_year = excluded.founded_year, domain = excluded.domain, ownership_type = excluded.ownership_type, ownership_summary = excluded.ownership_summary, ownership_source_url = excluded.ownership_source_url, revenue = excluded.revenue, revenue_currency = excluded.revenue_currency, revenue_season = excluded.revenue_season, revenue_source_name = excluded.revenue_source_name, revenue_source_url = excluded.revenue_source_url, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, valuation_year = excluded.valuation_year, valuation_source_name = excluded.valuation_source_name, valuation_source_url = excluded.valuation_source_url, social_followers = excluded.social_followers, social_as_of = excluded.social_as_of, social_source_url = excluded.social_source_url, social_platforms = excluded.social_platforms, notes = excluded.notes, sources = excluded.sources, verification = excluded.verification, source = excluded.source;

insert into public.sports_teams (external_key, name, short_name, sport, league, country, city, stadium, stadium_capacity, stadium_capacity_source_url, founded_year, domain, ownership_type, ownership_summary, ownership_source_url, revenue, revenue_currency, revenue_season, revenue_source_name, revenue_source_url, valuation, valuation_currency, valuation_year, valuation_source_name, valuation_source_url, social_followers, social_as_of, social_source_url, social_platforms, notes, sources, verification, source)
  values ('la-liga--fc-barcelona', 'FC Barcelona', 'Barcelona', 'football', 'La Liga', 'Spain', 'Barcelona', 'Camp Nou', 62652, 'https://en.wikipedia.org/wiki/List_of_football_stadiums_in_Spain', null, null, null, null, null, 974800000, 'EUR', '2024/25', 'Deloitte Football Money League 2026', 'https://www.goal.com/en/news/deloitte-football-money-league-2026/bltedf9c4b411ec7212', 7500000000, 'USD', 2026, 'Forbes', 'https://www.forbes.com/sites/justinteitelbaum/2026/05/29/the-worlds-most-valuable-soccer-teams-2026/', null, null, null, '[]'::jsonb, null, '["https://en.wikipedia.org/wiki/List_of_football_stadiums_in_Spain", "https://www.goal.com/en/news/deloitte-football-money-league-2026/bltedf9c4b411ec7212", "https://www.forbes.com/sites/justinteitelbaum/2026/05/29/the-worlds-most-valuable-soccer-teams-2026/"]'::jsonb, '[]'::jsonb, 'web_research')
  on conflict (external_key) do update set name = excluded.name, short_name = excluded.short_name, sport = excluded.sport, league = excluded.league, country = excluded.country, city = excluded.city, stadium = excluded.stadium, stadium_capacity = excluded.stadium_capacity, stadium_capacity_source_url = excluded.stadium_capacity_source_url, founded_year = excluded.founded_year, domain = excluded.domain, ownership_type = excluded.ownership_type, ownership_summary = excluded.ownership_summary, ownership_source_url = excluded.ownership_source_url, revenue = excluded.revenue, revenue_currency = excluded.revenue_currency, revenue_season = excluded.revenue_season, revenue_source_name = excluded.revenue_source_name, revenue_source_url = excluded.revenue_source_url, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, valuation_year = excluded.valuation_year, valuation_source_name = excluded.valuation_source_name, valuation_source_url = excluded.valuation_source_url, social_followers = excluded.social_followers, social_as_of = excluded.social_as_of, social_source_url = excluded.social_source_url, social_platforms = excluded.social_platforms, notes = excluded.notes, sources = excluded.sources, verification = excluded.verification, source = excluded.source;

insert into public.sports_teams (external_key, name, short_name, sport, league, country, city, domain, source)
  values ('la-liga--ca-osasuna', 'CA Osasuna', 'Osasuna', 'football', 'La Liga', 'Spain', 'Pamplona', null, 'web_research')
  on conflict (external_key) do nothing;

insert into public.sports_teams (external_key, name, short_name, sport, league, country, city, domain, source)
  values ('la-liga--deportivo-alaves', 'Deportivo Alavés', 'Alavés', 'football', 'La Liga', 'Spain', 'Vitoria-Gasteiz', null, 'web_research')
  on conflict (external_key) do nothing;
