-- data_055_of_120.sql: intelligence dataset 2026-09-29, part 55 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:afc-bournemouth:ryan-sports-ventures:september-2023', null, 'September 2023', 'minority_investment', 'sports', 'football', 'AFC Bournemouth', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--afc-bournemouth'), null, 'Ryan Sports Ventures', 'family_office', (select id from public.companies where lower(name) = lower('Ryan Sports Ventures') limit 1), (select id from public.sports_investors where lower(name) = lower('Ryan Sports Ventures') limit 1), null, null, null, null, null, null, 'Ryan Sports Ventures takes minority stake in Black Knight Football Club', 'The Chicago-based Ryan family''s sports investment arm, minority owners of the Chicago Bears, acquired an undisclosed minority stake in BKFC, the vehicle that owns AFC Bournemouth.', 'Sportico', 'https://www.sportico.com/business/sales/2023/chicago-bears-investors-buy-bill-foleys-bournemouth-1234739606/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:afc-bournemouth:goldman-sachs:december-2024', null, 'December 2024', 'debt_financing', 'sports', 'football', 'AFC Bournemouth', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--afc-bournemouth'), null, 'Goldman Sachs', 'private_credit', (select id from public.companies where lower(name) = lower('Goldman Sachs') limit 1), (select id from public.sports_investors where lower(name) = lower('Goldman Sachs') limit 1), null, null, null, null, null, null, 'AFC Bournemouth establishes Goldman Sachs senior secured credit facility', 'Proceeds of a senior secured credit facility with Goldman Sachs put in place in December 2024 were used to repay £29.4m of City National Bank loans and £6.4m owed to Black Knight Football Club UK Limited, per the club''s FY2025 accounts.', 'The Esk (analysis of AFC Bournemouth Limited FY2025 accounts)', 'https://theesk.org/2026/05/11/the-analysis-series-afc-bournemouth-limited-annual-report-and-financial-statements-for-the-year-ended-30-june-2025/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:afc-bournemouth:black-knight-stadium-limited-bkfc:2025-04-25', '2025-04-25', '25 April 2025', 'acquisition', 'sports', 'football', 'AFC Bournemouth', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--afc-bournemouth'), null, 'Black Knight Stadium Limited (BKFC)', 'consortium', (select id from public.companies where lower(name) = lower('Black Knight Stadium Limited (BKFC)') limit 1), (select id from public.sports_investors where lower(name) = lower('Black Knight Stadium Limited (BKFC)') limit 1), 'Structadene', null, null, null, null, null, 'BKFC buys Vitality Stadium back from Structadene', 'A newly created BKFC entity, Black Knight Stadium Limited, entered a binding contract to acquire the Vitality Stadium from property company Structadene, which had owned it since 2005 (bought for £3.5m). No price disclosed; the purchase enables the planned expansion to 20,000+ seats.', 'AFC Bournemouth', 'https://www.afcb.co.uk/news/2025/april/25/afc-bournemouth-announces-acquisition-of-vitality-stadium/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
