-- data_086_of_120.sql: intelligence dataset 2026-09-29, part 86 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:aligned-data-centers:ai-infrastructure-partnership-mgx-and-blackrock-s-gip:2026-07-20', '2026-07-20', null, 'company_acquisition', 'infrastructure', null, 'Aligned Data Centers', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Aligned Data Centers') limit 1), 'AI Infrastructure Partnership, MGX and BlackRock''s GIP', 'consortium', (select id from public.companies where lower(name) = lower('AI Infrastructure Partnership, MGX and BlackRock''s GIP') limit 1), (select id from public.sports_investors where lower(name) = lower('AI Infrastructure Partnership, MGX and BlackRock''s GIP') limit 1), 'Macquarie Asset Management', null, null, null, 40000000000, 'USD', 'AIP, MGX and GIP close $40bn acquisition of Aligned Data Centers', 'Largest data centre M&A deal on record; 100% of the equity from Macquarie Asset Management, with a further $5bn committed for expansion; 51 campuses and 6.4GW operational and planned capacity.', 'Business Wire', 'https://www.businesswire.com/news/home/20260720395324/en/AIP-MGX-and-BlackRocks-GIP-Close-Acquisition-of-Aligned-Data-Centers', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:aes-corporation:global-infrastructure-partners-and-eqt-with-calpers-and-qia:2026-03-02', '2026-03-02', null, 'company_acquisition', 'infrastructure', null, 'AES Corporation', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('AES Corporation') limit 1), 'Global Infrastructure Partners and EQT (with CalPERS and QIA)', 'consortium', (select id from public.companies where lower(name) = lower('Global Infrastructure Partners and EQT (with CalPERS and QIA)') limit 1), (select id from public.sports_investors where lower(name) = lower('Global Infrastructure Partners and EQT (with CalPERS and QIA)') limit 1), null, null, 10700000000, 'USD', 33400000000, 'USD', 'GIP and EQT-led consortium agrees to acquire AES for $15 a share, a $33.4bn enterprise value', 'Total equity value of $10.7bn; AES stockholders approved the deal on 26 June 2026; closing expected late 2026 or early 2027.', 'PR Newswire (AES)', 'https://www.prnewswire.com/news-releases/consortium-led-by-global-infrastructure-partners-and-eqt-agrees-to-acquire-aes-302700916.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:helix-digital-infrastructure:samsung:2026-09-28', '2026-09-28', null, 'minority_investment', 'infrastructure', null, 'Helix Digital Infrastructure', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('Helix Digital Infrastructure') limit 1), 'Samsung', 'corporate', (select id from public.companies where lower(name) = lower('Samsung') limit 1), (select id from public.sports_investors where lower(name) = lower('Samsung') limit 1), null, null, 1000000000, 'USD', null, null, 'Samsung group companies to invest $1bn in KKR-backed Helix Digital Infrastructure', 'AI infrastructure company backed by KKR.', 'Bloomberg', 'https://www.bloomberg.com/news/articles/2026-09-28/samsung-to-invest-1-billion-in-kkr-s-ai-infrastructure-company', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
