-- data_089_of_120.sql: intelligence dataset 2026-09-29, part 89 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:national-grid-renewables:brookfield-asset-management:february-2025', null, 'February 2025', 'company_acquisition', 'infrastructure', null, 'National Grid Renewables', 'company', 'United States', null, (select id from public.companies where lower(name) = lower('National Grid Renewables') limit 1), 'Brookfield Asset Management', 'private_equity', (select id from public.companies where lower(name) = lower('Brookfield Asset Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Brookfield Asset Management') limit 1), 'National Grid', null, 1735000000, 'USD', null, null, 'Brookfield agrees to acquire National Grid''s US onshore renewables business for $1.735bn', '1.8GW operating and 1.3GW under construction of solar, onshore wind and storage.', 'ESG Today', 'https://www.esgtoday.com/brookfield-acquires-national-grids-u-s-renewables-business-for-1-7-billion/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:brookfield-infrastructure-fund-v:brookfield-asset-management:december-2023', null, 'December 2023', 'fund_close', 'infrastructure', null, 'Brookfield Infrastructure Fund V', 'fund', 'Canada', null, (select id from public.companies where lower(name) = lower('Brookfield Infrastructure Fund V') limit 1), 'Brookfield Asset Management', 'private_equity', (select id from public.companies where lower(name) = lower('Brookfield Asset Management') limit 1), (select id from public.sports_investors where lower(name) = lower('Brookfield Asset Management') limit 1), null, null, 30000000000, 'USD', null, null, 'Brookfield raises a record $30bn for Infrastructure Fund V', '$28bn for the fund and about $2bn in related co-investment vehicles; the largest closed-end private infrastructure fund at the time.', 'Brookfield Asset Management', 'https://bam.brookfield.com/press-releases/brookfield-raises-record-30-billion-flagship-infrastructure-strategy', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:starwood-distressed-opportunity-fund-xiii:starwood-capital-group:2026-07-01', '2026-07-01', null, 'fund_close', 'real_estate', null, 'Starwood Distressed Opportunity Fund XIII', 'fund', 'United States', null, (select id from public.companies where lower(name) = lower('Starwood Distressed Opportunity Fund XIII') limit 1), 'Starwood Capital Group', 'private_equity', (select id from public.companies where lower(name) = lower('Starwood Capital Group') limit 1), (select id from public.sports_investors where lower(name) = lower('Starwood Capital Group') limit 1), null, null, 10200000000, 'USD', null, null, 'Starwood Capital raises $10.2bn for SOF XIII, the largest fund in its history', '300-plus pensions, sovereign funds and endowments; residential, data centre, industrial and hospitality focus across the US and Europe.', 'PR Newswire', 'https://www.prnewswire.com/news-releases/starwood-capital-group-raises-10-2-billion-opportunistic-real-estate-fund-302815286.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
