-- data_066_of_120.sql: intelligence dataset 2026-09-29, part 66 of 120. Run in order; safe to re-run.

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:chelsea-football-club:clearlake-capital-group:2026-09-16', '2026-09-16', '16 September 2026', 'stake_sale', 'sports', 'football', 'Chelsea Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--chelsea'), null, 'Clearlake Capital Group', 'private_equity', (select id from public.companies where lower(name) = lower('Clearlake Capital Group') limit 1), (select id from public.sports_investors where lower(name) = lower('Clearlake Capital Group') limit 1), 'Todd Boehly and Mark Walter', 25.66, 950000000, 'GBP', 5000000000, 'GBP', 'Clearlake buys out Boehly and Walter for £950m, takes full control of Chelsea', 'Clearlake Capital, already holding 61.5%, acquired the roughly 12.8% stakes each of Todd Boehly and Mark Walter for a combined £950m, valuing Chelsea at £5bn including debt. Boehly stepped down as chairman; Hansjörg Wyss remains a shareholder.', 'CNBC', 'https://www.cnbc.com/2026/09/17/chelsea-mark-walter-bohely-clearlake-capital.html', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:crystal-palace-football-club:josh-harris-and-david-blitzer:december-2015', null, 'December 2015', 'minority_investment', 'sports', 'football', 'Crystal Palace Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--crystal-palace'), null, 'Josh Harris and David Blitzer', 'individual', (select id from public.companies where lower(name) = lower('Josh Harris and David Blitzer') limit 1), (select id from public.sports_investors where lower(name) = lower('Josh Harris and David Blitzer') limit 1), null, 36, 50000000, 'GBP', null, null, 'Harris and Blitzer take 18% each in Crystal Palace with £50m capital injection', 'Josh Harris (Apollo co-founder) and David Blitzer (Blackstone) each acquired 18% of Crystal Palace, injecting £50m of capital and forming a general partnership with chairman Steve Parish. The investors also committed a further £50m towards stadium development.', 'SportBusiness', 'https://www.sportbusiness.com/news/crystal-palace-confirms-investment-deal-with-american-businessmen/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;

insert into public.deals (external_key, date, date_text, kind, asset_class, sport, target, target_kind, target_country, target_team_id, target_company_id, investor, investor_type, investor_company_id, investor_id, seller, stake_pct, amount, currency, valuation, valuation_currency, headline, summary, source_name, source_url, source)
  values ('deal:crystal-palace-football-club:john-textor-eagle-football-holdings:august-2021', null, 'August 2021', 'minority_investment', 'sports', 'football', 'Crystal Palace Football Club', 'club', 'England', (select id from public.sports_teams where external_key = 'premier-league--crystal-palace'), null, 'John Textor (Eagle Football Holdings)', 'individual', (select id from public.companies where lower(name) = lower('John Textor (Eagle Football Holdings)') limit 1), (select id from public.sports_investors where lower(name) = lower('John Textor (Eagle Football Holdings)') limit 1), null, 40, 87500000, 'GBP', null, null, 'John Textor invests £87.5m for 40% of Crystal Palace', 'US businessman John Textor bought a 40% stake in Crystal Palace for a reported £87.5m (some reports say £86m), joining Parish, Harris and Blitzer as a co-owner. The stake was later held through Eagle Football Holdings.', 'City AM', 'https://www.cityam.com/who-owns-crystal-palace-now-how-much-did-john-textor-josh-harris-and-david-blitzer-and-his-co-owners-pay/', 'web_research')
  on conflict (external_key) do update set date = excluded.date, date_text = excluded.date_text, kind = excluded.kind, asset_class = excluded.asset_class, sport = excluded.sport, target = excluded.target, target_kind = excluded.target_kind, target_country = excluded.target_country, target_team_id = excluded.target_team_id, target_company_id = excluded.target_company_id, investor = excluded.investor, investor_type = excluded.investor_type, investor_company_id = excluded.investor_company_id, investor_id = excluded.investor_id, seller = excluded.seller, stake_pct = excluded.stake_pct, amount = excluded.amount, currency = excluded.currency, valuation = excluded.valuation, valuation_currency = excluded.valuation_currency, headline = excluded.headline, summary = excluded.summary, source_name = excluded.source_name, source_url = excluded.source_url, source = excluded.source;
