-- data_114_of_120.sql: intelligence dataset 2026-09-29, part 114 of 120. Run in order; safe to re-run.

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:all:deal_volume:2025:jefferies:global-secondary-market-transaction-volu', 'secondaries', null, 'deal_volume', 'Global secondary market transaction volume, 2025 (record, up 48%)', 240000000000, 'USD', '2025', 'Global', 'Jefferies', null, 'https://www.jefferies.com/insights/the-big-picture/2025-global-secondary-market-review-another-record-breaking-year/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:sec_lp_led:deal_volume:2025:jefferies:lp-led-secondary-volume-2025-up-34', 'secondaries', 'sec_lp_led', 'deal_volume', 'LP-led secondary volume, 2025 (up 34%)', 120000000000, 'USD', '2025', 'Global', 'Jefferies', null, 'https://www.jefferies.com/insights/the-big-picture/2025-global-secondary-market-review-another-record-breaking-year/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:sec_gp_led:deal_volume:2025:jefferies:gp-led-secondary-volume-2025-up-51', 'secondaries', 'sec_gp_led', 'deal_volume', 'GP-led secondary volume, 2025 (up 51%)', 106000000000, 'USD', '2025', 'Global', 'Jefferies', null, 'https://www.jefferies.com/insights/the-big-picture/2025-global-secondary-market-review-another-record-breaking-year/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:all:dry_powder:2025:jefferies:dedicated-secondary-capital-2025-record-', 'secondaries', null, 'dry_powder', 'Dedicated secondary capital, 2025 (record, up 14% from year-end 2024)', 327000000000, 'USD', '2025', 'Global', 'Jefferies', null, 'https://www.jefferies.com/insights/the-big-picture/2025-global-secondary-market-review-another-record-breaking-year/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:all:deal_volume:2025:evercore-private-capital-advisory:global-secondary-transaction-volume-2025', 'secondaries', null, 'deal_volume', 'Global secondary transaction volume, 2025, up 41% (Evercore)', 226000000000, 'USD', '2025', 'Global', 'Evercore Private Capital Advisory', null, 'https://www.ai-cio.com/news/secondaries-volume-reached-record-in-2025-as-lps-embrace-market/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:all:deal_volume:h1-2026:pitchbook:secondary-deal-volume-h1-2026-first-half', 'secondaries', null, 'deal_volume', 'Secondary deal volume, H1 2026 (first-half record)', 120000000000, 'USD', 'H1 2026', 'Global', 'PitchBook', null, 'https://pitchbook.com/news/articles/continuation-funds-drive-record-h1-for-secondary-market', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('secondaries:sec_gp_led:deal_volume:h1-2026:pitchbook:gp-led-secondary-volume-h1-2026-up-35-54', 'secondaries', 'sec_gp_led', 'deal_volume', 'GP-led secondary volume, H1 2026 (up 35%; 54% of activity)', 65000000000, 'USD', 'H1 2026', 'Global', 'PitchBook', null, 'https://pitchbook.com/news/articles/continuation-funds-drive-record-h1-for-secondary-market', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('hedge_funds:all:aum:q2-2026:hfr:global-hedge-fund-industry-capital-end-o', 'hedge_funds', null, 'aum', 'Global hedge fund industry capital, end of Q2 2026 (15th consecutive quarterly rise)', 5600000000000, 'USD', 'Q2 2026', 'Global', 'HFR', null, 'https://www.hfr.com/media/market-commentary/global-hedge-fund-industry-capital-surges-past-historic-5-trillion-milestone/', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;
