-- data_108_of_120.sql: intelligence dataset 2026-09-29, part 108 of 120. Run in order; safe to re-run.

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:los-angeles-county-employees-retirement-association:ae-industrial-partners-iv:2026', (select id from public.companies where lower(name) = lower('Los Angeles County Employees Retirement Association') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('AE Industrial Partners IV') limit 1), (select id from public.companies where lower(name) = lower('AE Industrial Partners') limit 1)), (select id from public.funds where lower(name) = lower('AE Industrial Partners IV') limit 1), 'Los Angeles County Employees Retirement Association', 'AE Industrial Partners', 'AE Industrial Partners IV', 350000000, 'USD', null, null, '2026 Board of Investments', 2026, 'news', 'web_research', 'https://www.dakota.com/fundraising-news/lacera-approves-2.2b-in-commitments-to-seven-alts-funds', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:los-angeles-county-employees-retirement-association:bregal-sagemount-v:2026', (select id from public.companies where lower(name) = lower('Los Angeles County Employees Retirement Association') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('Bregal Sagemount V') limit 1), (select id from public.companies where lower(name) = lower('Bregal Sagemount') limit 1)), (select id from public.funds where lower(name) = lower('Bregal Sagemount V') limit 1), 'Los Angeles County Employees Retirement Association', 'Bregal Sagemount', 'Bregal Sagemount V', 190000000, 'USD', null, null, '2026 Board of Investments', 2026, 'news', 'web_research', 'https://www.dakota.com/fundraising-news/lacera-approves-2.2b-in-commitments-to-seven-alts-funds', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.commitments (external_key, lp_company_id, gp_company_id, fund_id, lp_name, gp_name, fund_name, amount, currency, amount_text, commitment_date, commitment_date_text, commitment_year, disclosure_type, source, source_url, source_date)
  values ('lpcommit:los-angeles-county-employees-retirement-association:regal-healthcare-capital-partners-iv:2026', (select id from public.companies where lower(name) = lower('Los Angeles County Employees Retirement Association') limit 1), coalesce((select company_id from public.funds where lower(name) = lower('Regal Healthcare Capital Partners IV') limit 1), (select id from public.companies where lower(name) = lower('Regal Healthcare Capital Management') limit 1)), (select id from public.funds where lower(name) = lower('Regal Healthcare Capital Partners IV') limit 1), 'Los Angeles County Employees Retirement Association', 'Regal Healthcare Capital Management', 'Regal Healthcare Capital Partners IV', 150000000, 'USD', null, null, '2026 Board of Investments', 2026, 'news', 'web_research', 'https://www.dakota.com/fundraising-news/lacera-approves-2.2b-in-commitments-to-seven-alts-funds', '2026-09-29')
  on conflict (external_key) do update set lp_company_id = excluded.lp_company_id, gp_company_id = excluded.gp_company_id, fund_id = excluded.fund_id, lp_name = excluded.lp_name, gp_name = excluded.gp_name, fund_name = excluded.fund_name, amount = excluded.amount, currency = excluded.currency, amount_text = excluded.amount_text, commitment_date = excluded.commitment_date, commitment_date_text = excluded.commitment_date_text, commitment_year = excluded.commitment_year, disclosure_type = excluded.disclosure_type, source = excluded.source, source_url = excluded.source_url, source_date = excluded.source_date;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:fundraising_total:2025:s-p-global-market-intelligence-preqin-data:global-private-equity-fundraising-2025-b', 'private_equity', null, 'fundraising_total', 'Global private equity fundraising, 2025 (buyout, growth, secondaries, GP stakes, diversified), down 11.0%', 490810000000, 'USD', '2025', 'Global', 'S&P Global Market Intelligence (Preqin data)', null, 'https://www.spglobal.com/market-intelligence/en/news-insights/articles/2026/1/private-equity-fundraising-totals-continue-to-decline-in-2025-96694779', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;

insert into public.benchmarks (external_key, asset_class, strategy, metric, label, value, unit, period, geography, publisher, published_on, source_url, note, source)
  values ('private_equity:all:fundraising_total:q1q3-2025:preqin:global-private-equity-fundraising-q1q3-2', 'private_equity', null, 'fundraising_total', 'Global private equity fundraising, Q1–Q3 2025 (73% of 2024''s total)', 507000000000, 'USD', 'Q1–Q3 2025', 'Global', 'Preqin', null, 'https://www.blackrock.com/aladdin/discover/press-release-preqins-global-reports-private-markets-trends-2025', null, 'web_research')
  on conflict (external_key) do update set asset_class = excluded.asset_class, strategy = excluded.strategy, metric = excluded.metric, label = excluded.label, value = excluded.value, unit = excluded.unit, period = excluded.period, geography = excluded.geography, publisher = excluded.publisher, published_on = excluded.published_on, source_url = excluded.source_url, note = excluded.note, source = excluded.source;
